### ISSUE TITLE
Template file update: Chips, Select, & Wizard

### ISSUE THREAD

**Issue by bdiring** [patternfly/patternfly-design-kit#101]
Added **Chips**, **Select**, and **Wizard** components to the "patternfly-template" Sketch file using PatternFly symbols (with the new RH font).

[patternfly-template.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/3714299/patternfly-template.sketch.zip)

Artboards added:

**Chips** page:
Chips spec
Chip Groups / Expanded & dismissible
Chip Groups / Expanded
Chip Group / Collapsed
Chip Group / Collapsed multi-select
Chip Group / Expanded
Chip Group / Expanded multi-select

**Select** page:
Select spec
Select / Single with typeahead (expanded & selected)
Select / Multi with typeahead (expanded, chip group expanded)
Select / Multi with typeahead (expanded, chip group collapsed)
Select / Checkbox (expanded)
Select / Checkbox (expanded & selected with groups)

**Wizard** page: 
Wizard spec
Wizard / Non-progressive - desktop
Wizard / Simple progressive - desktop
Wizard / Progressive - desktop
Wizard / Compact nav - desktop
Wizard / Finished - desktop
Wizard / In-page - desktop
Wizard / Compact nav - mobile
Wizard / Expanded - mobile
Wizard / Finished - mobile

**Comment by gdoyle1** [comment]
Merged! Thanks for your work @bdiring
