### ISSUE TITLE
Template Update: Add Empty States

### ISSUE THREAD

**Issue by doruskova** [patternfly/patternfly-design-kit#103]
I added an Empty state page to the template with a new RH font. Link is here [patternfly-template.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/3729458/patternfly-template.sketch.zip)

There's also an artboard with padding. Hope it's ok :) @gdoyle1 
![screenshot](https://user-images.githubusercontent.com/32618096/66835653-32d17f00-ef60-11e9-9ec2-26e71c3ae538.png)

**Comment by gdoyle1** [comment]
Merged! Thanks @doruskova !!
