### ISSUE TITLE
Center-aligned text - issue on donut charts

### ISSUE THREAD

**Issue by katierik** [patternfly/patternfly-design-kit#104]
![Xnip2019-10-15_10-03-02](https://user-images.githubusercontent.com/23172038/66838683-1b2fd180-ef33-11e9-94cf-c075caef815d.jpg)

The donut charts with sublabel do not have centered text. When putting in a longer label, it breaks as seen.
There needs to be a new text style for centered text that is then used in the chart subtitle.

**Comment by gdoyle1** [comment]
Just fixed

**Comment by katierik** [comment]
Noticing this in the RH font version as well:
![Xnip2019-11-06_14-54-40](https://user-images.githubusercontent.com/23172038/68332899-8c335680-00a5-11ea-8eb2-35ae8ac14b4e.jpg)

**Comment by gdoyle1** [comment]
Fixed in the RH one! sorry about that @katierik
