### ISSUE TITLE
Color names and values

### ISSUE THREAD

**Issue by ajacobs21e** [patternfly/patternfly-design-kit#105]
There are a few related issues here:

1. The sketch library layer styles and color swatches use variables like `pf-black-600`.
This doc shows the names as `$pf-color-black-600`
https://github.com/patternfly/patternfly-next/blob/master/src/patternfly/sass-utilities/colors.scss
Do we need to update layer style and color swatch names to add in `-color` to these variable names? 
![Screen Shot 2019-10-16 at 1 57 55 PM](https://user-images.githubusercontent.com/6415742/66945642-60c8c900-f01d-11e9-8fe2-27daa6049c96.png)

2. Some color values have changed. The one I know that changed is the secondary color / `pf-black-600`. The new value is #737679 and the layer style has been updated to match. However there is no matching color swatch now. 
![Screen Shot 2019-10-16 at 1 58 10 PM](https://user-images.githubusercontent.com/6415742/66945644-61615f80-f01d-11e9-8e4c-6e8e280b754b.png)

The color swatch still has the old value, #72767b
![Screen Shot 2019-10-16 at 1 58 18 PM](https://user-images.githubusercontent.com/6415742/66945643-61615f80-f01d-11e9-9738-f6aefdc8f91d.png)

This color swatch needs to be updated, as well as any other colors that may have changed. We'd need to do a comparison to the list of variables I linked earlier or ask a dev what other color values (if any) changed.

**Comment by gdoyle1** [comment]
Fixed this in both Patternfly 4 Overpass and PatternFly libraries! Let me know if there is more confusion here @ajacobs21e @katierik
