### ISSUE TITLE
Template file update: Card view

### ISSUE THREAD

**Issue by bdiring** [patternfly/patternfly-design-kit#106]
Added **Card view** component to the "patternfly-template" Sketch file using PatternFly symbols (with the new RH font).

[patternfly-template.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/3740482/patternfly-template.sketch.zip)

Artboards added:

**Card view** page:
Cards spec
Cards
Card view standard - desktop
Card view - desktop
Card view standard - mobile
Card view - mobile

**Comment by gdoyle1** [comment]
merged! thanks @bdiring
