### ISSUE TITLE
Template update: Form 

### ISSUE THREAD

**Issue by doruskova** [patternfly/patternfly-design-kit#107]
I added a Form page into a PF Template with a new RH font. 
Here's the link: [patternfly-template.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/3744191/patternfly-template.sketch.zip)

And preview is below
<img width="963" alt="form" src="https://user-images.githubusercontent.com/32618096/67099295-f733f080-f1bd-11e9-81c7-f4f8ce955385.png">

**Comment by gdoyle1** [comment]
Merged! Thanks @doruskova
