### ISSUE TITLE
Template update: Page and Toast Alerts

### ISSUE THREAD

**Issue by doruskova** [patternfly/patternfly-design-kit#108]
Page and Toast alert with their spec has been added into a PF Template (RH font).
Link here: [patternfly-template.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/3761898/patternfly-template.sketch.zip)
@gdoyle1 
Preview: 
![snapshot1](https://user-images.githubusercontent.com/32618096/67385821-16eb6000-f594-11e9-899a-2b68fd23860f.png)
![snapshot2](https://user-images.githubusercontent.com/32618096/67385837-1d79d780-f594-11e9-9c4e-d027c8b7e2b9.png)

**Comment by gdoyle1** [comment]
Thanks @doruskova - merged this!
