### ISSUE TITLE
Template file update: Table

### ISSUE THREAD

**Issue by bdiring** [patternfly/patternfly-design-kit#109]
Added **Table** component to the "patternfly-template" Sketch file using PatternFly symbols (with the new RH font).

[patternfly-template.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/3783924/patternfly-template.sketch.zip)

Artboards added to the **Table** page:

Table spec
Table / Standard - desktop
Table / Compact - desktop
Table / Sortable - desktop
Table / Standard - mobile xs
Table / Compact - mobile xs

**Comment by gdoyle1** [comment]
Thanks @bdiring ! Merged
