### ISSUE TITLE
Text style change - Add Size 4xl and change Size3xl

### ISSUE THREAD

**Issue by mmenestr** [patternfly/patternfly-design-kit#111]
The sketch library text styles need to be edited. Currently, Size 3xl text style uses 36pt font, and there is no Size 4xl. Need to change that in the sketch library so that it matches with the styles in the screenshot here:

<img width="480" alt="Screen Shot 2019-11-05 at 2 28 23 PM" src="https://user-images.githubusercontent.com/51165119/68241509-cdabff00-ffdc-11e9-8878-ed10799409fe.png">

Ending result should be Size 3xl, 28pt and Size 4xl, 36pt! Thank you!!

**Comment by mmenestr** [comment]
@gdoyle1

**Comment by gdoyle1** [comment]
Just pushed it to the cloud!
