### ISSUE TITLE
Tertiary nav background padding should be margin on tabs

### ISSUE THREAD

**Issue by cshinn** [patternfly/patternfly-design-kit#114]
Currently the height of tertiary nav items don't match the height of the tertiary nav background.
Rather than including invisible padding on the background element, the 8 and 16px spacers should be added as margin to the nav element symbols so that they snap and align correctly. 

<img width="283" alt="Screen Shot 2019-11-22 at 10 54 09 AM" src="https://user-images.githubusercontent.com/3300756/69440250-77e29100-0d16-11ea-8595-c29a8574a8b4.png">

**Comment by gdoyle1** [comment]
Added the padding to each item so now they should snap!
