### ISSUE TITLE
Text style ordering

### ISSUE THREAD

**Issue by ajacobs21e** [patternfly/patternfly-design-kit#115]
Can we number the text styles so they show up in order rather than alphabetically? 
ex: 
1. xs
2. sm
3. md
etc.
or biggest to smallest, although since md is probably the most used having it closer to the top is maybe better

Also within md the first choice is pf-c-nav__horizontal-list-link. Can this be moved to a different category or renamed so it's not the default choice for medium font?

**Comment by gdoyle1** [comment]
Just updated this so it goes from largest to smallest. Figured that'd be easiest
