### ISSUE TITLE
16px Regular and Link text styles misaligned

### ISSUE THREAD

**Issue by andybraren** [patternfly/patternfly-design-kit#117]
Both have a line height of 24, but for some reason one of them (not sure which) is `1px` off vertically. The hover, hover-button, and light variants of Link are also `1px` different.

![image](https://user-images.githubusercontent.com/9122899/69484889-65478500-0e06-11ea-92e3-a4c1fe48d581.png)

**Comment by gdoyle1** [comment]
Just fixed this!
