### ISSUE TITLE
Split button action variant

### ISSUE THREAD

**Issue by gdoyle1** [patternfly/patternfly-design-kit#118]
Add symbols for the split button action variant. Here is the PR https://github.com/patternfly/patternfly-react/pull/3307.

**Comment by gdoyle1** [comment]
@lboehling

**Comment by lboehling** [comment]
Added New Symbols for Split Action 

[patternfly-splitbutton:forminputgroup.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/3918401/patternfly-splitbutton.forminputgroup.sketch.zip)
Button

Dropdowns / 1. Toggle / Split / With Text / Default
Dropdowns / 1. Toggle / Split / With Text / Hover
Dropdowns / 1. Toggle / Split / With Text / Selected
Dropdowns / 1. Toggle / Split / With Text / Disabled
Dropdowns / 1. Toggle / Split / With Text / Focus
Dropdowns / 1. Toggle / Split / Action / Icons
Dropdowns / 1. Toggle / Split / Action / Default
Dropdowns / 1. Toggle / Split / Action / Hover
Dropdowns / 1. Toggle / Split / Action / Selected
Dropdowns / 1. Toggle / Split / Action / Disabled

@gdoyle1

**Comment by gdoyle1** [comment]
Merged!
