### ISSUE TITLE
Success state of input field

### ISSUE THREAD

**Issue by gdoyle1** [patternfly/patternfly-design-kit#119]
Create a variation of the input field that includes success styling. https://github.com/patternfly/patternfly-next/issues/2320

Will tag you @maryshak1996 once the color palette has been updated!

**Comment by maryshak1996** [comment]
Not sure what the best way to share this is but here's a sketch cloud link that has the new symbol. Note: to be consistent with how the danger state works, I created an appearance for the green underline
The naming structure of everything (the symbol itself, the padding group, the success underline appearance, etc.) should all be consistent with the structure used in the library. so *in theory* you could be able to just copy-paste the symbol into the master file's symbol page!
https://sketch.cloud/s/bZaVj

**Comment by maryshak1996** [comment]
![image](https://user-images.githubusercontent.com/19824574/69996014-2b216600-151f-11ea-9cfc-58b524ebfd4e.png)
^ preview

**Comment by gdoyle1** [comment]
That's great! Thanks @maryshak1996 - in the future, you can also zip the sketch file in your comment but sketch cloud works as well!

**Comment by gdoyle1** [comment]
@maryshak1996 Just requested access for that sketch file

**Comment by gdoyle1** [comment]
Merged!
