### ISSUE TITLE
Application launcher template

### ISSUE THREAD

**Issue by gdoyle1** [patternfly/patternfly-design-kit#120]
Add an example of the application launcher to the template file. Here is the PR: https://github.com/patternfly/patternfly-next/issues/2365. 

Add symbols necessary for library and then add template example.

**Comment by maryshak1996** [comment]
@gdoyle1 I think that I have the symbols complete for the application launcher!
Should that get merged into the library first, and then I we can talk about making the template for it once that happens?
[application-launcher_addition.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/3951116/application-launcher_addition.sketch.zip)

**Comment by gdoyle1** [comment]
Oh great @maryshak1996 ! Yes - I'll merge that now and then once you receive the library update in Sketch, we can create the template! Let me know what you want to do that for that - I'm willing to create the whole thing or split it with you.

**Comment by gdoyle1** [comment]
Creating another issue to track the template addition for this
