### ISSUE TITLE
Issues with using Font Awesome for icons

### ISSUE THREAD

**Issue by mmenestr** [patternfly/patternfly-design-kit#122]
Creating this issue to document issues we run into with empty states icons being font awesome instead of the standard svg @gdoyle1 @mceledonia

**Comment by mmenestr** [comment]
**Issue 1**
Gina was asked to replace font awesome font. Theoretically we should all have the same one so we don't really understand why that's happening

<img width="460" alt="Screen Shot 2019-11-25 at 3 51 46 PM" src="https://user-images.githubusercontent.com/51165119/69577450-598dc700-0f9c-11ea-8dcd-931e9c0c0221.png">

**Comment by gdoyle1** [comment]
Closing this since we came up with a solution for the icons: https://docs.google.com/document/d/1x9wnkQBQ8A393ROMwGDz6jAbop3tTzUi5BFmPk2bc6E/edit?usp=sharing
