### ISSUE TITLE
Symbol library: Update input groups with icon to have a line in between the text box and the icon

### ISSUE THREAD

**Issue by mmenestr** [patternfly/patternfly-design-kit#127]
Currently, all the symbols under  **Forms / 2. Text box / With Icon** do not have a line in between the text field and the icon, [as is shown in core.](https://www.patternfly.org/v4/documentation/react/components/inputgroup)

Need to add that line so that it goes from this:
<img width="358" alt="Screen Shot 2019-11-26 at 4 17 17 PM" src="https://user-images.githubusercontent.com/51165119/69673518-72fc4500-1068-11ea-879d-bc7187678e38.png">

To this:
<img width="528" alt="Screen Shot 2019-11-26 at 4 19 36 PM" src="https://user-images.githubusercontent.com/51165119/69673566-90c9aa00-1068-11ea-9eef-82ab9f3065c6.png">

Variations of this symbol in the library include Active, Default, Disabled, Error, Focus, Hover and Placeholder

@lboehling

**Comment by lboehling** [comment]
Updated Form Input w Icon Symbols

Forms / 2. Text Box / With Icon / Default
Forms / 2. Text Box / With Icon / Hover
Forms / 2. Text Box / With Icon / Selected
Forms / 2. Text Box / With Icon / Disabled
Forms / 2. Text Box / With Icon / Focus
Forms / 2. Text Box / With Icon / Error
Forms / 2. Text Box / With Icon / Placeholder

[patternfly-splitbutton:forminputgroup.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/3918406/patternfly-splitbutton.forminputgroup.sketch.zip)

@gdoyle1

**Comment by gdoyle1** [comment]
Merged! Thank you @lboehling !
