### ISSUE TITLE
Empty state icons break on placement

### ISSUE THREAD

**Issue by cshinn** [patternfly/patternfly-design-kit#129]
Empty-state-sized icons break when placed on the page rendering [?] instead of the intended icon. I have the correct Fontawesome installed to render these icons, so it doesn't appear to be because of that. Using SVGs for these icons instead of an icon font would prevent this problem

**Comment by gdoyle1** [comment]
Hey @cshinn thanks for documenting this bug! This is something we were assuming would happen but wanted to try out the fontawesome font (for ease of creation purposes). Thanks for letting us know. There is a massive icon effort going on to audit PF icons now and once that has been completed, we will be adding icons as SVGs so this problem won't occur.

As a fix (for now if you want) you can "replace missing fonts" with your fontaweomse font you have installed on your local. I had this problem as well. Sketch removes the spaces between words of the font so it doesn't exactly match what you have in font book (is my assumption).

cc: @mmenestr @mceledonia

**Comment by gdoyle1** [comment]
We converted these empty state icons to outlines so they are SVGs. Will close this this has been fixed
