### ISSUE TITLE
Dropdown toggle with typeahead is different height

### ISSUE THREAD

**Issue by cshinn** [patternfly/patternfly-design-kit#130]
The `dropdown toggle with typeahead` symbol is 40px tall while all other dropdown toggles are 36px tall

**Comment by gdoyle1** [comment]
That's because when chips are added to the input field, it becomes taller: https://pf4.patternfly.org/documentation/core/components/select#multi-with-typeahead-chip-group-expanded. According to the code it looks like it actually should be 42px tall.

**Comment by gdoyle1** [comment]
I updated the height to 42px as it is in the code. We can make further updates if this is changed on the development side! Going to close this now though.
