### ISSUE TITLE
Application launcher

### ISSUE THREAD

**Issue by gdoyle1** [patternfly/patternfly-design-kit#131]
Create full screen application launcher mocks in the template file using the new application symbols from PatternFly

**Comment by maryshak1996** [comment]
[app-launcher-template.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/3969932/app-launcher-template.sketch.zip)
This has a pretty exhaustive desktop template. I have designs for mobile too, but they are dependent on the merging of the PF tree component that isn't ready yet, so once the tree component gets merged and we need symbols/templates for that, I can take that issue and update this along with it :) 
[app-launcher-template.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/3969946/app-launcher-template.sketch.zip)

**Comment by gdoyle1** [comment]
Awesome! Thank you @maryshak1996 !!

**Comment by gdoyle1** [comment]
Merged
