### ISSUE TITLE
Symbol library: Default and Read-only text boxes

### ISSUE THREAD

**Issue by mmenestr** [patternfly/patternfly-design-kit#133]
The default and read-only text boxes are the same in the sketch library, but they should be different.

What it is:
<img width="478" alt="Screen Shot 2019-12-19 at 8 35 55 AM" src="https://user-images.githubusercontent.com/51165119/71177721-99ae3580-223a-11ea-93c1-ebadc2e775ff.png">

What it should be:
<img width="596" alt="Screen Shot 2019-12-19 at 8 36 14 AM" src="https://user-images.githubusercontent.com/51165119/71177748-a894e800-223a-11ea-85a2-01b814a27d74.png">

**Comment by gdoyle1** [comment]
merged!
