### ISSUE TITLE
border colors incorrect

### ISSUE THREAD

**Issue by ajacobs21e** [patternfly/patternfly-design-kit#134]
Need to update border colors to these:
![Screen Shot 2019-12-20 at 1 46 02 PM](https://user-images.githubusercontent.com/6415742/71283766-1faba880-232f-11ea-9786-a0c59ed8ff67.png)

@mceledonia the border colors we just talked about are correct in the CSS so it's the sketch library that needs to be updated. Should BorderColor--300 be changed to #F0F0F0 or stay #EDEDED?

**Comment by gdoyle1** [comment]
Thanks Allie! So #ededed will be #f0f0f0. The rest are correct!

**Comment by ajacobs21e** [comment]
Sketch library update pushed. 

Changes made:

- Updated the underline-secondary and underline-secondary-bold layer styles from #EDEDED to #F0F0F0 for the right, top, and left borders
- Added border colors for the 5 variables in the screenshot above (and used #F0F0F0 for BorderColor--300)
- Removed the layer styles for BorderColor--light (not used anywhere) and BorderColor--light-200 (used on inline alerts)
- Updated inline alerts to use BorderColor--300 (verified against the code)

**Comment by gdoyle1** [comment]
Thank you! Will close this now @ajacobs21e
