### ISSUE TITLE
Radios with more information

### ISSUE THREAD

**Issue by katierik** [patternfly/patternfly-design-kit#135]
There are use cases to show additional descriptive information with a radio button. 

![Screen Shot 2019-09-26 at 11 10 35 AM](https://user-images.githubusercontent.com/23172038/65710966-fb0ea000-e061-11e9-8047-27b8bbddb2e0.png)

It is likely that this would also be helpful as an option for checkboxes, but I do not have use cases for this as of writing.

Notes/screenshots:
https://docs.google.com/document/d/13NkTdfpH7ZD7gBsmhYgjlux9K2mKa5s9t5JNmFV_KpI/edit?usp=sharing

–––––––––––––––––––––––––––––––––––––––––––––––––––––––––––

Final Designs:
marvel: https://marvelapp.com/50eh328/screen/64407412 
raw file: https://sketch.cloud/s/l8Dk4

**Comment by gdoyle1** [comment]
Merged in symbol library!
