### ISSUE TITLE
Need mixed-state checkbox symbol

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design-kit#137]
Need the ability to insert a "mixed-state" checkbox (i.e. "-") in cases where we want to indicated mixed selection.

**Comment by maryshak1996** [comment]
@gdoyle1 this doc here has all of the updates need (I think) for this issue as well as https://github.com/patternfly/patternfly-design-kit/issues/143#event-2948532389 (the play and pause icons), so if you merge this file it should merge in those icons too

**Comment by maryshak1996** [comment]
[patternfly-library.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/4087451/patternfly-library.sketch.zip)

**Comment by gdoyle1** [comment]
thanks @maryshak1996 ! Just merged
