### ISSUE TITLE
tabs - overflow arrow background and filled tabs

### ISSUE THREAD

**Issue by ajacobs21e** [patternfly/patternfly-design-kit#138]
The primary overflow arrows have a transparent background. I think these should be filled white (and maybe modifiable to match whatever the background color is?). If you put one over a tab you can see the tab name through it.

The filled tabs should have the text centered - it's left aligned
![Screen Shot 2020-01-07 at 12 50 20 PM](https://user-images.githubusercontent.com/6415742/71916600-4ac63280-314c-11ea-9e2c-332f78da091d.png)

Gina I can make these changes if no one else is working on the file today, lmk!

**Comment by gdoyle1** [comment]
For some reason the fill was unchecked for all of these! But I just fixed them. Should get the change soon :) Thanks for reporting this! @ajacobs21e
