### ISSUE TITLE
Selectable data list

### ISSUE THREAD

**Issue by gdoyle1** [patternfly/patternfly-design-kit#140]
1. Add new background layer styles to support hover and select states. (Marvel project: https://marvelapp.com/69dc1eg/screen/62345709)
2. Add template of a selectable data list on data list page.

Original issue here: https://github.com/patternfly/patternfly-react/pull/3404

**Comment by maryshak1996** [comment]
I *think* that this is all set to merge :) once it merges I'm happy to add some examples of this into the template file as well 
[patternfly.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/4110349/patternfly.sketch.zip)

**Comment by gdoyle1** [comment]
Merged! @maryshak1996 That would be GREAT if you could work on a template file example for this too (whenever you get the chance)

**Comment by gdoyle1** [comment]
Reopening to track template work

**Comment by maryshak1996** [comment]
** on hold for a little while until we have more clarity on how this will be implemented **

**Comment by maryshak1996** [comment]
@gdoyle1 I did a whole lot of brainstorming and I think that I may have a more scalable way of looking at this contribution that wouldn't change our current system of using overrides :) 
I put together a doc here detailing my idea
https://docs.google.com/document/d/1-BSk-MPqUfePxzlJjYxfjcxvP7LQA9qMMu3OLJbQz_g/edit?usp=sharing

**Comment by ajacobs21e** [comment]
@maryshak1996 That looks simplified to me! Do you think it's possible to take it a step further and combine these symbols with data list rows?

**Comment by gdoyle1** [comment]
@maryshak1996 wow this looks great! @ajacobs21e  I *think* Mary and I talked about that applying to data lists as well - is that right Mary?

**Comment by maryshak1996** [comment]
@ajacobs21e @gdoyle1 awesome, glad that you guys are cool with that concept! And yes, I was definitely planning to expand it out to the data list too :) 
@gdoyle1 I definitely have the bandwidth to take on the action items of making template updates for the table and data list pages if you want to open/assign those issues to me. I am curious though how we should tackle this though since the structure and usage would be a fairly breaking change to any folks who have sketch files with existing table/data list elements...?

**Comment by gdoyle1** [comment]
That's a great point @maryshak1996 ! I'll bring it up during the meeting today and get others' opinions as well

**Comment by maryshak1996** [comment]
@gdoyle1 
here's the NEW symbols for all things tables and lists (including compact data list) 
[library-contribution_tables+list.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/4160281/library-contribution_tables%2Blist.sketch.zip)

**Comment by maryshak1996** [comment]
Here's the updated template for all things tables and lists (so this should cover the deliverables for https://github.com/patternfly/patternfly-design-kit/issues/160)
[template-contribution.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/4162080/template-contribution.sketch.zip)

**Comment by gdoyle1** [comment]
This is amazing! Thanks so much @maryshak1996 - will close this and #160 out
