### ISSUE TITLE
Add FA 'play' and 'pause' icons to library

### ISSUE THREAD

**Issue by maryshak1996** [patternfly/patternfly-design-kit#143]
OpenShift uses an events stream and a streaming card in the UI. Both of these views rely on 'play' and 'pause' actions, so it would be very helpful to have the following brought in from FA:
Play: https://fontawesome.com/icons/play?style=solid
Pause: https://fontawesome.com/icons/pause?style=solid

**Comment by maryshak1996** [comment]
This should be ready to merge:
[patternfly-library.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/4087403/patternfly-library.sketch.zip)

**Comment by gdoyle1** [comment]
Thanks @maryshak1996 ! Just merged
