### ISSUE TITLE
borders (dark background) aren't layer styles

### ISSUE THREAD

**Issue by ajacobs21e** [patternfly/patternfly-design-kit#146]
These are on the colors page but aren't layer styles

<img width="244" alt="Screen Shot 2020-01-15 at 8 57 31 PM" src="https://user-images.githubusercontent.com/6415742/72486761-d2a9dd80-37d9-11ea-843f-4674b1ebc9d5.png">

**Comment by gdoyle1** [comment]
@ajacobs21e think we may need to investigate why these are not layer styles/why they aren't used in any of the dark theme buttons?

**Comment by gdoyle1** [comment]
Removed these from the library 🎉
