### ISSUE TITLE
Form text boxes don't scale with content

### ISSUE THREAD

**Issue by cntlsn** [patternfly/patternfly-design-kit#149]
The `Forms > Text box` components of the PF sketch library (Red Hat font) are all represented as a one-line text area. When content in it wraps to a new line, the background layer doesn't automatically resize according to content height.

See example:
<img width="872" alt="Screenshot 2020-01-21 15 48 09" src="https://user-images.githubusercontent.com/2865173/72814509-7295ba00-3c65-11ea-9ff0-876eda351d2f.png">

**Comment by gdoyle1** [comment]
We've changed this symbol so it automatically resizes according to content height! Thanks @cntlsn
