### ISSUE TITLE
Make Expandable text box auto-resize to content height

### ISSUE THREAD

**Issue by cntlsn** [patternfly/patternfly-design-kit#153]
I propose to improve the Expandable text box component design experience by making it auto-resize according to content height. 

Setting component layout to vertical and top-aligned will vertically auto-resize component after submitting content. 
Please see following screenshot (note: first is current behavior, second is desired behavior): 
<img width="453" alt="Screenshot 2020-01-22 18 01 03" src="https://user-images.githubusercontent.com/2865173/72982911-713ccc80-3de0-11ea-8097-af2457484424.png">

**Comment by ajacobs21e** [comment]
Thanks @cntlsn - we have an open story for this already so I'm going to close this one

#151
