### ISSUE TITLE
Define design pattern for drag and drop

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design-kit#154]
Multiple interactions within PatternFly may employ drag and drop. These include, but are not limited to, reordering rows in a list or table, moving cards in a card grid, and reordering columns in a table. We should have a common set of visual affordances to ensure consistency wherever drag and drop is used. Considerations must include:

* Cursor change to indicate that an object is draggable and is in the process of being dragged. 
* Change in appearance of an object as it is being dragged.
* How we visually indicate where an object can be dropped.

see https://github.com/patternfly/patternfly-react/issues/2908#issuecomment-532734997 for more specific question and design requirements from dev

There is some prior work for PatternFly 3 that can be found here: https://www.patternfly.org/v3/pattern-library/forms-and-controls/drag-and-drop/#design

In the process of making these recommendations, we should consider accessibility. Are there ways to make drag and drop interactions accessible to keyboard-only users? Must we always have a redundant method for moving an object when drag and drop is used?

**Comment by mcarrano** [comment]
@gdoyle1 I am adding this issue to the Design Kit backlog for discussion. This is more like a general design pattern rather than a new component so not sure how (or if) it should be reflected in the Sketch Library.

**Comment by jessiehuff** [comment]
From an accessibility standpoint, my research matches what @seanforyou23 found. The article he shared was a good one, and I found another [article](https://medium.com/salesforce-ux/4-major-patterns-for-accessible-drag-and-drop-1d43f64ebf09) also outlining those existing patterns with some specific examples that might help us. It might be worth a discussion about which pattern we should move forward with.

**Comment by gdoyle1** [comment]
For this issue we'll need -- 
Symbol library:
1. Icons
2. Data list/table that is "manageable"
3. Data list/table row that is being dragged (token piece)
https://sketch.cloud/s/0dMw2/a/VAVmd8

Template file:
1. Create a flow that's similar to the mocks that Mary worked on: https://sketch.cloud/s/0dMw2/a/VAVmd8

**Comment by maryshak1996** [comment]
@gdoyle1 I merged the chip symbol and a background overlay (for when a row is hovered over) -- I didn't end up needing any additional appearances so I think that we're good to close here!

**Comment by gdoyle1** [comment]
Great! Thanks @maryshak1996 :)
