### ISSUE TITLE
Show/Hide and Reorder Table Columns

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design-kit#155]
Separate requests have been made to allow for reordering and toggling visibility of columns in a Table. 

https://github.com/patternfly/patternfly-next/issues/2461
https://github.com/patternfly/patternfly-react/issues/2875

Provide design direction for introducing these enhancement. Consider how these features can work together or be used separately. Must work for small or large (>10) numbers of potential columns.

**Comment by gdoyle1** [comment]
Needed for this issue -- 
Symbol library:
1. Compact data list
Sketch file to reference: https://sketch.cloud/s/nW5Jl/a/4pMJqA

Template:
1. Example of the flow presented in this marvel project: https://marvelapp.com/d9e2b11/screen/65255956

**Comment by maryshak1996** [comment]
@gdoyle1 I've put together the modal and have indicated that the drag-drop interaction symbols are coming down the road a bit
[patternfly-template.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/4215578/patternfly-template.sketch.zip)

**Comment by gdoyle1** [comment]
Merged! Thank you!! @maryshak1996
