### ISSUE TITLE
Modal spacing is off

### ISSUE THREAD

**Issue by ajacobs21e** [patternfly/patternfly-design-kit#158]
<img width="855" alt="Screen Shot 2020-01-29 at 7 10 40 PM" src="https://user-images.githubusercontent.com/6415742/73408701-15d07a00-42cb-11ea-90b7-50b556629299.png">
The X icon is 31px from the top and 18px from the right of the modal. According to the spacers it should be 32px and 32px. On the right side though it's going right up to the icon, not to the bounding box.
Should the spacer to the right of the X be a 16px? and 32px in the content area?

**Comment by gdoyle1** [comment]
That's how it's implemented! 
<img width="576" alt="Screen Shot 2020-01-30 at 8 12 32 AM" src="https://user-images.githubusercontent.com/30870144/73452661-4dc1d680-4338-11ea-98ba-e7e6f9caa9c0.png">
<img width="150" alt="Screen Shot 2020-01-30 at 8 12 36 AM" src="https://user-images.githubusercontent.com/30870144/73452662-4f8b9a00-4338-11ea-81dc-3e38d40710be.png">

**Comment by ajacobs21e** [comment]
omg gross why...
Did you check with core that this is what they intended? If not I'm going to ask before I ask PFE to align to this weird standard :)

**Comment by gdoyle1** [comment]
Let me ask and will get back to you @ajacobs21e

**Comment by gdoyle1** [comment]
@ajacobs21e Going to close this since we spoke about the design decisions through Slack!
