### ISSUE TITLE
Add Primary toggle variant of the Dropdown component to sketch library

### ISSUE THREAD

**Issue by cntlsn** [patternfly/patternfly-design-kit#159]
Create new symbol for Primary toggle variant that is in the Dropdowns page

Original issue:
Would it be possible to add the [Primary toggle](https://www.patternfly.org/v4/documentation/react/components/dropdown#primary-toggle) variant of the Dropdown component to the Sketch library?

Thank you!

**Comment by gdoyle1** [comment]
Thanks for filing this! I'll create an issue to add it now

**Comment by gdoyle1** [comment]
@cntlsn here's some contribution guidelines to follow when contributing this!

Follow these steps:

1. Download the library file from here: https://sketch.cloud/s/7do0P
2. Create new symbols using the styles and elements from "Document" **Be sure you take them from "Document" rather than "PatternFly"**
3. When naming a new symbol, follow the naming mechanism within that same category (ex. Forms / 2. Text Box / Success)
4. Make it clear which page in the file you edited and which symbols on the page you added by adding a ⭐️ or some other mark to call them out.
5. Zip your file and attach it to the github issue you were assigned to. Add a list of the symbols you added. And finally, tag @gdoyle1 in your comment.

Thank you!!!!

**Comment by cntlsn** [comment]
Hi @gdoyle1, thank you for sharing the contribution guidelines.

Before moving forward, I wanted to double check about the desired style for the component. On the official [Dropdown component page](https://www.patternfly.org/v4/documentation/react/components/dropdown#primary-toggle), the component looks exactly like a default dropdown toggle with primary action color for the background, inverted text color and no borders.
<img width="158" alt="Screenshot 2020-02-05 15 55 05" src="https://user-images.githubusercontent.com/2865173/73852677-e6bc8a00-482f-11ea-9cad-4d0bad730b56.png">

Whereas in [previous mockups](https://openshift.github.io/openshift-origin-design/designs/administrator/future-openshift/bulk-actions/), the styling looks more like a custom primary button, with rounded corners and different padding.
<img width="126" alt="Screenshot 2020-02-05 15 56 59" src="https://user-images.githubusercontent.com/2865173/73852836-25eadb00-4830-11ea-93e3-609cc2658be8.png">

My gut feeling is that the latter would be more clearly identifiable as an action, but I'm curious to know what others think.

I will attach two more screenshots of the two options in-context:
Dropdown style
<img width="501" alt="Screenshot 2020-02-05 15 44 49" src="https://user-images.githubusercontent.com/2865173/73853023-7b26ec80-4830-11ea-830c-67c2acbfad38.png">

Button style
<img width="508" alt="Screenshot 2020-02-05 15 44 34" src="https://user-images.githubusercontent.com/2865173/73853036-7feba080-4830-11ea-8408-34522fb47ed0.png">

**Comment by gdoyle1** [comment]
Thanks for bringing this up @cntlsn ! To stay consistent with the implementation, in cases like this, we end up adding it to the design kit in whatever way that Core has it - (https://www.patternfly.org/v4/documentation/core/components/dropdown#primary-toggle). So we'd go with the first option you have! It may be worth opening an issue in patternfly-next if you feel that the primary dropdown should be styled differently according to your explanation!

**Comment by cntlsn** [comment]
Hi @gdoyle1, [here](https://github.com/patternfly/patternfly-design-kit/files/4181668/patternfly.sketch.zip) is the updated sketch file featuring the Primary toggle dropdown symbol.

Symbols added:
- [Dropdown / Primary toggle](https://www.patternfly.org/v4/documentation/react/components/dropdown#primary-toggle)

Notes:
- I had to use the `Text / pf-global--Color--light-100` color for the caret icon as no `Icon / pf-icon--Color--light` seems to be available for the sketch library (that's how this is done for the Dark theme components as well)
- the padding for the sketch Dropdown toggle symbol looks off (more space between the text content and the icon) when compared to the react/core symbol
<img width="693" alt="Screenshot 2020-02-10 16 48 16" src="https://user-images.githubusercontent.com/2865173/74165263-2961d600-4c25-11ea-90ce-17cd25a4820d.png">

**Comment by gdoyle1** [comment]
Thanks @cntlsn ! Just merged this 🎉 and thank you for opening another issue for the styling of the primary dropdown. It looks like that has been noted in the past so hopefully it will be fixed soon!
