### ISSUE TITLE
File upload

### ISSUE THREAD

**Issue by ajacobs21e** [patternfly/patternfly-design-kit#161]
Here are some options I played with for a Portal project. I didn't include pasting since that's not a use case for me.
![file upload](https://user-images.githubusercontent.com/6415742/52487552-e392ad80-2b8b-11e9-928f-88ff3fa85f24.png)

The left side shows 3 ideas. I like the concept of making it one regular height input field but it might be too cramped. I imagine with pasting capability it would grow in height after pasting.

The middle one might work best - there's an explicit button for browse, a larger drag and drop target area, and then clicking anywhere that's not the button could be used for pasting. It's a little big though.

The third one copies the PF3 version most but I prefer having a button instead of a link for browse. A button is more appropriate for an action and it's more obvious what to do in this field. 

On the right shows the flow of uploading and then the success message of uploading a file. That takes care of the questions about how to see the file name and how to remove it. 

@mturley and I plan on talking through this more and trying to come up with a single solution for all of these use cases.

_Originally posted by @ajacobs21e in https://github.com/patternfly/patternfly-react/issues/1254#issuecomment-461840247_

**Comment by gdoyle1** [comment]
Create a template with this flow: https://marvelapp.com/de0ggah/screen/65737568.

Sketch file: https://sketch.cloud/s/kROPo

(Don't think additional symbols are needed here but if they are, comment on this!)

**Comment by ajacobs21e** [comment]
@mcoker how will this piece be built in core? I'd like for the sketch file to be built in the same way if possible. If it's B or C, would those new component variations be available to be used in other contexts? @mcarrano 
![Fileupload_how1](https://user-images.githubusercontent.com/6415742/75373991-6cfd4680-5899-11ea-918c-b13d6a9f5ba9.png)

**Comment by gdoyle1** [comment]
@ajacobs21e Now that I'm looking at this - I'm wondering if we should use the existing input field symbols we have to recreate the browse and clear fields (even though these are technically buttons). Also in dropdowns we have split buttons that we could possibly leverage instead?

Symbol library wise we'll definitely need 1 new style for the blue square that is overlaid on the expandable text box once an item is hovered over it!

**Comment by mturley** [comment]
@ajacobs21e the core implementation is already up: https://www.patternfly.org/v4/documentation/core/components/fileupload

I think the line you are referring to is implicitly provided by the border-bottom on the read-only text field (read-only as opposed to disabled, which doesn't have that border) and the buttons with the class `.pf-m-control` which gives them a border-bottom even when disabled.

**Comment by ajacobs21e** [comment]
@gdoyle1 I added symbols for all of the states for an expandable text field (although should we rename this to text area?)
I added a "template" page to Lucia's file. I didn't include every single state in her flow because some should be self explanatory, like the hover state on a field. Can you take a look and let me know if this is what we need please?
[pffileupload.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/4267856/pffileupload.sketch.zip)

**Comment by gdoyle1** [comment]
@ajacobs21e That's a good question - I think I like text area since it captures both inputting text and dropping something within it. Do you want to make that change or should I? And I think what you have in the template example is perfect!

**Comment by ajacobs21e** [comment]
and it matches https://www.patternfly.org/v4/documentation/react/components/textarea !
I can make that change too and then will close this

**Comment by ajacobs21e** [comment]
updated library and template files
