### ISSUE TITLE
Add layer style for white icons

### ISSUE THREAD

**Issue by ajacobs21e** [patternfly/patternfly-design-kit#167]
The icon layer styles we have are
icon-color-dark = #151515
icon-color-light = #6A6E73
-link color = #0066CC

In dark theme we use white icons but there is no layer style for that. we're currently using 
Text / --pf-global--Color--light-100

I propose adding an icon-color-white layer style.

Associated core issue about this problem https://github.com/patternfly/patternfly-next/issues/2687

**Comment by ajacobs21e** [comment]
@gdoyle1 LMK what you think. I can make this update if we agree.

**Comment by gdoyle1** [comment]
I totally agree with you! Let's put this on hold until that issue you created is solved, then we won't confuse anyone adding a new variable for icons since it doesn't exist yet.

**Comment by gdoyle1** [comment]
this is merged
