### ISSUE TITLE
Sketch library update breaks `Link button with icon` component

### ISSUE THREAD

**Issue by cntlsn** [patternfly/patternfly-design-kit#168]
After auto-updating to the latest Sketch library (https://sketch.cloud/s/7do0P), all `Link button with icon` components featuring a `plus-circle` icon changed the icon color to `pf-global--icon--Color--dark` instead of the usual `pf-global--link--Color`:

<img width="620" alt="Screenshot 2020-02-14 12 57 28" src="https://user-images.githubusercontent.com/2865173/74530109-9331f680-4f29-11ea-91ca-0fd6c6500f1c.png">

Other `Link button with icon` components featuring different icons seems unaffected by the update:
<img width="712" alt="Screenshot 2020-02-14 12 57 07" src="https://user-images.githubusercontent.com/2865173/74530108-9200c980-4f29-11ea-807d-bb2d87241558.png">

**Comment by gdoyle1** [comment]
Thank you for filing this! Just merged a new version to fix this. @cntlsn
