### ISSUE TITLE
Add Primary toggle Disabled state symbol

### ISSUE THREAD

**Issue by cntlsn** [patternfly/patternfly-design-kit#169]
Add symbol for Disabled state of Primary toggle.

@gdoyle1 [here](https://github.com/patternfly/patternfly-design-kit/files/4214814/patternfly.sketch.zip) is the zip file.

Symbol added:
- Disabled state of Primary toggle

Notes:
- I have renamed both the Primary toggle `Default` and `Disabled` symbols so that they should live inside a sub-menu now.

**Comment by gdoyle1** [comment]
Thank you! just added this and merged @cntlsn
