### ISSUE TITLE
Master detail

### ISSUE THREAD

**Issue by gdoyle1** [patternfly/patternfly-design-kit#173]
Includes adding symbols for:
1) Active state of card

Templates for:
1) Data list flow
2) Card view/list view flow
3) Data list with bulk select flow
4) In card demo (simple list/data list) flow

Marvel project: https://marvelapp.com/9iefh5b/screen/63567619
Sketch file: @lboehling do you have this available by chance?

**Comment by lboehling** [comment]
here's a link to the sketch file: https://sketch.cloud/s/GxQ9w/v/1K7eoy/

**Comment by gdoyle1** [comment]
Merged
