### ISSUE TITLE
Add compound expansion toggle

### ISSUE THREAD

**Issue by cntlsn** [patternfly/patternfly-design-kit#179]
Create new Sketch symbol for the [Compound expansion toggle](https://www.patternfly.org/v4/documentation/react/components/table#compound-exandable) component, as seen in the Table component's page.

**Comment by cntlsn** [comment]
@gdoyle1 Please find the updated sketch file: [patternfly.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/4268276/patternfly.sketch.zip)

Symbols added:
- Compound expansion toggle / Default
- Compound expansion toggle / Hover
- Compound expansion toggle / Selected

Notes:
- Because of the way the toggle is designed - the blue top border overflows into the above row border by 1px for Hover and Selected state - the artboard for both Hover and Selected state is 1px taller (73px) and needs to be aligned to row bottom for correct placement. Do you think this can be misleading?
- I have named the artboards to support the following path: `Data list + table > 1. Row > 2. Row features > Standard size > Compound expansion toggle > Default / Hover / Selected` -- I'm not too sure whether this would be the desired place for the component in the menu, please feel free to rename it to accommodate best menu placement.
- Is this supported on compact rows? Proposed designs only support standard size rows

**Comment by maryshak1996** [comment]
Closing in favor of #206
