### ISSUE TITLE
Text style mismatches

### ISSUE THREAD

**Issue by ncameronbritt** [patternfly/patternfly-design-kit#180]
I have noticed some differences in the typography styles here https://www.patternfly.org/v4/design-guidelines/styles/typography and in the text styles in sketch

--pf-global--FontSize--lg is 18px on the PF site but 16 in sketch

The PF site also describes the 4th level title as 16 medium weight, so the one that's named large must be misnamed. But the 18px version seems to be missing altogether.

**Comment by ncameronbritt** [comment]
@gdoyle1 @mceledonia Any updates here?

**Comment by gdoyle1** [comment]
Updating this in the sketch library so it matches the typography page! So the --pf-global--FontSize--lg is 18px. So what is found on the typography page is correct

**Comment by ncameronbritt** [comment]
Thanks for looking into it, Gina!

**Comment by gdoyle1** [comment]
Merged this
