### ISSUE TITLE
Reduce use of white-space throught the PatternFly library

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design-kit#182]
In some areas of the system we have too much white space. This mostly is seen in our page layouts but we see it in a couple components as well. Initially we had a goal of aligning to the new brand visual direction which tastefully utilizes large amounts of white space to communicate or symbolize the open nature of our culture and products. While this works well in a marketing context, taking it too far in a product context hinders our products by seeming to waste space for no reason in an industry that really cares about information density. To put it bluntly, our users don’t make the brand connection and generally respond negatively to the additional white space.

cc: @mceledonia @LHinson

**Comment by gdoyle1** [comment]
Merged into library - creating a follow-up issue to address all changes that need to be made in the template file
