### ISSUE TITLE
Banner

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design-kit#183]
Introduce a general banner component that can be used in a variety of use cases:

* To indicate that the application is offline (see patternfly/patternfly-next#1879)
* To indicate an experimental feature 
* To indicate classification level
* others?

Color and a one line message may be used to convey status. Placement and height should be considered. Are there different placement options?

Related work includes: 

* Classification Banner for PF3: https://www.patternfly.org/v3/pattern-library/communication/classification-banner

* Disconnected/offline pattern proposal from @katierik : https://docs.google.com/document/d/13OoJdZA_L8xfg6sKxNOj2RgmJIXEYGPOaq67nTnZRGA/edit?usp=sharing

**Comment by maryshak1996** [comment]
@gdoyle1 here's the symbols for this! 
[banner-symbols.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/4370474/banner-symbols.sketch.zip)
Do you think that we need as template for this?

**Comment by gdoyle1** [comment]
@maryshak1996 Thank you! Just merged.

Re: template - Yes I think having a template of this would be helpful - the two that you presented in the google doc above would be great additions. I'm going to close this issue out for now and create a new one for a template of the banner for the next sprint!
