### ISSUE TITLE
Horizontal and vertical divider 

### ISSUE THREAD

**Issue by gdoyle1** [patternfly/patternfly-design-kit#185]
Add symbols for horizontal and vertical dividers.

Reference the implementation for spacing/usage: https://www.patternfly.org/v4/documentation/core/components/divider

**Comment by gdoyle1** [comment]
check to see if #d2d2d2 works on both light and #f0f0f0
dark theme use what is in dark nav

**Comment by ajacobs21e** [comment]
I've been using secondary color on dark theme in the pf web library

**Comment by gdoyle1** [comment]
Added a divider for light background with bordercolor-100 (#d2d2d2) but want to check with the team tomorrow to see what needs to be added for dark since we have two different ones for the dark nav. Going to merge the light ones and then update this issue after the meeting

**Comment by gdoyle1** [comment]
Merged this
