### ISSUE TITLE
Template: Change in-page form examples

### ISSUE THREAD

**Issue by mmenestr** [patternfly/patternfly-design-kit#189]
We're adding a new guideline in the form guidelines where forms in a page don't show up on the grey page background anymore on top of a white card, but instead, the whole page remains white and the form just goes on top of the white background.

**Task**: Make that change in the template library to reflect what the guidelines say!

Here is a visual for clarity:
![image](https://user-images.githubusercontent.com/51165119/78293047-fc7bc200-74f5-11ea-9204-da180d75df39.png)

**Comment by gdoyle1** [comment]
@mmenestr thanks for filing this! I'll move it to our backlog :)

**Comment by mmenestr** [comment]
Closing because this has been done.
