### ISSUE TITLE
Need to add toast notifications

### ISSUE THREAD

**Issue by cshinn** [patternfly/patternfly-design-kit#19]
Designs available here
http://www.patternfly.org/pattern-library/communication/toast-notifications/

**Comment by ajacobs21e** [comment]
[PatternFly 3 - Toast.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/2155565/PatternFly.3.-.Toast.sketch.zip)
@cshinn can you check this, please?

**Comment by cshinn** [comment]
This was fixed in #20
