### ISSUE TITLE
Template: Banner

### ISSUE THREAD

**Issue by gdoyle1** [patternfly/patternfly-design-kit#190]
Using the banner symbols, create a full page example of how they'd be used.

Reference this google doc: https://docs.google.com/document/d/1QZY9EcblZaIGFB6KHqeDtqWPHqxsJn5-VGJnowmrVT8/edit?usp=sharing

**Comment by mceledonia** [comment]
@gdoyle1 Here's the banner template page:
[patternfly-template-banner.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/5058347/patternfly-template-banner.sketch.zip)

**Comment by gdoyle1** [comment]
Merged! Thanks @mceledonia
