### ISSUE TITLE
Reduce or eliminate the use of drop shadows across the component library

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design-kit#191]
Similar to white space, we started to use drop shadows a bit too much looking back. Unlike white space, this actually doesn’t align at all with brand/marketing and is an area where we can both align and improve our general visual look and feel. Over-reliance on drop shadows can lead to things feeling a bit messy or outdated.

cc @mceledonia @LHinson

**Comment by gdoyle1** [comment]
Merged

**Comment by gdoyle1** [comment]
Merged this in the library! Closing
