### ISSUE TITLE
Compact pagination on mobile phone is not usable

### ISSUE THREAD

**Issue by rvsia** [patternfly/patternfly-design-kit#192]
**Describe the issue. What is the expected and unexpected behavior?**

When using compact pagination on smaller screen, it's not usable.

![compactpag](https://user-images.githubusercontent.com/32869456/73941134-f948c900-48ec-11ea-9261-cf0ba16e4e47.gif)

Expected:

An ability to switch pages.

**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**

1. Set compact navigation
2. Decrease size of your browser's window
3. Try to change the page

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**

A bug. It's not blocking us.

**What is your product and what release version are you targeting?**

Sources UI ASAP.
It affects all other Insights applications that are using the compact pagination.

cc @Hyperkid123 @karelhala

**Comment by ajacobs21e** [comment]
Can we consider changing the name of the sketch components for pagination? They're under Toolbar. Do we plan to add more things to the Toolbar category? If not, renaming the group to "Pagination" makes more sense to me.

**Comment by gdoyle1** [comment]
@ajacobs21e Definitely something to consider! Can pagination be added into a data view without a toolbar? If not, then I think it needs to stay as is.

**Comment by gdoyle1** [comment]
delete the options menu without a caret , update the template file

**Comment by mcarrano** [comment]
Here are the mockups in Sketch: https://sketch.cloud/s/DZyej

**Comment by mcarrano** [comment]
@gdoyle1 I just placed the 'on hold' label on this one as I just came out of a meeting with @mcoker and Matt Nolting where we redesigned how this will work (on mobile). I will update this once we merge a PR with the final implementation.

**Comment by ajacobs21e** [comment]
When this gets reopened, can the options menu and the text box of the full pagination component be updated to be responsive to text input size please?

**Comment by gdoyle1** [comment]
Use this as a reference for symbol library/template https://github.com/patternfly/patternfly/issues/3021

**Comment by gdoyle1** [comment]
Hey @ajacobs21e ! You good to take this on this sprint?

**Comment by ajacobs21e** [comment]
[Mobile.Pagination.zip](https://github.com/patternfly/patternfly-design-kit/files/4968099/Mobile.Pagination.zip)
I'm the wooorst :( 
Thanks Gina!

**Comment by ajacobs21e** [comment]
[Mobile.Pagination.zip](https://github.com/patternfly/patternfly-design-kit/files/4968132/Mobile.Pagination.zip)
I'm the worst! I created Mobile / Pagination and also updated Pagination / Full and Pagination / Options menu to be horizontally responsive. 
Thanks Gina!

**Comment by gdoyle1** [comment]
Thanks @ajacobs21e !! Merged this
