### ISSUE TITLE
Clarify styling and usage for Labels

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design-kit#193]
There is a lot of confusion about when to use Labels, Chips, and Badges as they seem to have similar characteristics, but none of these may provide everything PF users need to support complex use cases like tagging, for example. This is compounded by confusion of Labels and Buttons that look alike visually but serve different purposes.

Want to...
* Have a set of components that are visually differentiated and flexible.
* Clarify usage.
* Revise labels to include color coding, icons, make closable.

**Comment by maryshak1996** [comment]
@gdoyle1 this library contribution should be ready to merge in :) 
[labels-libarary-contribution.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/4458337/labels-libarary-contribution.sketch.zip)
----
One this is merged, do you want me to go through the template and replace instances of the old labels with these new labels?

**Comment by gdoyle1** [comment]
One question before I merge: Do we want to disable the option to change the color of the icon within the label? I'm still seeing it @maryshak1996 
<img width="232" alt="Screen Shot 2020-04-13 at 8 46 32 AM" src="https://user-images.githubusercontent.com/30870144/79121536-86802200-7d63-11ea-89b3-9624f94d4f37.png">

And yes that'd be great! I'm tracking all the updates needed for the template here: #198 - I'm going to make the larger page spacing updates first then maybe we can work together on those updates?

**Comment by gdoyle1** [comment]
Answers to above - we decided to stick with the format it is in since the dynamic icon makes the most sense in that symbol and in order for the icon to retain the same color even when the icon type changes, that color will show (but is unchangeable). The close icon will change color on hover so we'll leave that too. Will merge EOD

**Comment by maryshak1996** [comment]
@gdoyle1 ya I can definitely help make those updates to the template whenever you're ready :)

**Comment by gdoyle1** [comment]
Will close this out and just add an issue to track your table stuff + adding labels to full page example! @maryshak1996
