### ISSUE TITLE
Template: Manage columns with different modal

### ISSUE THREAD

**Issue by gdoyle1** [patternfly/patternfly-design-kit#196]
We have an example of a modal in the manage column template now that includes dragging but we want another example with a modal of the items with just checkboxes (shown here: https://www.patternfly.org/v4/documentation/core/demos/table/column-management-modal)

Also update the secondary "cancel" button in the modal to a link button

**Comment by maryshak1996** [comment]
[column-management-demo.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/4451681/column-management-demo.sketch.zip)
No library updates needed -- here's the updated template!

**Comment by maryshak1996** [comment]
Just merged this in @gdoyle1
