### ISSUE TITLE
Template fixes after last symbol library update

### ISSUE THREAD

**Issue by gdoyle1** [patternfly/patternfly-design-kit#198]
- [x] Accordion (Gina)
- [x] Application launcher page spacing (Gina)
- [x] Application launcher table replacement (Gina - wait for Mary to complete table/list updates)
- [x] Card view card examples and page spacing (Gina)
- [x] Column management modal and page spacing (Mary)
- [x] Data list page spacing, column headers alignment, mobile examples spacing (Mary)
- [x] Empty state page spacing (Margot)
- [x] Form page spacing (Margot)
- [x] Default hint page spacing and column headers alignment (Margot)
- [x] Inline alerts page spacing (Margot)
- [x] Master default page spacing and column headers alignment (Margot)
- [x] Navigation page spacing (Gina)
- [x] Page page spacing (Margot)
- [x] Popovers #208 
- [x] Table column headers, page spacing, mobile examples spacing (Mary) #212 
- [x] Toast alert page spacing (Margot)
- [x] Toolbar top and bottom sizes, mobile toolbar spacing #209 
- [x] Wizard page spacing (Margot)
- [x] Wizard mobile spacing 
- [x] Modal spacing (Mary)

**Comment by gdoyle1** [comment]
Uploaded new version of the template with updated Accordion, Application launcher (without tables), Navigation pages!

**Comment by maryshak1996** [comment]
@gdoyle1 this file here has the template updates for:

1. Data list (all desktop + mobile views)
2. Column mangement
3. Modals
[breaking-changes-template-4-20.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/4506013/breaking-changes-template-4-20.sketch.zip)

**Comment by mmenestr** [comment]
@gdoyle1 @maryshak1996 Updated template file with these updates:
- Empty state spacing
- form page spacing
- Default hint page spacing and column headers alignment
- Inline alerts page spacing
- Master default page spacing and column headers alignment
- page page spacing
- toast alert page spacing
- wizard desktop page spacing

**Comment by maryshak1996** [comment]
@gdoyle1 here's all of the table edits!
[breaking-changes-template-4-29-20.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/4554476/breaking-changes-template-4-29-20.sketch.zip)

**Comment by gdoyle1** [comment]
Thanks @maryshak1996 !

**Comment by gdoyle1** [comment]
this is merged so closing this
