### ISSUE TITLE
Add new color variables (new notifications)

### ISSUE THREAD

**Issue by gdoyle1** [patternfly/patternfly-design-kit#199]
Existing palette colors that need to be updated: 
- [x] --pf-global--palette--blue-50 = #e7f1fa

New palette colors that need to be added: 
- [x] --pf-global--palette--cyan-50 = #f2f9f9 
- [x] --pf-global--palette--gold-50 = #fdf7e7
- [x] --pf-global--palette--green-50 = #f3faf2
- [x] --pf-global--palette--red-50 = #faeae8

#12

**Comment by maryshak1996** [comment]
merged!
