### ISSUE TITLE
Update blue icon in grey labels to be black

### ISSUE THREAD

**Issue by maryshak1996** [patternfly/patternfly-design-kit#202]
Really small update to make the blue icon in the grey labels be black (conversation: https://github.com/patternfly/patternfly/pull/2943#issuecomment-613469548)

Before
![image](https://user-images.githubusercontent.com/19824574/79235346-7aff2a80-7e39-11ea-8b8c-4d5cd38ad960.png)
After
![image](https://user-images.githubusercontent.com/19824574/79235361-7fc3de80-7e39-11ea-96da-5e53490e36c0.png)

**Comment by gdoyle1** [comment]
Merged!
