### ISSUE TITLE
Link button with icon preview does not match symbol on the canvas

### ISSUE THREAD

**Issue by jknilans** [patternfly/patternfly-design-kit#203]
This may be a Sketch problem versus a symbol library problem, but I noticed that the icon in the  `link button with left icon` component doesn't match the link color. However, the preview for the button in the inspector displays the icon color as link blue. See screenshot below:   

<img width="654" alt="Screen Shot 2020-04-14 at 3 42 15 PM" src="https://user-images.githubusercontent.com/25486044/79268390-b49b5a00-7e68-11ea-8c6c-0e4d231fe98a.png">

The only way I could change the icon color is by detaching it from the library.

**Comment by gdoyle1** [comment]
Turning on the color override for the time-being since others have also mentioned this! Will also file a bug with Sketch for it. Merged, so closing this
