### ISSUE TITLE
Add 80px spacer

### ISSUE THREAD

**Issue by ajacobs21e** [patternfly/patternfly-design-kit#205]
Splitting off the request from the general whitespace story to add an 80px spacer.

This spacer is needed to support the roomy style used on marketing web sites, especially Red Hat Ecosystem and redhat.com. 

Original comment:
@LHinson and I talked today about expanding the scope of this story to look at whitespace in general, including looking at areas where we may need to increase the whitespace. Some web designers have a need for an 80px spacers added to our system. 

_Originally posted by @ajacobs21e in https://github.com/patternfly/patternfly-design/issues/799#issuecomment-577751824_

**Comment by gdoyle1** [comment]
Will we be using  pf-global--spacer--4xl as the variable for the 80px spacer?

**Comment by mcoker** [comment]
@gdoyle1 yep! Is there a color we'll use for this spacer in sketch designs?

**Comment by gdoyle1** [comment]
@mcoker Yes! We're using #B300B3 as the fill and #8F008F as the 1px border

**Comment by gdoyle1** [comment]
Merged in the kit - closing this!
