### ISSUE TITLE
Symbol lib: Compound expandable table

### ISSUE THREAD

**Issue by mmenestr** [patternfly/patternfly-design-kit#206]
Add a compound expandable table to the template library!
https://www.patternfly.org/v4/documentation/react/components/table#compound-exandable

**Comment by mmenestr** [comment]
https://github.com/patternfly/patternfly-design-kit/issues/179

**Comment by doruskova** [comment]
@gdoyle1 @mmenestr I'm adding my sketch zip file with a Compound expandable table. It also includes the toggle symbol for selected, hover, and expandable state. 
[Compound-table-template-symbol.zip](https://github.com/patternfly/patternfly-design-kit/files/4728760/Compound-table-template-symbol.zip)

Here's the preview: 
![Compound expandable - desktop](https://user-images.githubusercontent.com/32618096/83736379-d8517400-a651-11ea-9b54-2759f29fb186.png)

**Comment by maryshak1996** [comment]
Here's the symbols for tracking, but they have been merged in :) 
[patternfly-compoundexpansion-addition.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/4866124/patternfly-compoundexpansion-addition.sketch.zip)

**Comment by maryshak1996** [comment]
I haven't merged the template in, but here is the file for it!
[template-with-compoundexpoansion.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/4866194/template-with-compoundexpoansion.sketch.zip)

**Comment by gdoyle1** [comment]
Just merged this! Thank you @maryshak1996 !!
