### ISSUE TITLE
Naming incorrect on Lg table symbols

### ISSUE THREAD

**Issue by maryshak1996** [patternfly/patternfly-design-kit#207]
The symbols for the Lg table spacing are labeled as being 16px, but are really 24px. 24px is the correct sizing for lg --> so we just need to update the naming. 
<img width="968" alt="Screen Shot 2020-04-21 at 4 57 57 PM" src="https://user-images.githubusercontent.com/19824574/79990694-59c4bc80-847f-11ea-8ecc-228a035b2eb6.png">

**Comment by gdoyle1** [comment]
Fixed this! Thanks for filing @maryshak1996 

Closing bc merged
