### ISSUE TITLE
Popover page template update

### ISSUE THREAD

**Issue by gdoyle1** [patternfly/patternfly-design-kit#208]
Popover page needs to be updated to reflect the newest spacing changes (32px to 16px around the popover and 16px to 8px between text and the close button).

We'll add an example of the popover with header to the first artboard too. Also need to show a new example of the "detached" version of the popover by pulling in the new popover symbol and detaching.

Specifics of what was changed in popover symbol:
<img width="902" alt="Screen Shot 2020-04-23 at 9 19 15 AM" src="https://user-images.githubusercontent.com/30870144/80106851-6234fa00-8548-11ea-9692-a92cc8f6ec62.png">

**Comment by sunilmalagi** [comment]
Here is the PF template file with Popover page spacing changes.  
[patternfly-template_sunil.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/4545814/patternfly-template_sunil.sketch.zip)

 Please let me know for any changes required.

**Comment by gdoyle1** [comment]
Awesome, thanks @sunilmalagi ! Merged this so will close it
