### ISSUE TITLE
Action Button in Toolbar should grow with content

### ISSUE THREAD

**Issue by lizsurette** [patternfly/patternfly-design-kit#21]
I noticed that updating the Label for an action button in the toolbar doesn't seem to have the button grow with the text.
<img width="1127" alt="screen shot 2018-08-14 at 7 52 09 pm" src="https://user-images.githubusercontent.com/208455/44409585-a6c8f080-a530-11e8-85c5-efd1534a810d.png">

**Comment by cshinn** [comment]
@lizsurette yeah, unfortunately that's just not something that Sketch supports right now. if you edit the toolbar symbol itself, you can resize the button and it will update for all your pages.

**Comment by kybaker** [comment]
@lizsurette Buttons do not grow with the text. They must be resized manually. You can can turn on the padding variable to make sure the left/right spacing is correct. It is possible to have this functionality with 3rd party software which we decided to avoid for PF3.

**Comment by lizsurette** [comment]
Okay cool, thanks for the extra info. I will close this.
