### ISSUE TITLE
Vertical tabs

### ISSUE THREAD

**Issue by gdoyle1** [patternfly/patternfly-design-kit#215]
Add vertical tabs into the symbol library into 'Tabs' section

**Comment by gdoyle1** [comment]
Hey @ajacobs21e ! You good to take this on this sprint?

**Comment by ajacobs21e** [comment]
[VerticalTabs.zip](https://github.com/patternfly/patternfly-design-kit/files/4968203/VerticalTabs.zip)
@gdoyle1 these seemed to copy over and keep the PF layer styles. Can you check if it works please?
I also did my best guess for naming, if you had something else in mind LMK!

**Comment by gdoyle1** [comment]
Looks like it worked! Thanks @ajacobs21e merging this
