### ISSUE TITLE
Notification Badge Visual / Functional Enhancements

### ISSUE THREAD

**Issue by jcaianirh** [patternfly/patternfly-design-kit#217]
The following openshift design story would be nice to have in patternfly. Is this something that would be considered for patternfly core?

https://issues.redhat.com/browse/PD-323

Image below:
![image](https://user-images.githubusercontent.com/35978579/73221048-ea645880-412d-11ea-9a50-6d1bc127623e.png)

**Comment by gdoyle1** [comment]
Reference this PR when adding symbols! https://patternfly-pr-3231.surge.sh/documentation/core/components/notificationbadge

**Comment by mceledonia** [comment]
Added + updated to latest design:
[patternfly-notificationbadge2020.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/4955728/patternfly-notificationbadge2020.sketch.zip)

**Comment by gdoyle1** [comment]
Merged this so closing! Thanks @mceledonia
