### ISSUE TITLE
Dropdown with description needed

### ISSUE THREAD

**Issue by yih-wang** [patternfly/patternfly-design-kit#218]
We need a dropdown with description in it in AMQ. So users can have some help information about the options. I created an initial wireframe like this.
<img width="343" alt="Screen Shot 2019-05-17 at 15 47 52" src="https://user-images.githubusercontent.com/23331885/57911749-29fa5580-78bb-11e9-93c7-e88043008b11.png">

**Comment by mmenestr** [comment]
Finished adding the new symbols to the design kit, so closing the issue.

**Symbols added:**
Dropdowns / 3. Menu Item / With description / Default
Dropdowns / 3. Menu Item / With description / Hover
Dropdowns / 3. Menu Item / With description / Disabled
Dropdowns / 3. Menu Item / With description / Single select
