### ISSUE TITLE
Selectable tile component

### ISSUE THREAD

**Issue by katierik** [patternfly/patternfly-design-kit#220]
There is a need for a "selectable tile" that can be used in forms and other interactive areas 
![Xnip2019-09-26_13-05-32](https://user-images.githubusercontent.com/23172038/65709300-7e2df700-e05e-11e9-83cf-fbdff77b8fbd.jpg)

The most prominent use case seems to be using this as a radio-like selector. 

Collected use cases & proposed design: https://docs.google.com/document/d/1J6BAbhhPx7KPmgt9W7bujMXvIUnDxBur9ypZJTmbOns/edit?usp=sharing

**Comment by maryshak1996** [comment]
@gdoyle1 I think that this bad boy should be ready to merge :) 
[design-kit-tiles.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/4984446/design-kit-tiles.sketch.zip)

**Comment by gdoyle1** [comment]
Thank you @maryshak1996 !! Merged this
