### ISSUE TITLE
Change styling of expansion visuals in Table and Data list

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design-kit#222]
In the course of re-evaluating need for card backgrounds in various full page views we realized that the current approach to reflecting expansion in tables and lists does not work well when we do not include a card background to create padding between the table/list and the edge of the container. See patternfly/patternfly-design#798 for more details.

Want to reconsider the visual approach for showing expansion in these components to mitigate that problem.

**Comment by mcarrano** [comment]
Have opened a core issue here to implement these changes: https://github.com/patternfly/patternfly/issues/3124

**Comment by lboehling** [comment]
Here are the full-page demo mocks w/ new expansion styling too: https://marvelapp.com/5996ff7/screen/69836554

**Comment by gdoyle1** [comment]
@mmenestr here's the issue we were discussing!

I've made the changes to the symbol library but need to update the template file

**Comment by gdoyle1** [comment]
Merged!

**Comment by mcarrano** [comment]
@gdoyle1 I hate to do this, but can we revert this back? We've encountered some problems implementing https://github.com/patternfly/patternfly/issues/3124 and after discussing with @mceledonia we decided we are better off not making the change. Sorry about that!

**Comment by gdoyle1** [comment]
@mcarrano Ah, yeah we can! I'll add it back into the backlog

**Comment by gdoyle1** [comment]
Closing this since the reverted changes have been made and applied to the template file!
