### ISSUE TITLE
New filled labels have different visual weights

### ISSUE THREAD

**Issue by katierik** [patternfly/patternfly-design-kit#225]
I'm looking to use the new filled label designs in my application, and found that they have very different visual weights.

![image](https://user-images.githubusercontent.com/23172038/82942996-e115bc00-9f66-11ea-9d40-1530d6603bc9.png)

On the right are the labels in blue, cyan, and purple. On the left are the other colors (grey, green, orange, red). 
Green and Purple have significantly more visual weight than the others, which makes it difficult to combine them with the other labels.

**Comment by jeperry** [comment]
Thanks, this is great.

**Comment by KendraMar** [comment]
Thank you for following up on this, Matt!

**Comment by maryshak1996** [comment]
Action items for symbol library
- [ ] Add purple-050 to symbol appearances and colors
- [ ] Update green label to use green-050
- [ ] Update purple label to use purple-050

**Comment by maryshak1996** [comment]
Changes merged into the library :)
