### ISSUE TITLE
Blue label text color does not match colors in PF website

### ISSUE THREAD

**Issue by mmenestr** [patternfly/patternfly-design-kit#227]
The blue label text color in PF is #004368,  but that is not a HEX value in the blue family colors shown [here](https://v4.patternfly.org/v4/design-guidelines/styles/colors). I'm guessing it's actually supposed to be the blue-500 whose hex value is #004080, but not sure - just wanted to record the inconsistency!

![image](https://user-images.githubusercontent.com/51165119/83459879-28062480-a433-11ea-915a-3bfb801b0a11.png)

**Comment by maryshak1996** [comment]
I inspected the [most recent PR on the labels](https://patternfly-pr-3138.surge.sh/documentation/core/components/label#) and the text uses blue-600, so I updated that for the labels here and merged
