### ISSUE TITLE
Add context menu capability to dropdown menu items

### ISSUE THREAD

**Issue by gdoyle1** [patternfly/patternfly-design-kit#228]
Like the application launcher, we want the ability to add an icon to the left of text and arrow-right to the right of text to get a fly-out menu for that menu item. We'll add that to the symbol. Also need to create a template of this.

Here's the marvel: https://marvelapp.com/dhj94fe/screen/67940185 (designed by Marie)

PF issue: 774

**Comment by mmenestr** [comment]
**Note to self:** Still need to create a template adition

**Comment by mmenestr** [comment]
Synced template with the following:

![image](https://user-images.githubusercontent.com/51165119/86955950-5fe54380-c126-11ea-8496-3a3776d9e4f9.png)

![image](https://user-images.githubusercontent.com/51165119/86955976-65428e00-c126-11ea-8e4f-0438b69e1ecb.png)

Also added an extra symbol for the selected version to the symbol library.
