### ISSUE TITLE
Adding non-link text to dropdown

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly-design-kit#229]
## Requesting new features, enhancements, or design changes to PatternFly 
- Describe the use cases and requirements of the new feature or enhancement you are requesting.

Adding non-link text to dropdown component. CodePen: https://codepen.io/mcoker/pen/rNagKWQ

Mockup:
![gq7f0K1fTJLI4dEP1mO9KO_GjrFyfnxfP5R9TOKmENo6dwJsopeLpiKFj6eOy91c1tIWHTXJ6w_bVf3pjmMnPeEbizV9swM7IOCc1Jp9vOYG6f3PajujiMDyWQ7UA_co6eRvWPpg](https://user-images.githubusercontent.com/40275806/73467564-7e623a00-4351-11ea-832d-e3b21c520cb3.png)

- Explain *why* this feature is needed and/or why these requirements can
not be met using existing components.

It may be needed as an enhancement to dropdown because it will have to be customized on the OpenShift side.

- If this is for specific applications, list them here along with any dates that you need this for.

It's needed for the OpenShift console 4.5. Confirming with @beanh66 this is correct. 

- Link any detailed design documents, rough sketches, wireframes or workflows.

- State whether this is a new feature or an enhancement on an existing pattern by labeling it accordingly

New enhancement - Dropdown

- If this is an enhancement to an existing feature, identify the feature that you want to modify.

Adding text that is not a link to the dropdown.

We don’t currently support an element in the dropdown that just has text in it, so they will need to make CSS overrides (https://codepen.io/mcoker/pen/rNagKWQ). And that as we make changes to the dropdown, our changes may break their overrides and would require updates.

cc @beanh66 @rhamilto @mcarrano @mceledonia @maryshak1996 @mcoker

**Comment by gdoyle1** [comment]
Create a template for this since these pieces already exist in the library

**Comment by gdoyle1** [comment]
@asumihasan 
In the "Menus" page of the [template file](https://www.sketch.com/s/729c2eee-e8b6-4fcd-8a79-f6faa8c30f89), we want to add an example of the user menu with gray text as the first menu item.

1. Download template file
2. Use symbols from PatternFly library to recreate the menu shown here:
![image](https://user-images.githubusercontent.com/30870144/86171399-a6192200-baea-11ea-87e2-1e1966787870.png)
(This has already been [implemented in React](https://patternfly-react-v4.surge.sh/documentation/react/components/dropdown#dropdown-with-image-and-text) as well if you want to see it live)
  - You should be able to use existing text styles to recreate the gray text
  - You'll want to include a spec of it (showing padding) as well as an example in context (in full page)
3. Once you're done, upload as a .zip file to this issue and tag me! 😃

**Comment by asumihasan** [comment]
[patternfly-template.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/4859695/patternfly-template.sketch.zip)
@gdoyle1

**Comment by gdoyle1** [comment]
Merged! Thanks so much @asumihasan !!
