### ISSUE TITLE
Text not pinned to correct spot in large text fields

### ISSUE THREAD

**Issue by katierik** [patternfly/patternfly-design-kit#23]
![xnip2018-11-20_16-42-49](https://user-images.githubusercontent.com/23172038/48804728-6cafec00-ece3-11e8-8dba-97e72d98ff3b.jpg)

Needs to be pinned to top edge (most likely?)

**Comment by ajacobs21e** [comment]
[large field.zip](https://github.com/patternfly/patternfly-design-kit/files/2601748/large.field.zip)
fixed - here's a file with just that symbol

**Comment by mcarrano** [comment]
@cshinn are you able to integrate this fix?

**Comment by cshinn** [comment]
@mcarrano yeah! Sketch52 made some mischief with a number of the symbols' scaling, so I suspect we'll have to correct a few things like this

**Comment by cshinn** [comment]
@katierik Looks like the main reason that this wasn't behaving nicely is that the `large text field` widget is intended to be a single line <input> box (large for things like big search bars). I added a new `text area` widget that should fulfill your requirements, however.
