### ISSUE TITLE
Add symbols and template for Search input

### ISSUE THREAD

**Issue by gdoyle1** [patternfly/patternfly-design-kit#230]
New search input designs will have to include new input fields for:
1. Field with icon on left
2. Field with badge
3. Field with up / down arrows
4. Field with clear button

Marvel link to reference: https://marvelapp.com/e9ge7g7

Need to create template for this too

**Comment by maryshak1996** [comment]
Here's the sketch file! https://www.sketch.com/s/10959c66-4198-42c3-b0cd-ca79d19d21a6

**Comment by gdoyle1** [comment]
Use this for reference: https://patternfly-pr-3264.surge.sh/documentation/core/components/searchinput

**Comment by gdoyle1** [comment]
Done and merged
