### ISSUE TITLE
Tabs symbols are too "tall"

### ISSUE THREAD

**Issue by mmenestr** [patternfly/patternfly-design-kit#231]
When you inspect the tabs in the demos, their height is 40px https://www.patternfly.org/v4/documentation/react/components/tabs/default
but in the sketch library, their height is 56?

**Comment by ajacobs21e** [comment]
https://www.sketch.com/s/f6a52c25-8657-4680-9d3e-4c09131e6ed0/a/3AvL8j They should have 16px spacers all the way around. It looks like the demo is using buttons.

**Comment by mmenestr** [comment]
Hmm ok so are you saying the demo is wrong and what's in the sketch symbol is how it _should_ be?

**Comment by ajacobs21e** [comment]
Yeah. This is what I reviewed with @mattnolting: https://patternfly-next-pr-2757.surge.sh/documentation/core/components/tabs
It has 16px spacers.

**Comment by mmenestr** [comment]
Kk and then just from a usage perspective, would you still have a 24px spacing between tabs and whatever is above it? Like this- 
![image](https://user-images.githubusercontent.com/51165119/84189094-ab8ec980-aa62-11ea-88ae-8bf18c1d61ae.png)

**Comment by ajacobs21e** [comment]
In general yes, but I think we didn't build that into the component in case there are other uses for the tabs, like putting them in a card etc.

**Comment by mmenestr** [comment]
Yeah, wouldn't expect it to be built in! I just worry about all the extra space this takes up compared to the old default tab styling. Especially since there's no box around it, it just looks like a lot of white space on top of the text.

**Comment by gdoyle1** [comment]
@ajacobs21e @mmenestr going to close this since it follows the Core implementation! If there are future design updates then we can update the symbols once those changes are made.

@mmenestr It may be best to create a follow up design story in the design repo!

**Comment by ajacobs21e** [comment]
@gdoyle1 do you mean Core uses the 8px spacers above & below?

**Comment by gdoyle1** [comment]
@ajacobs21e No, core uses what is in the symbol library now for tabs (16px) - I meant I'm closing since the library matches Core right now

**Comment by ajacobs21e** [comment]
whew ok - does this mean we need to open an issue with react about the demo?

**Comment by mmenestr** [comment]
Allie you don't need to do anything! 

**For clarification:** my initial thought in filing this issue was that there was an error in the lib because it didn't match core. But, now that you clarified that it's right and there is no error, I am just wondering whether we should tweak the new tabs a bit to use less white space, to go along with the whole PF effort of reducing white space. Made this issue for that: https://github.com/patternfly/patternfly-design/issues/883
