### ISSUE TITLE
Tweak Labeled Field's help text to wrap

### ISSUE THREAD

**Issue by andybraren** [patternfly/patternfly-design-kit#234]
Setting the `Alignment` of the help text below a Labeled Field symbol to `Auto Height` rather than `Fixed Size` would allow text to wrap like it does in the implementation. At the moment, longer text strings disappear like this:

![image](https://user-images.githubusercontent.com/9122899/85350363-f7b02400-b4ce-11ea-8217-c3ca838c5a74.png)

**Comment by gdoyle1** [comment]
I can't find where the wrapping is here? https://www.patternfly.org/v4/documentation/core/components/form @andybraren

**Comment by gdoyle1** [comment]
Ah wait I think I did it with inspect
<img width="499" alt="Screen Shot 2020-06-23 at 10 34 33 AM" src="https://user-images.githubusercontent.com/30870144/85417057-31b80f00-b53d-11ea-843c-97fe928e432f.png">

**Comment by andybraren** [comment]
Thank you Gina! I'll try to go through the [contributing process](https://github.com/patternfly/patternfly-design-kit#contributing-a-new-or-edited-symbol) next time. 👍

**Comment by gdoyle1** [comment]
Something that is this quick is fine through comments! If you ever wanted to contribute with larger fixes or additions, you're welcome to download the library file and try it yourself though! @andybraren

**Comment by gdoyle1** [comment]
Fixed! And merged, so going to close this
