### ISSUE TITLE
Symbol update: Notification Drawer

### ISSUE THREAD

**Issue by gdoyle1** [patternfly/patternfly-design-kit#235]
The notification drawer symbols were created before the design had been implemented. Since then, there have been some changes with styles and spacing. 

This issue is to:
1. Download the library Sketch file here: https://www.sketch.com/s/2cf1063b-5283-4e0b-b8a6-cbb1ac07e29e
2. Use inspect on this demo https://www.patternfly.org/v4/documentation/core/components/notificationdrawer to figure out the specifics about colors, fonts, spacing and more.
3. Compare that to the current notification drawer symbols and make any updates necessary
4. Attach the Sketch file that you have edited to this issue (you must attach it as a .zip file)

**Comment by LPutney** [comment]
@gdoyle1 Would you mind checking what I've done so far to see if it needs any tweaking before I do the rest? I've attached the file I was working on, and I added a screenshot with the padding showing for the 6 things I've updated so far 
<img width="940" alt="Screen Shot 2020-07-02 at 1 18 20 PM" src="https://user-images.githubusercontent.com/66384335/86390896-dede0600-bc66-11ea-92c0-0d238b9d3423.png">
[patternfly.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/4865773/patternfly.sketch.zip)

**Comment by gdoyle1** [comment]
@LPutney Just took a look at what you've done so far and it looks great! When you continue to update, remember to pin any of the new items you bring in so that when you resize them, they are responsive! You can do that pretty easily by pulling the "document" symbol into the file and stretching it / changing the content.

**Comment by LPutney** [comment]
@gdoyle1 thanks for your help! I've attached an updated zip file with the rest updated and added pinning where it was missing. Let me know if I need to update anything else.
[patternfly.sketch 2.zip](https://github.com/patternfly/patternfly-design-kit/files/4886292/patternfly.sketch.2.zip)

**Comment by gdoyle1** [comment]
Great work @LPutney Thank you!!! Just merged - closing this
