### ISSUE TITLE
Template file: Wizard updates

### ISSUE THREAD

**Issue by gdoyle1** [patternfly/patternfly-design-kit#236]
In the wizard page in the template file, check to make sure all examples match the implementation examples.
This issue includes:
1. Compare the wizard component examples to what we have : 
https://www.patternfly.org/v4/documentation/core/components/wizard
**Especially the mobile versions**
2. Compare the wizard demo examples to what we have in the file : https://www.patternfly.org/v4/documentation/core/demos/wizard
**Especially the mobile versions**
3. IF you need to update the symbols as well, add the "symbol" label and download the library file here https://www.sketch.com/s/2cf1063b-5283-4e0b-b8a6-cbb1ac07e29e/v/DEjZ02/. Make the changes to those symbols, upload the file to this issue and we can get it merged in then you can use those in the template file.
4. Update all artboards (if applicable) on the wizards page so they are accurate to what is implemented

**Comment by abichen** [comment]
[patternfly.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/4927851/patternfly.sketch.zip)
@gdoyle1 The Wizard and Mobile Wizard symbols had to be updated, so once those are merged I can update the template file as well!

**Comment by abichen** [comment]
[patternfly.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/4938581/patternfly.sketch.zip)
@gdoyle1

**Comment by gdoyle1** [comment]
@abichen Just merged the symbols! You should be good to do the template now :)

**Comment by abichen** [comment]
[patternfly-template.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/4954713/patternfly-template.sketch.zip)
@gdoyle1 All updated!

**Comment by gdoyle1** [comment]
Merged! Thanks @abichen
