### ISSUE TITLE
Typeahead dropdown height

### ISSUE THREAD

**Issue by lboehling** [patternfly/patternfly-design-kit#237]
Typeahead dropdown has a taller height (42px) than the other dropdowns. With the new chip designs, this should be able to have the same 36px height as the normal dropdowns. 

<img width="378" alt="Screen Shot 2020-06-25 at 11 38 40 AM" src="https://user-images.githubusercontent.com/46571616/85752330-53e69400-b6d9-11ea-9bd6-6526c8e64f6e.png">

**Comment by mviang** [comment]
[patternfly.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/4858773/patternfly.sketch.zip)
Updated the typeahead dropdown! @gdoyle1

**Comment by mmenestr** [comment]
Merged so i'm closing!
