### ISSUE TITLE
Remove dominant Hint

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design-kit#238]
We encountered problems implementing the dominant Hint variant and made a decision to remove it for now. We should also remove this symbol from the Sketch library. So there will only be the default (light blue) version of the hint.

**Comment by abchen-redhat** [comment]
[patternfly.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/4885537/patternfly.sketch.zip)
[patternfly-template.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/4885542/patternfly-template.sketch.zip)

Removed the dominant Hint variant instances from the design kit and template files! Also renamed symbols/artboards accordingly
@gdoyle1

**Comment by gdoyle1** [comment]
Merged! Closing this. Thank you!
