### ISSUE TITLE
Add horizontal and vertical splitter

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design-kit#240]
This issue is to add symbols for horizontal and vertical splitters. 

Naming would be the following:

- Splitter / Horizontal
- Splitter / Vertical

Marvel project with the spec: https://marvelapp.com/prototype/8cdg211/screen/69469192

All colors should already be in the library. This would be a good one to add the test run of adding a "pre-release" badge to the symbols (that the user _can override to turn off_).

**Comment by abichen** [comment]
[patternfly.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/4886848/patternfly.sketch.zip)
Added the horizontal and vertical splitters as symbols! The pre-release badge still needs work
@gdoyle1

**Comment by gdoyle1** [comment]
Merged! Thank you @abichen !
