### ISSUE TITLE
Update list and table templates to remove card backgounds

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design-kit#241]
Go through all full page examples in the template file (https://www.sketch.com/s/729c2eee-e8b6-4fcd-8a79-f6faa8c30f89) and ensure that all data lists, tables, and forms are no longer living on a card.

They should all match these designs: https://marvelapp.com/5996ff7/screen/69836554

Edit pages
1. Data lists
2. Tables

Updates to be made
- Remove the "card" symbol from the list group
- Push all content over so it left-aligns with the Header content
- Stretch all rows so they are 24px from the right
- Move any items within
- Add a divider under the header
- Fix indentation

**Comment by abichen** [comment]
[patternfly-template.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/4905265/patternfly-template.sketch.zip)
Updated data lists and tables! (excluding mobile views) 
@gdoyle1

**Comment by gdoyle1** [comment]
Thanks @abichen !!!! Just merged
