### ISSUE TITLE
Update "Card" symbol and template names

### ISSUE THREAD

**Issue by gdoyle1** [patternfly/patternfly-design-kit#243]
Based on documentation, we are moving the naming of Cards to be:
1. Standard (24px spacing) - change Large to Standard
2. Compact (16px spacing) - this would remain the same

Naming in the symbols all need to be updated as well as the template file

Template file change:
1. Compact (use as standard) change to Compact (recommended)
2. Large change to Standard

**Comment by abichen** [comment]
[patternfly.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/4920797/patternfly.sketch.zip)
[patternfly-template.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/4920798/patternfly-template.sketch.zip)
@gdoyle1

**Comment by gdoyle1** [comment]
@abichen hey! sorry we just actually decided to have this be "Default" rather than "Standard". Any way you could make those changes too?

**Comment by abichen** [comment]
[patternfly.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/4921498/patternfly.sketch.zip)
[patternfly-template.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/4921499/patternfly-template.sketch.zip)
@gdoyle1 Updated!

**Comment by gdoyle1** [comment]
Merged
