### ISSUE TITLE
Remove the rest of the card backgrounds for artboard with tables

### ISSUE THREAD

**Issue by gdoyle1** [patternfly/patternfly-design-kit#244]
Continue to remove the card bg from tables/lists so that they sit directly on the page. 

This applies to the following pages:

- Application launcher
- Column management
- Data list
- Empty state
- Inline alert
- Master detail
- Table
- Toolbar

**Comment by abichen** [comment]
[patternfly-template.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/4933959/patternfly-template.sketch.zip)
@gdoyle1

**Comment by gdoyle1** [comment]
Merged!
