### ISSUE TITLE
Ensure CTA symbols match spacing

### ISSUE THREAD

**Issue by gdoyle1** [patternfly/patternfly-design-kit#246]
Some of the spacing got updated along the implementation: https://github.com/patternfly/patternfly/pull/3214

Compare CTA symbols with that and ensure they are correct. Use inspect here https://www.patternfly.org/v4/documentation/core/components/button#call-to-action to see the spacing of the CTAs and the text styles used. Make sure to check both the buttons and the link buttons.

**Comment by abichen** [comment]
@gdoyle1 Everything LGTM! ✅

**Comment by gdoyle1** [comment]
Will close this, thanks @abichen !
