### ISSUE TITLE
Add Description list template

### ISSUE THREAD

**Issue by gdoyle1** [patternfly/patternfly-design-kit#247]
Add a template page with example of description list: https://github.com/patternfly/patternfly/pull/3243

Use the Default, Default 2 column and Default 3 columns examples from the Core examples here https://patternfly-pr-3243.surge.sh/documentation/core/components/descriptionlist to create artboards on a "Description list" page. Also put one example within a page for in-context example

**Comment by abichen** [comment]
[patternfly-template.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/4968008/patternfly-template.sketch.zip)
@gdoyle1

**Comment by gdoyle1** [comment]
Merged! Thank you @abichen
