### ISSUE TITLE
Add symbols to support checkboxes in menu item with description

### ISSUE THREAD

**Issue by gdoyle1** [patternfly/patternfly-design-kit#248]
Add additional symbols to item w description

https://github.com/patternfly/patternfly/pull/3224

**Comment by mmenestr** [comment]
Added the three following symbols:
Dropdowns / 3. Menu Item / 8. With description / With checkbox / Default
Dropdowns / 3. Menu Item / 8. With description / With checkbox / Disabled
Dropdowns / 3. Menu Item / 8. With description / With checkbox / Selected
Dropdowns / 3. Menu Item / 8. With description / With checkbox / Hover
