### ISSUE TITLE
Add menu items with select and icon

### ISSUE THREAD

**Issue by gdoyle1** [patternfly/patternfly-design-kit#249]
Add additional symbol for menu item that is selected AND has an icon on right

**Comment by gdoyle1** [comment]
So I merged the symbols for favorites in the normal menu items for this @doruskova  - I'm thinking we create other issues for:
1. Adding favorites to menu items with descriptions
2. Adding variations of menu items with icon on left vs. icon on right - this way we can get at the use case of someone wanting to put another icon in place of the favorite star

Let me know what you think!

**Comment by doruskova** [comment]
@gdoyle1 It makes sense. Do you have any mocks for it so that we can create these two issues?

**Comment by gdoyle1** [comment]
@doruskova Here are mocks for #1 (favorites to menu items with descriptions): https://www.patternfly.org/v4/components/select#favorites and then symbols for `menu item with icon on left` exist... but only the default state. So maybe we make `default`, `hover`, `selected`, `disabled` states for `menu item with icon on left`. I thought I remembered you taking on a design story with `menu item with icon on right` ... or was that covered in the tree view design you did?

**Comment by doruskova** [comment]
@gdoyle1 Yes, it was for a tree view https://marvelapp.com/prototype/8cdg211/screen/69897125 and this was for a context menu (it's called menu) https://marvelapp.com/prototype/dhj94fe/screen/67940185

Is it this menu with an icon?

**Comment by gdoyle1** [comment]
@doruskova ah okay never mind then, I think we can just stick with 1 issue for `favorites to menu items with descriptions` and 1 issue for additional states to `menu item with icon on left` (default, hover, selected, disabled)

**Comment by gdoyle1** [comment]
Closing this but created follow up issues #291 and #292
