### ISSUE TITLE
Library update - new icon size & text input changes

### ISSUE THREAD

**Issue by ajacobs21e** [patternfly/patternfly-design-kit#25]
When I created the 'text box with icon' symbols I used 18px icons ($pf-global--icon--FontSize--md: pf-font-prem(18px) !default;) but the visual design uses 14px icons.

That icon size will have to change based on https://github.com/patternfly/patternfly-next/issues/1933
but in the meantime I am going to update those icon sizes to 14px so I'm not blocked on finishing this symbol. 

@gdoyle1 @cshinn

**Comment by ajacobs21e** [comment]
I'll also change the helper icon to the open circle version

**Comment by ajacobs21e** [comment]
[patternfly-4_icon_textbox.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/3298609/patternfly-4_icon_textbox.sketch.zip)
@gdoyle1

**Comment by gdoyle1** [comment]
Done! @ajacobs21e - Going to close this and keep an open issue regarding the icon size changes for future updates
