### ISSUE TITLE
Potential bug in Symbol lib with chip group with chip

### ISSUE THREAD

**Issue by mmenestr** [patternfly/patternfly-design-kit#251]
I can edit the Chip group label, but not the label for the chip itself!

![image](https://user-images.githubusercontent.com/51165119/87799847-b4ba4580-c81b-11ea-9a28-402a939c864e.png)

**Comment by gdoyle1** [comment]
@mmenestr Can you confirm that this was fixed with the last update? It may not be possible to have both the 'project' group category and the 'chip' text expand

**Comment by mmenestr** [comment]
It was fixed, in that both texts are editable, the only thing is the background doesn't automatically expand as you type in something longer in the chip!

See original + edited underneath!
![image](https://user-images.githubusercontent.com/51165119/88209781-35fd4800-cc21-11ea-88b2-87600d1f1ffd.png)

**Comment by gdoyle1** [comment]
Ah yeah I had to turn off the horizontal resizing since allow the chip to editable messed up the way the padding was able to stick. Can you stretch the symbol itself?

**Comment by gdoyle1** [comment]
Closing this based on our conversation on slack 😊
