### ISSUE TITLE
Add more versions of tab symbols

### ISSUE THREAD

**Issue by gdoyle1** [patternfly/patternfly-design-kit#254]
Add symbols to Tabs for the following:

1. Tabs with icons ([Use inspect on this documentation for specs](https://www.patternfly.org/v4/documentation/core/components/tabs#icons-and-text))
- This should be available for Open, Boxed, and Filled tabs
2. Secondary tabs ([Use inspect on this documentation for specs](https://www.patternfly.org/v4/documentation/core/components/tabs#tabs-with-sub-tabs))
- Also seen in [this documentation example](https://www.patternfly.org/v4/documentation/core/components/tabs#tabs-with-sub-tabs)

**Comment by abichen** [comment]
[patternfly.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/5105407/patternfly.sketch.zip)

Added the above mentioned tabs and also divided box tabs into first tab, middle tab, and last tab.
Passing this off to Gina to help with behavior of filled tabs with icons as well as testing! @gdoyle1

**Comment by doruskova** [comment]
@gdoyle1 The problem was fixed and the tabs are centered with flexible text!

**Comment by doruskova** [comment]
Oh, I forgot to add Core-only labels for labels with a grey bg. I'll add it next week.
