### ISSUE TITLE
Notification drawer alert background updates

### ISSUE THREAD

**Issue by gdoyle1** [patternfly/patternfly-design-kit#257]
Update notification drawer symbols so they include the correct bg colors

Reference: https://www.patternfly.org/v4/documentation/core/components/notificationdrawer#component-title

**Comment by abichen** [comment]
[patternfly.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/5053276/patternfly.sketch.zip)
@gdoyle1 Updated shadows and added hover states!

**Comment by gdoyle1** [comment]
Merged!!! Thank you @abichen
