### ISSUE TITLE
Add an "x" to notification drawer symbol

### ISSUE THREAD

**Issue by gdoyle1** [patternfly/patternfly-design-kit#259]
Add an "x" to the notification drawer header symbol by referencing [this marvel](https://marvelapp.com/prototype/8i964cj)

**Comment by abichen** [comment]
[patternfly.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/5058652/patternfly.sketch.zip)
@gdoyle1 This file has the updated recommendation notification drawer symbols in it as well!
