### ISSUE TITLE
Add label group symbols and template

### ISSUE THREAD

**Issue by gdoyle1** [patternfly/patternfly-design-kit#260]
Add new symbols for label groups by referencing this [marvel](https://marvelapp.com/prototype/5ajfj8f). It will generally follow the same format as chip groups do, including:

1. Label group / dismissible (for symbol designer - has text and the "x")
2. Label group / non-dismissible (for symbol designer - has text)
3. Label group / dismissible / with label (for symbol designer - try adding one label here)
4. Label group / non-dismissible / with label (for symbol designer - try adding one label here)
5. Label group / show more
6. Label group / show less

**Be sure to** add the PRE-RELEASE label to these symbols - will have labels on labels but that's fine

Add new template page called Labels and include label groups shown in the marvel as well as the responsive versions in both the popover and the compressed version of the label group. You can use the Sketch cloud file [here](https://www.sketch.com/s/a552bfaf-8c51-4898-a87e-44b7ca34c89f) for the full page example as well.

**Be sure to** add the PRE-RELEASE label to these artboards

**Comment by doruskova** [comment]
Symbols here: [patternfly-labels.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/5223923/patternfly-labels.sketch.zip)
Added a new text style for less/more labels and hover state (inspired by chips).

**Comment by gdoyle1** [comment]
@doruskova yes it looks great! I'm merging into lib now with my icon stuff :)

**Comment by gdoyle1** [comment]
Merged - you're all good to do a template! @doruskova

**Comment by doruskova** [comment]
@gdoyle1 Template merged!
