### ISSUE TITLE
Add template for inline alert/error message demo

### ISSUE THREAD

**Issue by gdoyle1** [patternfly/patternfly-design-kit#261]
In the template file, add new artboards to the page "Inline Alerts" that demonstrate the examples in [this marvel project](https://marvelapp.com/prototype/4j6agce):

1. Horizontal form demo example
2. Stacked from demo example

**Comment by doruskova** [comment]
[PatternFly-template.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/5262149/PatternFly-template.sketch.zip)
@gdoyle1 Can you review this issue? Wasn't sure about the width of the inline alert.

**Comment by gdoyle1** [comment]
@doruskova Just checked it out - I think the way you have them looks right to me!
