### ISSUE TITLE
Add modal symbol with icon in title

### ISSUE THREAD

**Issue by gdoyle1** [patternfly/patternfly-design-kit#262]
Based on the spec provided [here](https://github.com/patternfly/patternfly-design/issues/863#issuecomment-668789845), create:

1. New modal symbol that includes the icon in the header
2. New modal template that shows how one would use that

**Make sure** to mark the symbol and template with a pre-release badge as seen in the separator component

**Comment by mmenestr** [comment]
**Added two symbols:**
Modal / Compact (24px spacers) / Header and icon
Modal / Large (32px spacers) / Header and icon

**And added template examples:**
![image](https://user-images.githubusercontent.com/51165119/89949235-987caf00-dbf5-11ea-9d27-9513ae8c4465.png)

**Comment by gdoyle1** [comment]
Thanks @mmenestr !
