### ISSUE TITLE
Add recommendation variation of notification drawer item

### ISSUE THREAD

**Issue by gdoyle1** [patternfly/patternfly-design-kit#265]
Add a new symbol for the recommendation variation of a notification drawer item. Use inspect within [this implementation](https://patternfly-pr-3338.surge.sh/documentation/core/components/notificationdrawer#basic) to get details on:

1. Icon type and color
2. Status bar color (left bar)

**Make sure** to add a CORE ONLY label to this symbol! (see #266 for details)

**Comment by abichen** [comment]
[patternfly.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/5058619/patternfly.sketch.zip)
@gdoyle1

**Comment by gdoyle1** [comment]
Merged!
