### ISSUE TITLE
Add boxed tabs symbols with gray bg

### ISSUE THREAD

**Issue by gdoyle1** [patternfly/patternfly-design-kit#266]
**ON HOLD UNTIL #254 IS REVIEWED**

Add symbols for boxed tabs with a gray bg (rather than white). Taking this issue on would mean:

1. Renaming the existing boxed tab symbols so that it is clear you would use them when the content they are sitting above has a white
2. Adding the new boxed tab symbols to match this implementation https://patternfly-pr-3286.surge.sh/documentation/core/components/tabs#box-tabs-current-tab-background-light-300. Will need default, hover and selected states for each tab type (this is really just copying and pasting the existing boxed tabs and changing the coloring)
3. Adding a CORE ONLY label to the symbol (see splitter for an example) **make sure the override is set so you can turn this label off**

This will probably coincide with #254

**Comment by doruskova** [comment]
@gdoyle1 Merged!
