### ISSUE TITLE
Info banner color using the wrong blue

### ISSUE THREAD

**Issue by mmenestr** [patternfly/patternfly-design-kit#267]
Top is what it _should be_. Bottom is what it currently is!
Should be pf-global-primary-color-light-200
![image](https://user-images.githubusercontent.com/51165119/89824441-1b800580-db21-11ea-8d39-753c8b757627.png)

**Comment by gdoyle1** [comment]
@fionayhlin if you could also turn the overrides off for everything other than the text values too, that'd be great!

**Comment by fionayhlin** [comment]
@gdoyle1 updated as a local symbol like last time
[patternfly.sketch-banner.zip](https://github.com/patternfly/patternfly-design-kit/files/5084605/patternfly.sketch-banner.zip)

**Comment by doruskova** [comment]
@fionayhlin Merged!
