### ISSUE TITLE
Add symbols and template for toggle button group

### ISSUE THREAD

**Issue by gdoyle1** [patternfly/patternfly-design-kit#268]
Inspect [this documentation](https://patternfly-pr-3355.surge.sh/documentation/core/components/togglegroup) to add new `toggle group` symbols for the following:

1. Toggle group / Text / Default, Hover, Selected, Disabled
2. Toggle group / Icon / Default, Hover, Selected, Disabled
3. Toggle group / On gray bg / Text / Default, Hover, Selected, Disabled
3. Toggle group / On gray bg / Icon / Default, Hover, Selected, Disabled

Create a new page in the template file for `toggle group` to show how this component can be used in a full page.

**Be sure to** add CORE ONLY label to the symbols and template

**Comment by maryshak1996** [comment]
@gdoyle1 here are the symbols!! Do you know if there's any examples or anything for things that I could show it in context of with for the template?
[toggle-group-addition.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/5119710/toggle-group-addition.sketch.zip)

**Comment by gdoyle1** [comment]
@maryshak1996 thank you! So this was originally intended to go into the topology view - recreating that would probably be a pain lol. Another use of it would be toggling the view from a "Form" to "YAML" - maybe we could do something like that? You can just copy a form page and have the toggle set on "Form" and then you don't have to mock up a YAML page

**Comment by maryshak1996** [comment]
ahhh gotcha thanks @gdoyle1 I'll have some bandwidth next week that I could mock up a few different template examples

**Comment by doruskova** [comment]
@maryshak1996 @gdoyle1 Merged!

**Comment by maryshak1996** [comment]
Template here!
[toggle-template.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/5176410/toggle-template.sketch.zip)

**Comment by doruskova** [comment]
@maryshak1996 @gdoyle1  Merged! Thanks a lot.
