### ISSUE TITLE
Update navigation symbols 

### ISSUE THREAD

**Issue by gdoyle1** [patternfly/patternfly-design-kit#273]
Update the navigation symbols so they reflect the newest designs. Includes the following:

- [x] Use inspect on the [React demo](https://www.patternfly.org/v4/documentation/react/demos/page/default-nav) to figure out the specifics of the design
- [x] Default nav symbols
- [x] Expandable nav symbols
- [x] Grouped nav symbols
- [x] Horizontal nav (may not need changes) symbols
- [x] Tertiary nav (may not need changes) symbols

**Comment by doruskova** [comment]
@gdoyle1 Merged!

Default, Grouped > didn't notice anything new (let me know if you notice something)
Expandable nav > added divider
Horizontal nav and Tertiary nav > updated arrows (added lines, removed shadows), added disabled arrows

**Comment by gdoyle1** [comment]
@doruskova thank you!!!!!! you're the best
