### ISSUE TITLE
Update whole Template file with new navigation and notification badge symbols

### ISSUE THREAD

**Issue by gdoyle1** [patternfly/patternfly-design-kit#274]
This cannot be completed until #273 is complete.

Update all full pages within the Template file to use the newest nav **and** notification badge (the one with the count).

Most important page to update with navigation symbols is **Navigation**. Next would be going through the rest of the pages seeing where there are full page mockups and replacing with the new default nav.

Pages where the notification badge/masthead still need to be updated:
- [x] Navigation
- [x] Table
- [x] Toast alert
- [x] Toolbar
- [x] Search input
- [x] Wizard

**Comment by doruskova** [comment]
Merged Navigation page

**Comment by doruskova** [comment]
Merged everything else.
