### ISSUE TITLE
Add Context Selector with actions

### ISSUE THREAD

**Issue by doruskova** [patternfly/patternfly-design-kit#275]
Add new Context selector with actions at the bottom based on this mockup 
https://marvelapp.com/prototype/7ahigh3/screen/72291839

1. Add a new page to a template called Context selector
2. Show Context selector with actions, include spec (padding)
3. Create an example (see pictures from Gina in comments). 

Be sure to add the PRE-RELEASE label to these artboards.

**Comment by gdoyle1** [comment]
Example of this in context from OpenShift
<img width="1678" alt="Screen Shot 2020-09-14 at 9 55 50 AM" src="https://user-images.githubusercontent.com/30870144/93128832-11ac6d80-f69e-11ea-85f3-1b4965ec7cbb.png">
<img width="1676" alt="Screen Shot 2020-09-14 at 9 55 39 AM" src="https://user-images.githubusercontent.com/30870144/93128833-12450400-f69e-11ea-97ba-4672734793f7.png">

**Comment by doruskova** [comment]
Merged!
