### ISSUE TITLE
Change icons to the open style

### ISSUE THREAD

**Issue by ajacobs21e** [patternfly/patternfly-design-kit#28]
By Royal decree (talking to @kybaker ) we should be using open style icons. I'll check the file and see which ones might need to be changed and run then by Kyle first. 

So far I know the clock has to change. 

@gdoyle1

**Comment by ajacobs21e** [comment]
@kybaker a few questions for you:


<img width="278" alt="Screen Shot 2019-06-18 at 12 52 08 PM" src="https://user-images.githubusercontent.com/6415742/59703648-54944280-91c8-11e9-96d8-e9f38ff58f81.png">
We have both of these icons in the library now. Do we need both? What's the use case for one vs the other?

----

Some status icons, like exclamation-triangle and exclamation-circle, only come in the filled in version. I think we should keep all other status icons filled in then.
<img width="282" alt="Screen Shot 2019-06-18 at 12 53 56 PM" src="https://user-images.githubusercontent.com/6415742/59703705-7f7e9680-91c8-11e9-8f2d-e66992768731.png">
<img width="268" alt="Screen Shot 2019-06-18 at 12 53 47 PM" src="https://user-images.githubusercontent.com/6415742/59703710-81485a00-91c8-11e9-97c4-aaebe20bd2b6.png">
<img width="248" alt="Screen Shot 2019-06-18 at 12 54 31 PM" src="https://user-images.githubusercontent.com/6415742/59703713-82798700-91c8-11e9-98ee-e4e25923ba62.png">
KEEP THESE SOLID - correct?

---

Is the arrow a status icon? There's only a solid version of the arrow style we're using (on the left) but there is an open version of the other arrow style. {same for the up arrow}
<img width="398" alt="Screen Shot 2019-06-18 at 12 54 18 PM" src="https://user-images.githubusercontent.com/6415742/59703785-ab018100-91c8-11e9-88eb-00398e8f8791.png">

**Comment by kybaker** [comment]
> @kybaker a few questions for you:
> 
> <img alt="Screen Shot 2019-06-18 at 12 52 08 PM" width="278" src="https://user-images.githubusercontent.com/6415742/59703648-54944280-91c8-11e9-96d8-e9f38ff58f81.png">
> We have both of these icons in the library now. Do we need both? What's the use case for one vs the other?

Lets go with the solid one since the square dimensions which allows us to make the icon larger. This shape also allows us to center align it with text. 

> 
> Some status icons, like exclamation-triangle and exclamation-circle, only come in the filled in version. I think we should keep all other status icons filled in then.
> <img alt="Screen Shot 2019-06-18 at 12 53 56 PM" width="282" src="https://user-images.githubusercontent.com/6415742/59703705-7f7e9680-91c8-11e9-8f2d-e66992768731.png">
> <img alt="Screen Shot 2019-06-18 at 12 53 47 PM" width="268" src="https://user-images.githubusercontent.com/6415742/59703710-81485a00-91c8-11e9-97c4-aaebe20bd2b6.png">
> <img alt="Screen Shot 2019-06-18 at 12 54 31 PM" width="248" src="https://user-images.githubusercontent.com/6415742/59703713-82798700-91c8-11e9-98ee-e4e25923ba62.png">
> KEEP THESE SOLID - correct?

Yes - keep these solid. This is a good place for an exception since we need these to draw attention.

> 
> Is the arrow a status icon? There's only a solid version of the arrow style we're using (on the left) but there is an open version of the other arrow style. {same for the up arrow}
> <img alt="Screen Shot 2019-06-18 at 12 54 18 PM" width="398" src="https://user-images.githubusercontent.com/6415742/59703785-ab018100-91c8-11e9-88eb-00398e8f8791.png">

**Comment by ajacobs21e** [comment]
Thanks @kybaker !

TO DO:
- Change clock to open version
- Remove Icons / Framework / external-link-alt

**Comment by ajacobs21e** [comment]
[patternfly-4-icon update.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/3302766/patternfly-4-icon.update.sketch.zip)
@gdoyle1 done!

**Comment by gdoyle1** [comment]
Merged!
