### ISSUE TITLE
Fix fonts in a template

### ISSUE THREAD

**Issue by doruskova** [patternfly/patternfly-design-kit#280]
![Snímek obrazovky 2020-09-18 v 13 21 05](https://user-images.githubusercontent.com/32618096/93599978-49c5f000-f9bf-11ea-8378-0589ee860391.png)

I went through a template because Sketch always complains that the Font is missing. So, I used the [Fontily plugin](https://github.com/partyka1/Fontily) in Sketch to find where Overpass was used and where UX Comment with OpenSans was used. The result was that OpenSans wasn't used anywhere > I removed this font-style from the doc because we have an official _small comment_ style.  

And the Overpass was used in:
-  "About this document" > updated
- "Toast alert" > updated

Hope that it'll be okay now and Sketch will not complain @gdoyle1 :D

**Comment by gdoyle1** [comment]
YAY @doruskova thank you!!!!
