### ISSUE TITLE
Create Catalog View template

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design-kit#282]
Add a Catalog view to a template based on this mock: https://marvelapp.com/prototype/24g4a7g6/screen/72488225

- Add a new page in a template called "Catalog view"
- Create a Catalog view artboard that shows the component itself. 
- Create a Catalog view artboard with spec and examples. I'd follow the Marvel that includes: basic layout, tablet example.

Here's the helpful sketch link:
https://www.sketch.com/s/381a44dc-d625-4d90-80e0-d98e802c6035

**Comment by mcarrano** [comment]
Per discussion we may want to create a generic Panel symbol to be used for the left sidebar. Consider usage for drawers - inline vs overlay.

**Comment by maryshak1996** [comment]
issue for drawer component symbols: https://github.com/patternfly/patternfly-design-kit/issues/286

**Comment by maryshak1996** [comment]
I did two examples (each showing responsiveness) -- definitely let me know if you need any changes made to this though :) 
[catalog-template.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/5300051/catalog-template.sketch.zip)

**Comment by doruskova** [comment]
@maryshak1996 I have just one thing, haha. Can you create an arboart that summarize all of these examples? Just show, for example, the default catalog view and the more difficult next to each other with padding. Does it make sense to you?

**Comment by maryshak1996** [comment]
@doruskova oh yup, I knew I was forgetting something haha -- I'll post that by the end of the week!

**Comment by maryshak1996** [comment]
[catalog-template.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/5313766/catalog-template.sketch.zip)
I added a sort of overview/help art-board here :)

**Comment by doruskova** [comment]
@maryshak1996 Merged!
