### ISSUE TITLE
Drill-down tree menu

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design-kit#284]
Add a default drill-down tree menu to a symbol library and a template based on this mockup https://marvelapp.com/prototype/66b0059/screen/72079939 (just the default version without icons etc). Here's the spec https://marvelapp.com/prototype/66b0059/screen/72079923 

Also, here's the sketch file from Marvel: 
[drill-down-menu.zip](https://github.com/patternfly/patternfly-design-kit/files/5256693/drill-down-menu.zip)
 
Taking this issue means: 

**Symbol library:** 
- Create a new page called Drill down menu

_Backgrounds_
- Drill down menu/ Background / Default and Drill down menu/ Background / Hover

_Items and navigation_
- Create default items, parents, and selected items. 
- Create nav with separator

Add **core-only** labels to these artboards. 

**Template:** 
- Add a new drill-down menu to the Menus page.
- Add a drill-down menu with spec.
- Add examples, you can use these use-cases as an inspiration https://marvelapp.com/prototype/66b0059/screen/72416835 

The template should show that it's possible to use it in a dropdown and in a primary detail. 

Add **core-only** labels to these artboards and make sure that you're adding only components from the PF library.

**Comment by doruskova** [comment]
@maryshak1996 Here's the current HTML implementation https://patternfly-pr-3438.surge.sh/documentation/core/components/menu#drilldown-level-two

It's just a default version without icons etc.

**Comment by maryshak1996** [comment]
@doruskova here are the symbols! once these are merged in I'll make some templates :) 
[drill-down-menu-symbols.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/5293840/drill-down-menu-symbols.sketch.zip)

**Comment by maryshak1996** [comment]
@doruskova just realized that I didn't include the 'core-only' labels -- do you want me to do that or do you just want to do it when you merge it in?

**Comment by doruskova** [comment]
@maryshak1996 Thank you! You're incredible and no worries I'll add them when I merge it in.

**Comment by doruskova** [comment]
@maryshak1996 Merged!

**Comment by maryshak1996** [comment]
Here's the template :) 
[drill-down-template-addition.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/5336241/drill-down-template-addition.sketch.zip)

**Comment by doruskova** [comment]
@maryshak1996 Merged!
