### ISSUE TITLE
Add Code editor to a symbol library and template

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design-kit#285]
Create Code editor based on this mock (version 1) https://marvelapp.com/prototype/b284chd/screen/70964526
HTML implementation here https://www.patternfly.org/v4/components/code-editor
This issue needs: 

**Symbols:**
- Create a new page called "Code editor".
- Create an artboard with the container for a block of code. 
- This container has read-only and edit mode. 

Hierarchy in Sketch
Code editor / multi-line / 1. Read-only
Code editor / multi-line / 2. Edit

Make sure you added Core-only labels to these artboards.

**Template:**

- Create a new page in a template called "Code editor" 
- Create artboards with design specifications and examples.

 
Make sure you added Core-only label to these artboards and be sure that you're adding components from the PF library.

**Comment by doruskova** [comment]
@gdoyle1 Is there any progress? Just checking before this year ends.

**Comment by gdoyle1** [comment]
I will take a look at this and my other remaining issues right now!

**Comment by gdoyle1** [comment]
Merged this! Ended up adding code editor as a new page with code block (where you can have read-only and editable code blocks) as well as code snippets (formatting text to look like code). Added templates for this as well

**Comment by doruskova** [comment]
@gdoyle1 Thank you! You're amazing.
