### ISSUE TITLE
Add drawer symbols to library

### ISSUE THREAD

**Issue by maryshak1996** [patternfly/patternfly-design-kit#286]
Create the various versions of the [drawer component](https://www.patternfly.org/v4/components/drawer) as symbols:

- [ ] Inline drawer (left, right, bottom)
- [ ] Overlay drawer (left, right, bottom)

**Comment by maryshak1996** [comment]
@doruskova @gdoyle1 (not sure where you guys are in the handoff of merging things so tagging you both haha) -- if you could merge in these drawer symbols here that would be great, then I get working on the catalog template! Thanks!
[drawer-symbols.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/5277063/drawer-symbols.sketch.zip)

**Comment by doruskova** [comment]
@maryshak1996 Merged!
