### ISSUE TITLE
Primary dropdown symbol needs doesn't match implementation

### ISSUE THREAD

**Issue by maryshak1996** [patternfly/patternfly-design-kit#288]
The primary dropdown symbol has two inconsistencies with [what's been implemented here](https://patternfly-pr-3438.surge.sh/components/dropdown#primary-toggle). Screenshot of the symbol as is below: 
![image](https://user-images.githubusercontent.com/19824574/95248546-7498ac80-07e5-11eb-81ac-12abcabdfca4.png)
 
- [x] The dropdown caret should default to being white (currently the symbol has a black caret)
- [x] The symbol should have the rounded corners that other buttons have (currently it has square edges)

**Comment by doruskova** [comment]
@maryshak1996 Fixed!
