### ISSUE TITLE
Down caret in primary dropdown toggle should be white

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design-kit#293]
The down caret in the Primary variant of the Dropdown toggle is dark, should be light.

![Screen Shot 2020-10-07 at 3 29 24 PM](https://user-images.githubusercontent.com/6619860/95378590-22718d00-08b2-11eb-9b5f-63e7096201f2.png)

**Comment by doruskova** [comment]
The issue noticed here #288

**Comment by doruskova** [comment]
@mcarrano Fixed in #288
