### ISSUE TITLE
Add: Toolbar filters

### ISSUE THREAD

**Issue by ajacobs21e** [patternfly/patternfly-design-kit#30]
Adding a textbox filter 
![image](https://user-images.githubusercontent.com/6415742/59774066-ccbc4000-927c-11e9-8a86-34ded17e02fa.png)

and attribute-value filter
![attribute-value-input](https://user-images.githubusercontent.com/6415742/59774169-02612900-927d-11e9-98c3-74894db48dae.png)

**Comment by mcarrano** [comment]
Something we should probably clarify here is whether the thing we call a "textbox" filter always has a search icon button. In my opinion the textbox filter and attribute-value are the same thing. Thoughts @mceledonia ?

**Comment by ajacobs21e** [comment]
@mcarrano the difference is if it's single (no dropdown) or multiple (dropdown). I'm only making that part of the component.

**Comment by ajacobs21e** [comment]
Added page for toolbar filters

Also fixed a few bugs on other pages:
* Changed form disabled text color to global-color-100 (instead of secondary)
* Added read-only text field
* Fixed dropdowns where 6px spacers were 8px tall

@gdoyle1  they're the first three pages with the eyes on them
[patternfly-4_toolbar filter.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/3308412/patternfly-4_toolbar.filter.sketch.zip)

**Comment by gdoyle1** [comment]
Merged!
