### ISSUE TITLE
Add horizontal card

### ISSUE THREAD

**Issue by doruskova** [patternfly/patternfly-design-kit#300]
Add a horizontal card example to a template. Mocks here https://marvelapp.com/prototype/5e55293/screen/72960491

- Add new artboards to a "Card view" page. 
- Add an artboard that introduces a horizontal card and the spacing
- Show the horizontal card in a context. 

Be sure you added pre-released labels to these artboards.

**Comment by gdoyle1** [comment]
Merged!
