### ISSUE TITLE
Add dual list selector

### ISSUE THREAD

**Issue by doruskova** [patternfly/patternfly-design-kit#301]
Add new Dual list selector to a symbol library and a template based on this mock https://marvelapp.com/prototype/12e47bhj/screen/72622268

Symbol library: 

- 

Add pre-released labels to these artboards. 

Template: 
- Create a new page called "Dual list selector"
- Create artboard that shows Dual list selector and spec
- Show some examples of how to use it. 

Add pre-released labels to these artboards.

**Comment by mmenestr** [comment]
Just added to the symbol library:
![image](https://user-images.githubusercontent.com/51165119/96029306-79ceaa80-0e28-11eb-8b3b-999b4fc4d7c0.png)

**Comment by mmenestr** [comment]
Just added to the template file:
![image](https://user-images.githubusercontent.com/51165119/96037139-6bd25700-0e33-11eb-9a15-b416b335634f.png)
