### ISSUE TITLE
Add Form sections

### ISSUE THREAD

**Issue by doruskova** [patternfly/patternfly-design-kit#302]
Add Form sections to a symbol library and a template based on this mock https://marvelapp.com/prototype/5e57if3/screen/72963176

Symbol library: 
- Add new artboards to a Forms page called "8. Form section". 
- Create symbols for a default field group - with/without description, with/without group actions
- Create symbols for a nested field group - with/without description, with/without group actions

Be sure you added Pre-release labels to these artboards. 

Template:
- Add new artboards with examples (from mock) to a Forms page in a template
- Include padding spec

Be sure you added Pre-release labels to these artboards.

**Comment by maryshak1996** [comment]
@doruskova these symbols should be all set! and I'll put together a template next week :) 
[form-sections-symbols-addition.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/5418547/form-sections-symbols-addition.sketch.zip)

**Comment by doruskova** [comment]
@maryshak1996 Hey! Thank you so much for the update. I have a few questions. 

1. What's the difference between the first/middle items and the last items? For example here: 
<img width="1094" alt="Snímek obrazovky 2020-10-22 v 14 22 48" src="https://user-images.githubusercontent.com/32618096/96871854-1e796980-1473-11eb-8b21-0cf6142dbce6.png">

I just can't find a difference. 

2. Can we differentiate the symbols for a field group and nested field group?
<img width="615" alt="Snímek obrazovky 2020-10-22 v 14 25 20" src="https://user-images.githubusercontent.com/32618096/96871879-25a07780-1473-11eb-8ada-c11d8407c1dc.png">

3. Can we reorganize the structure to be shorter a little bit? 
I was thinking something about this: 
![structure](https://user-images.githubusercontent.com/32618096/96877467-f80afc80-1479-11eb-814b-0e13ca537532.png)


Please, let me know if it makes sense to you or not and if you have any suggestions. :)  I'd like to keep it short, but sometimes it's difficult.

**Comment by maryshak1996** [comment]
Okay, so @doruskova the naming convention is slightly different than what you have but it's definitely much closer and supports nested vs field group versions :) here it is
[form-sections-symbols-addition.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/5441647/form-sections-symbols-addition.sketch.zip)

**Comment by doruskova** [comment]
@maryshak1996 You're amazing. Thank you so much!

**Comment by doruskova** [comment]
@maryshak1996 Merged!

**Comment by maryshak1996** [comment]
Annnnnnd here's the template!
[form-sections-template.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/5460741/form-sections-template.sketch.zip)
