### ISSUE TITLE
Library Update: Modal Symbols 

### ISSUE THREAD

**Issue by lboehling** [patternfly/patternfly-design-kit#31]
added to the modal page: 

Modal / Large / Header
Modal / Large / No Header
Modal / Large / Body Content
Modal / Large / Footer
Modal / Large / Background
Modal / Small / Header
Modal / Small / No Header
Modal / Small / Body Content
Modal / Small / Footer
Modal / Small / Background

Also updated the close icon size in modal to 18px. 

[patternfly-4-Modal.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/3311814/patternfly-4-Modal.sketch.zip)

**Comment by gdoyle1** [comment]
Merged!
