### ISSUE TITLE
New presentation of "Page" artboards in a template

### ISSUE THREAD

**Issue by doruskova** [patternfly/patternfly-design-kit#317]
"Page" artboards in a template are out of date and they can be presented in the "Navigation" page. 
@mcarrano FYI

**Comment by doruskova** [comment]
@mcarrano Is there any update on this? Just checking.

**Comment by mcarrano** [comment]
Thanks for the reminder @doruskova . I have been working on the Page guidelines and when I'm done I will send you updates to the template file.

**Comment by doruskova** [comment]
@mcarrano Thank you!

**Comment by mcarrano** [comment]
@doruskova here are the images I created for the Page guidelines documentation. https://www.sketch.com/s/929590e6-9636-4ded-913b-ec3b5dc7f726/v/JzK217/p/page  I can make templates from these and replace the content of the current Page page in the template file, but these are not really any different from what's on the Navigation page. Do you think we need both? Maybe we should just remove Page and/or rename Navigation to "Page with navigation" or something like that. Thoughts?

**Comment by doruskova** [comment]
@mcarrano oh, the link doesn't work. Can you give me access to your document? Thank you!

**Comment by doruskova** [comment]
@mcarrano Yeah, it looks similar. So, I think that it's a great idea to remove the "Page" page (haha) and rename Navigation to "Page with navigation". It makes more sense. Thank you! 

I can make this change quickly :)

**Comment by doruskova** [comment]
@mcarrano Merged!
