### ISSUE TITLE
Symbol library request for Notification drawer symbols

### ISSUE THREAD

**Issue by mmenestr** [patternfly/patternfly-design-kit#318]
@doruskova Wondering if it would be possible to switch the ordering for the naming of notification drawer symbols:

Instead of having Read or unread first, and then default and hover last, could we make it so that default and hover are first, and then read and unread are last? It makes more sense in terms of symbol usage. I'm using it heavily right now and I never use the hover state, only read and unread, so it's annoying to have to start from the beginning and drill down to find the unread version. Ideally Default > Unread and Default > Read would be in the same "container"

![image](https://user-images.githubusercontent.com/51165119/98687293-92eb4e00-2337-11eb-971f-2552bd651155.png)

**Comment by doruskova** [comment]
@mmenestr Haha, yes I agree that it's not practical at all and your suggestion makes sense to me. Anyway, I'll have to go through the library and notice issues like this. Do you want to change this component? But, if you don't have time, I can do it. :) It's up to you.

**Comment by mmenestr** [comment]
Do you mind doing it? Will be forever grateful!! :)

**Comment by doruskova** [comment]
No problem :)

**Comment by doruskova** [comment]
@mmenestr Fixed!
