### ISSUE TITLE
Popovers are weird!

### ISSUE THREAD

**Issue by ajacobs21e** [patternfly/patternfly-design-kit#32]
But not anymore! QA'd everything on the tooltips page and all of the spacing should be right now. 
[patternfly-4_Tooltips page.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/3312027/patternfly-4_Tooltips.page.sketch.zip)

@gdoyle1

**Comment by gdoyle1** [comment]
Merged! Thanks Allie!!
