### ISSUE TITLE
Labels demo

### ISSUE THREAD

**Issue by doruskova** [patternfly/patternfly-design-kit#325]
Create Labels page in a template and add these examples of using labels in a page https://marvelapp.com/prototype/bd077ag/screen/74286991

**Comment by doruskova** [comment]
@maryshak1996 Would you mind taking this issue? If you don't have time, it's ok. Just add the sketch file here for me so that I can add it :)

**Comment by maryshak1996** [comment]
@doruskova ya sure! also, just a heads up -- we are proposing some updates to the label component itself to support stronger accessibility. Once that issue comes in, you're welcome to assign that to me as well :)

**Comment by doruskova** [comment]
@maryshak1996 Label symbols have been updated :)

**Comment by maryshak1996** [comment]
[Uploading Labels-demo-addition.sketch.zip…]()
Here's the demo!

**Comment by doruskova** [comment]
@maryshak1996 Can you upload it again? I think that something went wrong because I can't download the file.

**Comment by maryshak1996** [comment]
[Labels-demo-addition.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/5996777/Labels-demo-addition.sketch.zip)
Hopefully this one works!

**Comment by doruskova** [comment]
@maryshak1996 Merged! Thank you!
