### ISSUE TITLE
List variants

### ISSUE THREAD

**Issue by doruskova** [patternfly/patternfly-design-kit#326]
Add list variants to a template. Mocks are available here https://marvelapp.com/prototype/7gc36d1/screen/75109901

**Comment by doruskova** [comment]
@maryshak1996 You've been working on this too, haha. So, if you can't add these to a template > it's fine, I can add it there. Just share the sketch file here. Thank you!

**Comment by maryshak1996** [comment]
@doruskova do you think that it would make sense to create symbols for the list items with icons as well? I think that it might help people use correct spacing and sizing if I made symbols for this too

**Comment by doruskova** [comment]
@maryshak1996 Yeah, that's a great idea!

**Comment by maryshak1996** [comment]
@doruskova here are the list variant symbols! Once these are merged in, I'll make the template :) 
[List variant symbols addition.zip](https://github.com/patternfly/patternfly-design-kit/files/5705648/List.variant.symbols.addition.zip)

**Comment by doruskova** [comment]
@maryshak1996 Merged! The only thing I changed is the RH logo to be higher quality :)

**Comment by doruskova** [comment]
@maryshak1996 Any update here?

**Comment by maryshak1996** [comment]
@doruskova woops, totally let the template fall off of my radar! I've got bandwidth to work on it this week :)

**Comment by maryshak1996** [comment]
[list-variants-template.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/6063777/list-variants-template.sketch.zip)
@doruskova I had made weeks ago and just forgot to post it here :p

**Comment by doruskova** [comment]
@maryshak1996 Merged! Thank you!
