### ISSUE TITLE
Dual list symbol

### ISSUE THREAD

**Issue by mmenestr** [patternfly/patternfly-design-kit#327]
The styling for a selected item with checkbox has changed. Instead of a selection being shown just with the checkbox, the text should now also be bolded and blue.

![image](https://user-images.githubusercontent.com/51165119/102925466-6875d000-4461-11eb-9974-9cee7c5f0ac5.png)

**Comment by doruskova** [comment]
Thank you for letting me know. I'm going to fix it today :)

**Comment by doruskova** [comment]
Merged!
