### ISSUE TITLE
Advanced search

### ISSUE THREAD

**Issue by doruskova** [patternfly/patternfly-design-kit#329]
Add Advanced search to a template. Mocks available here: 
https://marvelapp.com/prototype/276i4086/screen/75506113

**Comment by jhiadlov** [comment]
[attribute value search.zip](https://github.com/patternfly/patternfly-design-kit/files/5994614/attribute.value.search.zip)
Done:)

**Comment by jhiadlov** [comment]
[attribute value search + autocomplete.zip](https://github.com/patternfly/patternfly-design-kit/files/6002553/attribute.value.search.%2B.autocomplete.zip)
added autocomplete

**Comment by doruskova** [comment]
@jhiadlov Merged! Symbol and a template.
