### ISSUE TITLE
Library Update: fixing form widths

### ISSUE THREAD

**Issue by ajacobs21e** [patternfly/patternfly-design-kit#33]
Fixes to the form inputs & dropdowns meant that they were no longer the same size and therefore not interchangeable in the stacked or inline form symbols. Fixed widths of both to correct the error. 
[patternfly-4_dropdowns&forminputs.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/3312891/patternfly-4_dropdowns.forminputs.sketch.zip)

@gdoyle1

**Comment by gdoyle1** [comment]
Merged!
