### ISSUE TITLE
Update labels symbols

### ISSUE THREAD

**Issue by maryshak1996** [patternfly/patternfly-design-kit#330]
We have made more updates to the label component itself to better support accessibility over a grey background. updates can be seen here: https://marvelapp.com/project/5380059/screen/75382724 
Related to : #325

**Comment by maryshak1996** [comment]
Symbols are all set here :) at some point, we will be revisiting a new red color to use for the outline on Red-Heavy ([issue here](https://github.com/patternfly/patternfly-design/issues/979)), but this should be up to date and ready to merge!
[labels-addition.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/5803497/labels-addition.sketch.zip)

**Comment by doruskova** [comment]
@maryshak1996 Merged! Sorry for my delayed action.
