### ISSUE TITLE
Incorrect spacing in form sections symbols

### ISSUE THREAD

**Issue by maryshak1996** [patternfly/patternfly-design-kit#334]
I noticed that what is in the design kit uses `16px` spacers for padding in the the form sections, but what's implemented uses `24px` spacers above and below.

### Design kit
<img width="1090" alt="Screen Shot 2021-01-25 at 4 08 23 PM" src="https://user-images.githubusercontent.com/19824574/105766692-0dd00800-5f28-11eb-8a73-cf4f53d08c81.png">

### Implementation
<img width="740" alt="Screen Shot 2021-01-25 at 4 08 38 PM" src="https://user-images.githubusercontent.com/19824574/105766636-027cdc80-5f28-11eb-9744-f841fdc0a022.png">
<img width="238" alt="Screen Shot 2021-01-25 at 4 08 55 PM" src="https://user-images.githubusercontent.com/19824574/105766650-0577cd00-5f28-11eb-8579-d3b11fd98180.png">

**Comment by maryshak1996** [comment]
I'm actually noticing several issues with this symbol group (some of the overrides that should be editable are not and some the nesting behavior isn't consistent with the implementation). @doruskova I'm happy to make these fixes if you'd like, while the things are fresh on my mind!

**Comment by doruskova** [comment]
@maryshak1996 Go ahead! Thankk you that you found this issue!

**Comment by maryshak1996** [comment]
Updated symbols here:
[form-sections-updates.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/5896968/form-sections-updates.sketch.zip)

**Comment by doruskova** [comment]
@maryshak1996 Merged!
