### ISSUE TITLE
Login page template sizing discrepancies

### ISSUE THREAD

**Issue by ajacobs21e** [patternfly/patternfly-design-kit#335]
![image](https://user-images.githubusercontent.com/6415742/106300481-8da9eb00-6224-11eb-9063-02c8b70cbef0.png)

![image](https://user-images.githubusercontent.com/6415742/106300533-9b5f7080-6224-11eb-9a60-46b47a6a7a8a.png)

Sketch template file uses 2XL for title. Code is 3XL. Which one is right?
@mceledonia

**Comment by mceledonia** [comment]
Let's go with 3xl as is implemented, we can update the template file accordingly @ajacobs21e @doruskova

**Comment by doruskova** [comment]
@ajacobs21e @mceledonia Template has been fixed!
