### ISSUE TITLE
Add slider component

### ISSUE THREAD

**Issue by doruskova** [patternfly/patternfly-design-kit#339]
Add slider component from [here]( https://www.patternfly.org/v4/components/slider) to a symbol library. 

1. Create a circle indicator (default, hover, and selected state) 
- Slider/3. Circle > 1. Default (2.Hover, 3.Selected)

2. Create a grey line track 
- Slider/2. Line track/With steps
- Slider/2. Line track/Without steps

3. Create a blue line track with a circle
- Slider/1. Main track

@jhiadlov FYI

**Comment by jhiadlov** [comment]
[slider.zip](https://github.com/patternfly/patternfly-design-kit/files/6054073/slider.zip)
I made discrete and continuous sliders, I hope it will be alright :)

**Comment by doruskova** [comment]
@jhiadlov Merged! I changed it a little bit to make it more simple so that user can create a slider fast. However, awesome job! I took a look at all your layers and components and it was really nicely created.
