### ISSUE TITLE
Library Update: Alerts

### ISSUE THREAD

**Issue by mmenestr** [patternfly/patternfly-design-kit#34]
**Added to the alerts page:**

Alerts / 1. Info / Description
Alerts / 2. Success / Description
Alerts / 3. Warning / Description
Alerts / 4. Danger / Description

Alerts / 1. Info / Action Button
Alerts / 2. Success / Action Button
Alerts / 3. Warning / Action Button
Alerts / 4. Danger / Action Button

All Inline Actions - Including default,  w/dismissal, w/ description, w/ action button

**Added to the icon page**
All status icons in 24px

[Patternfly 4 - Alerts.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/3321532/Patternfly.4.-.Alerts.sketch.zip)

**Comment by gdoyle1** [comment]
Merged!
