### ISSUE TITLE
Item counts to the select dropdown

### ISSUE THREAD

**Issue by doruskova** [patternfly/patternfly-design-kit#343]
Add item counts (right-aligned) to a symbol library and an example to a template.  
Mocks for symbol: https://marvelapp.com/prototype/c18hjf1/screen/76910983
Mocks for a template: https://marvelapp.com/prototype/c18hjf1/screen/76941197

https://github.com/patternfly/patternfly-design/issues/759

**Comment by jhiadlov** [comment]
[number of items.zip](https://github.com/patternfly/patternfly-design-kit/files/6100982/number.of.items.zip)
I think I made it. In the first 2 symbols, I didn't use the same padding, please check it and tell me which one is correct, I will fix it. :)

**Comment by doruskova** [comment]
@jhiadlov I've checked the symbol and when there's only a number > it should definitely follow the current menu item design. I mean it should have the same spacing and height.
You used toggle symbols and it's correct for Catalog view. However, we need this symbol for the Select dropdown. You can find this group of symbols in Dropdown > Menu item

It looks good to me, just add this type of symbol for the Select dropdown. :))

**Comment by jhiadlov** [comment]
[number of items.zip](https://github.com/patternfly/patternfly-design-kit/files/6109092/number.of.items.zip)
Fixed :)

**Comment by doruskova** [comment]
@jhiadlov Could you add it to your downloaded library so that you have these new symbols with other symbols? And remove this symbol: Dropdown with label. It won't be a new symbol because badge and dropdown are already available in a library. Thank youu, great work!

**Comment by jhiadlov** [comment]
[PatternFly.sketch 2.zip](https://github.com/patternfly/patternfly-design-kit/files/6141081/PatternFly.sketch.2.zip)

**Comment by doruskova** [comment]
@jhiadlov Merged!

**Comment by doruskova** [comment]
@jhiadlov Create symbols for Catalog view with item counts

**Comment by jhiadlov** [comment]
[Toggle with number.zip](https://github.com/patternfly/patternfly-design-kit/files/6181105/Toggle.with.number.zip)
I did toggle with number

**Comment by doruskova** [comment]
@jhiadlov Merged!

**Comment by jhiadlov** [comment]
[Toggle with number.zip](https://github.com/patternfly/patternfly-design-kit/files/6181678/Toggle.with.number.zip)
Fixed

**Comment by jhiadlov** [comment]
[Catalog view.zip](https://github.com/patternfly/patternfly-design-kit/files/6187832/Catalog.view.zip)
I made Catalog view template :)

**Comment by doruskova** [comment]
@jhiadlov Amazing! Thank you! I'm going to merge it.
