### ISSUE TITLE
Add marketing variation of accordion

### ISSUE THREAD

**Issue by doruskova** [patternfly/patternfly-design-kit#344]
https://www.sketch.com/s/00432cc6-fd0c-454f-bdd6-c9720ceebbdc/a/OvQza4

https://github.com/patternfly/patternfly/pull/3888

**Comment by ajacobs21e** [comment]
I'll take this since it's my sketch file you linked :)

**Comment by ajacobs21e** [comment]
Fixed resizing behaviour of subtext on Tile components
Added large bordered accordion
-- includes adding Icon / Web Components / angle right & angle down
Added bordered accordion


There is a random icon button (kebab) on the accordion page. Do we know why that's there?

[PatternFly_tile_and_accordion.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/6084531/PatternFly_tile_and_accordion.sketch.zip)

**Comment by doruskova** [comment]
Thank you! Huh, I'll remove the icon, it's a bug.

**Comment by doruskova** [comment]
@ajacobs21e Merged!
