### ISSUE TITLE
Expansion for wizard steps

### ISSUE THREAD

**Issue by doruskova** [patternfly/patternfly-design-kit#353]
Add expansion symbol for wizard steps (Create only **one** symbol with arrow)
Mocks available here https://marvelapp.com/prototype/142h0f9e

Add an example to a template file. 
- Choose one screen (capturing the expansion) from a mock above and put it to a high-fidelity mock. 
- Don't create a mock with grey borders only. I want to see something like this https://www.sketch.com/s/729c2eee-e8b6-4fcd-8a79-f6faa8c30f89/p/wizard

Add a Pre-release label to a new symbol and a template (fix weight and height and align it to the left)
Create a symbol first and upload the file here for a review @jhiadlov 

https://github.com/patternfly/patternfly-design/issues/769

**Comment by jhiadlov** [comment]
[wizard steps.zip](https://github.com/patternfly/patternfly-design-kit/files/6221027/wizard.steps.zip)
I made 3 new types of wizard steps, in First and in After first. If there will be anything wrong, let me know, I'll fix it :)

**Comment by doruskova** [comment]
@jhiadlov Thank you! It looks good. However I noticed few things. Could you remove the "Opened" symbols? It's not necessary because if you use the first symbol with arrow > you can easily change the arrow icon. Also, I want to avoid overcrowding the menu with symbols. 
<img width="585" alt="Snímek obrazovky 2021-03-30 v 10 24 34" src="https://user-images.githubusercontent.com/32618096/112958027-51bad580-9142-11eb-8096-e4aca2df8cf4.png">

The next is the naming structure. There is a lot of nested symbols. I can imagine this structure: 

Wizard / Step / 1. First / With Arrow / Default
Wizard / Step / 1. First / With Arrow / Current
Wizard / Step / 2. After first / With Arrow / Default
Wizard / Step / 2. After first / With Arrow / Current

**Comment by jhiadlov** [comment]
[fixed wizard steps.zip](https://github.com/patternfly/patternfly-design-kit/files/6234370/fixed.wizard.steps.zip)
I hope it is alright now :)

**Comment by doruskova** [comment]
@jhiadlov It looks great! Thank you, I'll merge it.

**Comment by doruskova** [comment]
@jhiadlov Symbols merged!

**Comment by jhiadlov** [comment]
[wizard template.zip](https://github.com/patternfly/patternfly-design-kit/files/6254078/wizard.template.zip)
I made a wizard template. I add a pre-release label, but I don't know how to make it visible. Because when it is out of the artboard it is not visible :/

**Comment by doruskova** [comment]
@jhiadlov Looks great too. And the label in a template needs to be placed inside of the artboard because as you said >> it's not visible then. I usually put it to the upper right corner. But, no worries. I've already put it there so you don't have to do it. 

MERGED! 

I'm just wondering if wording for the symbol is ok "With arrow" or we should use, for example, "Expandable". WDYT?

**Comment by jhiadlov** [comment]
I didn't know how to name it properly 😅, so "Expandable" sounds pretty good to me :)
