### ISSUE TITLE
Add menu item with description for drill-down menu

### ISSUE THREAD

**Issue by doruskova** [patternfly/patternfly-design-kit#355]
Add menu item with a description as a new symbol
https://www.patternfly.org/v4/components/menu#with-drilldown

**Comment by jhiadlov** [comment]
[drill down menu w description.zip](https://github.com/patternfly/patternfly-design-kit/files/6254448/drill.down.menu.w.description.zip)
I did 3 drill down menus with a description :)

**Comment by doruskova** [comment]
@jhiadlov Looks great! Thank you! Btw. Don't work on Sunday!!
