### ISSUE TITLE
Add show/hide password to a Login page

### ISSUE THREAD

**Issue by doruskova** [patternfly/patternfly-design-kit#356]
Add Show/hide password to a template file. You can add this optional feature to some of our current screens. 
Implementation here: https://www.patternfly.org/v4/components/login-page#showhide-password

Use icon from fontawesome

**Comment by doruskova** [comment]
This issue depends on #369

**Comment by doruskova** [comment]
@jhiadlov Icons have been merged to a library so you can continue :)

**Comment by jhiadlov** [comment]
[Show:Hide passwword.zip](https://github.com/patternfly/patternfly-design-kit/files/6342914/Show.Hide.passwword.zip)
I add an eye icon to the password field and rename "Labels" to "Username" and "Password" in desktop, tablet, and mobile versions. If there is anything wrong, let me know, I'll fix it. :)

**Comment by doruskova** [comment]
@jhiadlov Did you send me the correct file? It should be added only in a template file, not a library.

**Comment by jhiadlov** [comment]
[Show:Hide password.zip](https://github.com/patternfly/patternfly-design-kit/files/6343201/Show.Hide.password.zip)
yeah, I zipped the wrong file 🤦🏼‍♀️ sorry

**Comment by doruskova** [comment]
@jhiadlov Could you add the icon also to the first artboard (it's Logic spec artboard) with spec?

**Comment by jhiadlov** [comment]
[Show:Hide Password.zip](https://github.com/patternfly/patternfly-design-kit/files/6343717/Show.Hide.Password.zip)

**Comment by doruskova** [comment]
@jhiadlov MERGED!
