### ISSUE TITLE
Minimize nested folders that are not necessary

### ISSUE THREAD

**Issue by doruskova** [patternfly/patternfly-design-kit#358]
I'd like to make the library more simple and some symbols are nested too much.
Goal: reorganize some symbols to avoid 3 or more nested folders

**Comment by ajacobs21e** [comment]
ALERTS! I can take on that folder if we want to break this up into multiple tasks

**Comment by doruskova** [comment]
@ajacobs21e Definitely! I'll create an epic so that we can include issues there.
