### ISSUE TITLE
Minimize symbol structure: Radio buttons / checkboxes

### ISSUE THREAD

**Issue by doruskova** [patternfly/patternfly-design-kit#361]

**Comment by ajacobs21e** [comment]
Radio buttons were already done.  I did checkboxes
[PatternFly_checkboxes.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/6402554/PatternFly_checkboxes.sketch.zip)

**Comment by doruskova** [comment]
@ajacobs21e You're a rockstar! Merged! I also thought about pulling out the checkboxes and radio buttons from the toggles section and put them directly under forms because when I use "toggle with text" and I want to change the checkbox > this is the result. Toggles folder/section seems duplicate. WDYT?
![Snímek obrazovky 2021-04-30 v 14 21 07](https://user-images.githubusercontent.com/32618096/116694612-c55d3600-a9bf-11eb-9841-e625d71c6c29.png)

**Comment by ajacobs21e** [comment]
Yeah I can do that too!

**Comment by doruskova** [comment]
@ajacobs21e You don't have to :) I'll do it with a plugin.

**Comment by ajacobs21e** [comment]
If you take all of the easy tasks, then what am I going to do? lol Thank you!

**Comment by doruskova** [comment]
Merged! Haha, thank you so much! I really appreciate your work! Btw. I'll find some easy tasks for you :D
