### ISSUE TITLE
Add Code block 

### ISSUE THREAD

**Issue by doruskova** [patternfly/patternfly-design-kit#363]
Add Code block https://www.patternfly.org/v4/components/code-block 
to a template file next to the code editor.

Add Core only label

**Comment by jhiadlov** [comment]
[Code block.zip](https://github.com/patternfly/patternfly-design-kit/files/6316263/Code.block.zip)
I add a new page called "Code block" and there are Basic and Expandable. I hope everything is alright. :)

**Comment by doruskova** [comment]
@jhiadlov MERGED!
