### ISSUE TITLE
Secondary horizontal nav (sub menu)

### ISSUE THREAD

**Issue by doruskova** [patternfly/patternfly-design-kit#365]
Update primary nav and create new subnav that replace tertiary nav.
https://marvelapp.com/prototype/fj0941h/screen/77719995

Full issue @jhiadlov: 
https://github.com/patternfly/patternfly-design/issues/958

- [x] 1. Update primary nav. The symbols are available in a symbols library here: masthead > horizontal nav
- [x] 2. Create new sub nav symbols for "Secondary horizontal nav" 
- [x] 3. Add pre-release label to these symbols
- [x] 4. Update template file with new symbols 
- [x] 5. Add mobile version

**Comment by jhiadlov** [comment]
[sub menu.zip](https://github.com/patternfly/patternfly-design-kit/files/6553636/sub.menu.zip)
Hi, on the Masthead page I made new symbols and added Pre-release labels. Then on the Mobile page, I added a new background symbol which is described in the Marvel file under the Subnav spec (mobile), but I wasn't sure about including the 16px space between levels. Please let me know if there is something wrong, I will fix it. :)

**Comment by doruskova** [comment]
@jhiadlov I guess that the only thing that is missing is the horizontal divider for the submenu items and for mobile version there should be dividers as well (left and top)

**Comment by jhiadlov** [comment]
[fixed subnav items.zip](https://github.com/patternfly/patternfly-design-kit/files/6583609/fixed.subnav.items.zip)
I just fixed some issues, could you please update it? :)

**Comment by jhiadlov** [comment]
[sub nav tertiary.zip](https://github.com/patternfly/patternfly-design-kit/files/6608737/sub.nav.tertiary.zip)
I add a new symbol to the Mobile page, it is called sub nav tertiary.

**Comment by doruskova** [comment]
Merged! You can continue with a template for both.

**Comment by jhiadlov** [comment]
I finally made it. :D 
[subnav template.zip](https://github.com/patternfly/patternfly-design-kit/files/6648581/subnav.template.zip)

**Comment by doruskova** [comment]
@jhiadlov Merged!
