### ISSUE TITLE
Disclosure - marketing context

### ISSUE THREAD

**Issue by doruskova** [patternfly/patternfly-design-kit#366]
Add a disclosure to a template file. Sketch file available:  https://www.sketch.com/s/00432cc6-fd0c-454f-bdd6-c9720ceebbdc/a/0D2ZYy

https://github.com/patternfly/patternfly-design/issues/874

**Comment by ajacobs21e** [comment]
Is this what is needed? I haven't been following this design story to know if it's changed. https://www.sketch.com/s/00432cc6-fd0c-454f-bdd6-c9720ceebbdc/a/0D2ZYy

**Comment by doruskova** [comment]
@ajacobs21e Thanks for the reminder, haha! I just forgot to add this sketch link to a description :D
