### ISSUE TITLE
View more for option overflow

### ISSUE THREAD

**Issue by doruskova** [patternfly/patternfly-design-kit#367]
https://marvelapp.com/prototype/c49ebi3/screen/77975699

Add the "View more" option to a template file.

Add pre-release label to a template

**Comment by jhiadlov** [comment]
[added view more.zip](https://github.com/patternfly/patternfly-design-kit/files/6375902/added.view.more.zip)
So I added "view more" options in Select page, but I am not sure if I did it right, I am a little bit confused 😅

**Comment by doruskova** [comment]
@jhiadlov Thanks! I noticed few things: 

- Could you create a spec for the View more option? I mean include this padding spec into the Select spec artboard.
- Could you create only 2 new artboards that will be called: _Select / Checkbox (expanded) / View more (simple)_  a  _Select / Checkbox (expanded) / View more (sticky)_
- Could you add a "Pre-release" label to a spec? 

Thank you :)

**Comment by jhiadlov** [comment]
[added View more option.zip](https://github.com/patternfly/patternfly-design-kit/files/6397518/added.View.more.option.zip)
I hope, I did right this time 😅

**Comment by doruskova** [comment]
@jhiadlov It looks great. But, can you add padding to the first view more spec?

**Comment by doruskova** [comment]
@jhiadlov Any update?

**Comment by jhiadlov** [comment]
[added paddings .zip](https://github.com/patternfly/patternfly-design-kit/files/6410998/added.paddings.zip)
got it :)

**Comment by doruskova** [comment]
@jhiadlov Merged!

**Comment by doruskova** [comment]
Just reopening the issue because of template file bug
