### ISSUE TITLE
Change styling for toggle group

### ISSUE THREAD

**Issue by doruskova** [patternfly/patternfly-design-kit#368]
Update **toggle group** symbols to reflect new styling (see picture below). 
<img width="311" alt="109863537-c11ad380-7c2f-11eb-8fba-e7b15df2fe23" src="https://user-images.githubusercontent.com/32618096/114709060-698e7e00-9d2c-11eb-8481-72722e8b16d6.png">

Current style: 
<img width="959" alt="Snímek obrazovky 2021-04-14 v 14 30 29" src="https://user-images.githubusercontent.com/32618096/114710425-fb4abb00-9d2d-11eb-9264-1a61cf73d76a.png">

Create a version for white and grey background. 
Create default, hover, selected, disabled states for each version. 
Create version without icon and with icon

**Comment by jhiadlov** [comment]
[toggle group.zip](https://github.com/patternfly/patternfly-design-kit/files/6420730/toggle.group.zip)
I just made in Toggle group on white bg first group without icon, could you please check it and tell me if it is right or if I should do it another way :) thanksss

**Comment by doruskova** [comment]
Michael added spec for this component
![unnamed](https://user-images.githubusercontent.com/32618096/117111346-bb548200-ad87-11eb-9fec-943ece5f1e92.png)

**Comment by jhiadlov** [comment]
[toggle group.zip](https://github.com/patternfly/patternfly-design-kit/files/6457579/toggle.group.zip)
fixed

**Comment by doruskova** [comment]
@jhiadlov Merged! You can continue :) Great job!

**Comment by jhiadlov** [comment]
[Toggle group.zip](https://github.com/patternfly/patternfly-design-kit/files/6488871/Toggle.group.zip)
I did the Toggle group for grey bg. For default options I kept dividers. Could you please check it out, and tell me what should I change or fix? Thank youuuu

**Comment by doruskova** [comment]
@jhiadlov I noticed just one detail, but I'll describe it on our call :)

**Comment by jhiadlov** [comment]
[toggle group.zip](https://github.com/patternfly/patternfly-design-kit/files/6492871/toggle.group.zip)
fixed borders

**Comment by doruskova** [comment]
@jhiadlov Merged!
