### ISSUE TITLE
Add eye and eye-slash icons

### ISSUE THREAD

**Issue by ajacobs21e** [patternfly/patternfly-design-kit#369]

**Comment by doruskova** [comment]
@ajacobs21e Working on it to get these icons to our PF icons set.

https://github.com/patternfly/patternfly-design/issues/1028

**Comment by bdellasc** [comment]
Related: https://github.com/patternfly/patternfly-design/issues/1028

**Comment by ajacobs21e** [comment]
[PatternFly_eyecons.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/6320351/PatternFly_eyecons.sketch.zip)

**Comment by doruskova** [comment]
@ajacobs21e Merged!

**Comment by ajacobs21e** [comment]
![image](https://user-images.githubusercontent.com/6415742/119896040-7944d900-bf0c-11eb-86ed-89b864754f97.png)
I used the outline versions and should have used solid

**Comment by ajacobs21e** [comment]
[PatternFly_eyecons_solid.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/6556808/PatternFly_eyecons_solid.sketch.zip)

@doruskova oopsie

**Comment by doruskova** [comment]
@ajacobs21e Thank youuu! I didn't even noticed that :D Merged!
