### ISSUE TITLE
Inconsistency: Masthead

### ISSUE THREAD

**Issue by ajacobs21e** [patternfly/patternfly-design-kit#37]
@gdoyle1 
On https://pf4.patternfly.org/components/Nav/examples/
The masthead tabs look like they're 64px tall with a 16px spacer above and 24px spacer below the text:
![Screen Shot 2019-06-24 at 1 27 11 PM](https://user-images.githubusercontent.com/6415742/60039186-24471b00-9684-11e9-972b-c27397f87120.png)

The entire masthead is 98px tall with a 16px spacer above & below each tab:
![Screen Shot 2019-06-24 at 1 26 49 PM](https://user-images.githubusercontent.com/6415742/60039336-725c1e80-9684-11e9-8fb6-e02049f80f05.png)

@kybaker is this correct?
It doesn't match what's on https://www.patternfly.org/v4/documentation/react/components/nav/
(no spacer below tab)
![Screen Shot 2019-06-24 at 1 33 06 PM](https://user-images.githubusercontent.com/6415742/60039407-a3d4ea00-9684-11e9-83f9-81581b4b73f5.png)

**Comment by ajacobs21e** [comment]
I started this fix but now I'm not sure if this is right.
[masthead.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/3321957/masthead.sketch.zip)

**Comment by gdoyle1** [comment]
@ajacobs21e It looks like somehow the website is STILL pulling in website styles... and my guess is that is why the spacing is off there. Let me confirm before I make a decision!!

**Comment by mceledonia** [comment]
@ajacobs21e @gdoyle1 @kybaker I'd say let's go with what's shown in documentation, no spacer below the tab.

**Comment by ajacobs21e** [comment]
@mceledonia I started making the change and it is breaking everything else.

https://www.patternfly.org/v4/documentation/react/demos/pagelayout/pagelayoutsimplenav/ 
This demo has a 76px tall masthead. But it doesn't have nav items as examples. 

This might take sitting down and looking at examples & code to figure out.
![Screen Shot 2019-06-26 at 10 44 36 AM](https://user-images.githubusercontent.com/6415742/60189736-6b0d5000-97ff-11e9-9378-23311cc58e49.png)
[Masthead2.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/3330596/Masthead2.sketch.zip)

**Comment by mceledonia** [comment]
Yeah happy to sit down and figure it out, it's worth noting it looks like those icons are spec'd incorrectly, they don't have the 24px bounding box which should be what the spacers rest against.

**Comment by matthewcarleton** [comment]
@ajacobs21e I was just talking to @gdoyle1 about this. The screenshot you posted about is getting that 16px spacer from the workspace preview. It doesn't get pulled into the actually layout.
If you look at the page layout with the horizontal nav you can see the spacers are correct.
<img width="1578" alt="Screen Shot 2019-06-28 at 10 11 48 AM" src="https://user-images.githubusercontent.com/287880/60344545-2c0d0500-998d-11e9-9846-b2877079404d.png">
That 76px height comes from a min-height applied to the header which is set for the brand area. 
Hopefully that helps :)

**Comment by ajacobs21e** [comment]
[Masthead3.zip](https://github.com/patternfly/patternfly-design-kit/files/3339383/Masthead3.zip)


Here's a file with the icons updated to have a 24px bounding box. I also added an icon for the menu (hamburger) and also an option for a custom text logo (instead of the PatternFly lockup)

Thanks @matthewcarleton ! So it's alright that there's 26px padding above & below the tabs and icons?

**Comment by matthewcarleton** [comment]
@ajacobs21e no prob :)
That's a good question. I think some further investigation could be done into the layout of the header and spacers being used. I think it's gets a bit tricky trying to get all of these elements to align properly while still leaving room for the logo and it's variations. 
I know the icons currently don't have a 24x24 bounding box in core b/c they are being pulled in as a font so we can't apply a box to them like you can with an svg. That might change though.
