### ISSUE TITLE
Update Avatar to create dark and light versions

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design-kit#370]
In release 2020.05 we are introducing new light and dark versions of the Avatar. These including new border treatments and placeholder image. See updates in this core PR: https://github.com/patternfly/patternfly/pull/3990

Original spec and artwork here: https://github.com/patternfly/patternfly/issues/3866

cc @ajacobs21e

**Comment by doruskova** [comment]
@mcarrano Updated!
