### ISSUE TITLE
Remove pixel sizes from icon category labels

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design-kit#371]
Currently labeling use for icon groups is correct, but inconsistent with actual implementation (see https://github.com/patternfly/patternfly/issues/3957). Rather than risk a visual breaking change, I'm recommending that we just remove reference to the pixel sizes in the labeling and just refer to the icons as "small, medium, large, and x-large." So the dimensions would no longer appear in the menu below:

![Screen Shot 2021-04-14 at 2 45 07 PM](https://user-images.githubusercontent.com/6619860/114766894-f806fd80-9d34-11eb-8c0b-9963bcc90879.png)

**Comment by doruskova** [comment]
Makes sense!

**Comment by doruskova** [comment]
@mcarrano Fixed!
