### ISSUE TITLE
Update Large Card symbol

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design-kit#372]
The large Card symbol does not match implementation. Should have 32px padding and spacing between sections except after title (24px). Title text is 20px. Body and footer are 16px. Here is an image 

![card-types](https://user-images.githubusercontent.com/6619860/115082535-135c3f00-9ed4-11eb-880a-7b3305a18bb6.png)

**Comment by doruskova** [comment]
@mcarrano Large card updated in a library
