### ISSUE TITLE
Add success and error help text to form symbols

### ISSUE THREAD

**Issue by gdoyle1** [patternfly/patternfly-design-kit#373]
Our form symbols include variations of help text, but when you override the input field type to success/error, the help text remains in the default text color when it should be green/red depending on success/error.

Today
![Screen Shot 2021-04-20 at 8 32 35 AM](https://user-images.githubusercontent.com/30870144/115396621-30825d80-a1b3-11eb-9bc2-903782e6c8d7.png)

What it should be
![Screen Shot 2021-04-20 at 8 34 24 AM](https://user-images.githubusercontent.com/30870144/115396646-38420200-a1b3-11eb-8736-3f9ff3d5c72b.png)

**Comment by doruskova** [comment]
@gdoyle1 Merged!
