### ISSUE TITLE
Password strength indicator

### ISSUE THREAD

**Issue by doruskova** [patternfly/patternfly-design-kit#380]
Add password strength indicator to login page in a template file. 
https://marvelapp.com/prototype/6jehce7/screen/78511266

Reopened > need to resolve inconsistent icons for a placeholder https://github.com/patternfly/patternfly-design/issues/1062

**Comment by ajacobs21e** [comment]
[Password strength.zip](https://github.com/patternfly/patternfly-design-kit/files/6495970/Password.strength.zip)
@doruskova can you check this and make sure it makes sense? I had to play with the line height of the strength name text ("weak" etc) to get it to bottom align with the field label ("Password"). 

Do we want this in a template of a full page account creation type form? The context is for creating a password, not entering a username / password on a login page.

**Comment by doruskova** [comment]
@ajacobs21e It makes sense to me :) I merged them and yes I guess we need a template for login page with this component. Can you share your use-case?

**Comment by doruskova** [comment]
@ajacobs21e Any update here?

**Comment by ajacobs21e** [comment]
@doruskova sorry totally forgot about this! I added two templates of this in context. Also trying this to share a sketch file rather than a zip file, maybe this is easier?
https://www.sketch.com/s/8b60350f-fbc0-48b7-9622-86d063ec4d1d
