### ISSUE TITLE
Optional finish button in wizard

### ISSUE THREAD

**Issue by doruskova** [patternfly/patternfly-design-kit#381]
Add optional finish button to wizard page in a template file. Mocks available 

Create a new artboard for this option. Don't add it to existing wizard artboards. https://marvelapp.com/prototype/62dig4j/screen/78180859

**Comment by jhiadlov** [comment]
[finish button in wizard.zip](https://github.com/patternfly/patternfly-design-kit/files/6457813/finish.button.in.wizard.zip)
Done, I hope it's alright 😅

**Comment by doruskova** [comment]
@jhiadlov Amazing! Thank you. Merged!
