### ISSUE TITLE
Add icon or image placeholder for cards

### ISSUE THREAD

**Issue by doruskova** [patternfly/patternfly-design-kit#383]
1. Create a card variation that includes a placeholder for the image/logo and add it to a symbol library. 
2. Add a spec to a template file 
3. Use the new symbols in a template file. Replace the old detached cards with the new component that allows adding images/logos.

**Comment by jhiadlov** [comment]
[card with logo.zip](https://github.com/patternfly/patternfly-design-kit/files/6821457/card.with.logo.zip)

**Comment by doruskova** [comment]
@jhiadlov Merged! I've edited the settings a little bit. We can discuss it next week :) You can update the template file :)

**Comment by jhiadlov** [comment]
[cards.zip](https://github.com/patternfly/patternfly-design-kit/files/6846210/cards.zip)

So I changed the old cards with the new cards symbols in the template file.

**Comment by doruskova** [comment]
@jhiadlov merged!
