### ISSUE TITLE
Copy to clipboard

### ISSUE THREAD

**Issue by doruskova** [patternfly/patternfly-design-kit#385]
Add new symbols called "Copy to clipboard" to a symbol library. 
Mocks here https://marvelapp.com/prototype/g39724e/screen/77261405
PR preview https://patternfly-pr-3933.surge.sh/components/clipboard-copy/#inline

1. Add basic version (editable and read-only)
2. Add expandable version (editable and read-only)
3. Add inline version (basic, code, and another action)

Try to use a small number of symbols. 

@jhiadlov 

Add examples in a context to a template file. Use PF screen of a page with a drawer and add this feature. to a drawer like this. 

1. Inline version
2. Basic one expandable.

![107276505-1b55b980-6a21-11eb-9d91-ebcfb454a17c](https://user-images.githubusercontent.com/32618096/121000024-0e0bca00-c78a-11eb-8e02-618fd8cf5330.png)
![107276506-1bee5000-6a21-11eb-8028-a67bedad8e15](https://user-images.githubusercontent.com/32618096/121000027-0ea46080-c78a-11eb-8073-cba43ce9a019.png)

**Comment by jhiadlov** [comment]
[copy clipboard.zip](https://github.com/patternfly/patternfly-design-kit/files/6607848/copy.clipboard.zip)
Hi, I made a new page called Clipboard copy where I put the new symbols, I hope they are alright.

**Comment by doruskova** [comment]
@jhiadlov Merged! Could you create a template for it? You can ignore the left part and just put empty cards there. The most important is the drawer with this component

**Comment by jhiadlov** [comment]
[copy to clipboard.zip](https://github.com/patternfly/patternfly-design-kit/files/6669691/copy.to.clipboard.zip)
Finally? 😅

**Comment by doruskova** [comment]
@jhiadlov Yes! Merged! Just please be sure that your symbols don't come from the _outdated library. If so, use Camilo plugin to transfer them to PatternFly library or use the most up to date template file.
