### ISSUE TITLE
Label size in design kit does not match implemented 

### ISSUE THREAD

**Issue by katierik** [patternfly/patternfly-design-kit#388]
![image](https://user-images.githubusercontent.com/23172038/116615615-91273e00-a909-11eb-8035-5a0854fb7351.png)
In implementation, the label text size is 14px. 
![image](https://user-images.githubusercontent.com/23172038/116615674-a1d7b400-a909-11eb-8f2f-b873477e647d.png)
In the design kit, the label text size is 12px.

The larger label size in implementation does not work well for compact tables, see below:
![large labels](https://user-images.githubusercontent.com/23172038/116615732-b61bb100-a909-11eb-8f77-e02f9ab28cf6.jpg)

The request is to update the implemented label size to size 12 font (and subsequent overall size changes)

**Comment by katierik** [comment]
Thank you!

**Comment by doruskova** [comment]
@maryshak1996 Would you mind taking this issue?

**Comment by maryshak1996** [comment]
sure @doruskova :)

**Comment by maryshak1996** [comment]
updated the labels + label groups @doruskova 
[PatternFly-labels-update.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/6510416/PatternFly-labels-update.sketch.zip)

**Comment by doruskova** [comment]
@maryshak1996 @katierik Merged! Library component updates should be available.

**Comment by katierik** [comment]
Thank you!
