### ISSUE TITLE
Library Update: Progress Bars

### ISSUE THREAD

**Issue by lboehling** [patternfly/patternfly-design-kit#39]
**Added to Progress Bar Page:** 
(All symbols on page are new)

Progress Bar / 1. In Progress / 1. Default / 1. Simple
Progress Bar / 1. In Progress / 1. Default / 2. Step Instructions
Progress Bar / 1. In Progress / 1. Default / 3. Finite Step
Progress Bar / 1. In Progress / 2. Small /  1. Simple
Progress Bar / 1. In Progress / 2. Small /  2. Step Instructions
Progress Bar / 1. In Progress / 2. Small /  3. Finite Step
Progress Bar / 1. In Progress / 3. Large / 1. Simple
Progress Bar / 1. In Progress / 3. Large / 2. Measure Inside
Progress Bar / 1. In Progress / 3. Large / 3. Measure Outside
Progress Bar / 1. In Progress / 3. Large / 4. Single line
Progress Bar / 1. In Progress / 3. Large / 5. Step Instrustions
Progress Bar / 1. In Progress / 3. Large / 6. Finite Step
___
Progress Bar / 2. Success / 1. Default 
Progress Bar / 2. Success / 2. Small 
Progress Bar / 2. Success / 3. Large / 1. Simple
Progress Bar / 2. Success / 3. Large / 2. Measure Inside
Progress Bar / 2. Success / 3. Large / 3. Measure Outside
___
Progress Bar / 3. Failure / 1. Default / 1. Simple
Progress Bar / 3. Failure / 1. Default / 2. No Measure
Progress Bar / 3. Failure / 2. Small / 1. Simple
Progress Bar / 3. Failure / 2. Small / 2. No Measure
Progress Bar / 3. Failure / 3. Large / 1. Simple
Progress Bar / 3. Failure / 3. Large / 2. No Measure
Progress Bar / 3. Failure / 3. Large / 3. Measure Outside

[patternfly-4-progressbar.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/3322174/patternfly-4-progressbar.sketch.zip)

**Comment by gdoyle1** [comment]
Merged!
