### ISSUE TITLE
Update labels in a template file

### ISSUE THREAD

**Issue by doruskova** [patternfly/patternfly-design-kit#390]
Labels in a symbol library have been updated > template needs an update too.

**Comment by jhiadlov** [comment]
[application launcher_labels.zip](https://github.com/patternfly/patternfly-design-kit/files/6731392/application.launcher_labels.zip)
Hi, I updated the labels on Application launcher's page, could you check it, please? Thanksss

**Comment by jhiadlov** [comment]
[labels.zip](https://github.com/patternfly/patternfly-design-kit/files/6994419/labels.zip)
I updated all labels in the Template file. Labels were on these pages: Application launcher, Cards*, Catalog view, Dashboard*, Form, Labels, Menus, Popovers and tooltips, Table, Tabs. 

*detached labels

**Comment by doruskova** [comment]
@jhiadlov Unfortunately, my fix broke your template...
I'll try to figure out how to make it less painful because i guess that we don't need a huge spec about labels.

**Comment by doruskova** [comment]
- [x] Application launcher fixed

**Comment by doruskova** [comment]
- [x] Fixed Labels page

**Comment by doruskova** [comment]
- [ ] Need to fix: table page,

**Comment by jhiadlov** [comment]
[table page_fixed labels.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/7149713/table.page_fixed.labels.sketch.zip)
I fixed labels on the table page.

**Comment by jhiadlov** [comment]
Merged!

**Comment by doruskova** [comment]
@jhiadlov I don't think you merged it.

**Comment by doruskova** [comment]
- [x] Cards page fixed
- [x] Menus page with labels fixed
