### ISSUE TITLE
Template file: Dashboard page

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design-kit#4]
Add a template for a generic Dashboard page

**Comment by gdoyle1** [comment]
@abichen do you want to pick this up and add all of of the dashboard card work we did for PF in the template file in the page called "Dashboards"? You can pretty much delete what's currently there!

**Comment by abichen** [comment]
[patternfly-template.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/4925979/patternfly-template.sketch.zip)
@gdoyle1 Added the dashboard cards that we made and cleaned everything up a tiny bit!

**Comment by gdoyle1** [comment]
Thanks @abichen !! Just merged this 🎉
