### ISSUE TITLE
Add filter tree menu

### ISSUE THREAD

**Issue by doruskova** [patternfly/patternfly-design-kit#402]
Add filter tree menu to a symbol library and a template file. Implementation of this component is available here https://www.patternfly.org/v4/demos/composable-menu/#filter-tree-menu
Mockups with a specification is here https://marvelapp.com/prototype/6hbd4bj/screen/76696403

It's an expandable tree in a dropdown with a badge
<img width="361" alt="Snímek obrazovky 2021-06-28 v 17 28 59" src="https://user-images.githubusercontent.com/32618096/123663140-663c6600-d836-11eb-8b30-0b09d2e03b04.png">

**Comment by doruskova** [comment]
@mmenestr Just wanted to ask you if you want to add it to a library and template file when you were working on it? I'll definitely understand if you don't have time. But, it's not urgent :)

**Comment by mmenestr** [comment]
Sure I can take this on! I think it just needs to be added to the template though no? Couldn't people just use the tree view symbols that already exist?

**Comment by doruskova** [comment]
@mmenestr yeah, if you used only existing symbols then create just a template for it.

**Comment by mmenestr** [comment]
I'm so sorry I completely forgot about this, will try to get it done by end of this week!!

**Comment by mmenestr** [comment]
Added this to the "Select" page!

![image](https://user-images.githubusercontent.com/51165119/132026642-2021a50d-9ce2-44c0-a1ba-940bbe3e66a3.png)

**Comment by doruskova** [comment]
@mmenestr Thank youu!
