### ISSUE TITLE
Minimize symbol structure: Navigation

### ISSUE THREAD

**Issue by ajacobs21e** [patternfly/patternfly-design-kit#409]

**Comment by ajacobs21e** [comment]
@doruskova I merged this change into the library, do you want to check it out before I mark this closed?

**Comment by doruskova** [comment]
@ajacobs21e Thank you! Sorry for my delayed answer. :D I'll clear up the naming in a library a little bit. But, it makes logical sense.

**Comment by doruskova** [comment]
@ajacobs21e I minimized it more and removed some symbols where the only difference was the padding.

**Comment by ajacobs21e** [comment]
@doruskova did you also remove the expanded version of the expandable nav? The collapsed version I can override the arrow to point down instead of right but there's no override for the bottom border. Personally I think it's easier to have a separate symbol for these two states than have to change two overrides. What do you think? I can add these in if you agree.

**Comment by doruskova** [comment]
@ajacobs21e ooohh I didn't realize that there is a bottom border. My fault. I put it back so it should be ok now :D
