### ISSUE TITLE
Buttons - change layout from "center" to "left to right"

### ISSUE THREAD

**Issue by ajacobs21e** [patternfly/patternfly-design-kit#413]
Button symbols are created to resize from the center out which doesn't make sense to me. As long as the text is centered, buttons can be stretched to be block level. But I believe the far more common use case is for buttons to be left aligned to something. 
@doruskova can I change all of the button symbols to resize from left to right? is there some reason they are center-out?

**Comment by doruskova** [comment]
@ajacobs21e Sure! I changed labels like that.

**Comment by ajacobs21e** [comment]
cool thanks - done!
