### ISSUE TITLE
Drill down menu items

### ISSUE THREAD

**Issue by doruskova** [patternfly/patternfly-design-kit#414]
Add drill-down menu items with breadcrumbs navigation. 

1. Add breadcrumbs header and include all states from breadcrumbs. Reason: existing breadcrumbs have a different size
2. Add a badge with a number and dropdown
3. Add menu item with icon

**Comment by jhiadlov** [comment]
[drill down menu items.zip](https://github.com/patternfly/patternfly-design-kit/files/7026705/drill.down.menu.items.zip)
On page "Drill down menu", I added Drill down menu / 2. Menu items / 2. Drill down / 3. Default with description / 2. Hover, and made Menu item with an icon with default and hover state. Then I did a breadcrumbs header with all states on page "Breadcrumbs". The last thing I made was a badge with a number and dropdown on the page "Badges". Could you please check if I did it right? Also, I have in my notes that I should make "Start rollout" (see pic), but I am not sure where should I put it.
<img width="189" alt="Screenshot 2021-08-22 at 10 07 42" src="https://user-images.githubusercontent.com/78600774/130345895-02469f0c-ae3a-4cbc-8b0a-e88844492c40.png">

**Comment by doruskova** [comment]
@jhiadlov Good! I've merged the items with icons and hover description item. 
I've allowed to change text size for breadcrumbs components. I'd like to add the example to a template file with it instead of duplicating symbols. They should have 16px which is a standard font-size and we have a text style for it. Another thing is that I replaced the badge from Badge page to Dropdowns because badge is not actionable and from the implementation point it's a dropdown with badge. https://www.patternfly.org/v4/components/dropdown#with-badge 

When it comes to your last question. These symbols already exists (Drill down menu / 3. 'Back' header / 1. Default). But, this one with icon is missing. Could you add them? Default and hover state. 
<img width="839" alt="Snímek obrazovky 2021-08-23 v 11 46 08" src="https://user-images.githubusercontent.com/32618096/130427669-87ca6f1a-806d-49cf-87b8-a7e5389466ec.png">

**Comment by jhiadlov** [comment]
[drill down menu:back header:with icon.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/7082681/drill.down.menu.back.header.with.icon.sketch.zip)
Hello, I added the symbol Drill down menu / 3. Back header / Default with icon and Drill down menu / 3. Back header / Hover with icon.

**Comment by jhiadlov** [comment]
[menu with breadcrumbs.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/7089531/menu.with.breadcrumbs.sketch.zip)
Here is a Template file with added Menu with breadcrumbs. I was just wondering if I should add to the template the "Set max menu height" and also "Start rollout" button (see pics under). What do you think? 
<img width="385" alt="Screenshot 2021-09-01 at 10 30 00" src="https://user-images.githubusercontent.com/78600774/131638885-fab2d777-5a6f-48e3-a3d0-f2856c887ac2.png">

<img width="213" alt="Screenshot 2021-09-01 at 10 28 53" src="https://user-images.githubusercontent.com/78600774/131638726-0bd6bcc0-83ec-446c-a406-73c9ac90a5bb.png">

**Comment by doruskova** [comment]
@jhiadlov I'd add "Start rollout" because it's a part of the component. But, "Set max menu height" not because it's part of the PF website.

**Comment by doruskova** [comment]
@jhiadlov Symbols merged!

**Comment by doruskova** [comment]
@jhiadlov Here's my review of breadcrumbs drill-down menu: 

- Group A - G shouldn't be only text. They are all menu items from "Dropdown" page.  
- The last item in a breadcrumb, "Application Grouping" is not a text as well. It's a leaf item symbol from breadcrumbs. 
- It's not just a menu, but drilldown menu because you can get more levels deep.

**Comment by jhiadlov** [comment]
[drilldown menu fixed.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/7116676/drilldown.menu.fixed.sketch.zip)
fixed, at least I hope so..

**Comment by jhiadlov** [comment]
[drilldown menu fixed.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/7127193/drilldown.menu.fixed.sketch.zip)
final

**Comment by doruskova** [comment]
Merged!
