### ISSUE TITLE
Design kit audit

### ISSUE THREAD

**Issue by doruskova** [patternfly/patternfly-design-kit#415]
Is everything working properly in our library? We need to do an audit of our library and create issues if anything is wrong.

**Comment by ajacobs21e** [comment]
grouped nav selected items - turn off overrides for highlight, background, and font

**Comment by doruskova** [comment]
@ajacobs21e Fixed! Good catch!

**Comment by ajacobs21e** [comment]
@doruskova thanks! would you prefer I open stories for little things like this or dump them here?

**Comment by ajacobs21e** [comment]
I also can do the fixes too but was going to save up a few small things so there isn't a library update every day

**Comment by ajacobs21e** [comment]
@doruskova sounds good thank you! I'll knock out what I can while you're gone. Enjoy your vacation!

**Comment by ajacobs21e** [comment]
[audit.csv](https://github.com/patternfly/patternfly-design-kit/files/7123459/audit.csv)

I saw this plugin to do an audit of a library so I tried it. Maybe it's helpful but it's at least cool to see how much stuff we've made!
https://docs.google.com/spreadsheets/d/1ZnW1DEHG7rK98HRZAvYIyOQ58OcOtk28DrvWoL2bG34/edit?usp=sharing this has it separated into 3 tabs for symbols, layer styles, and text styles

**Comment by doruskova** [comment]
@ajacobs21e This is awesome! I didn't know that we've made so many things :D
