### ISSUE TITLE
danger secondary and danger link button styles

### ISSUE THREAD

**Issue by ajacobs21e** [patternfly/patternfly-design-kit#416]
https://www.patternfly.org/v4/components/button

@doruskova is there a reason these aren't in the library other than we forgot them? If not I will add them!

**Comment by doruskova** [comment]
I don't think there is a reason :D I think we just forgot to add them. Go ahead and add them! Thanks for being soo active! Anyway, I have to do an audit of a library if everything works correctly or if anything is missing (like this example).

**Comment by doruskova** [comment]
Both buttons have been added to a library. Just need to reorganize the order numbers here.
