### ISSUE TITLE
Back to top button

### ISSUE THREAD

**Issue by doruskova** [patternfly/patternfly-design-kit#419]
Create a new button component called "back to top" to a symbol library. Full issue description is available [here](https://github.com/patternfly/patternfly-design/issues/970)

Please, follow instruction below: 

![127220429-de657fe2-a122-4a9e-9667-e6419a425ac4](https://user-images.githubusercontent.com/32618096/128870912-cbc6a83e-248c-4159-a713-11d469fecb51.png)

Real example. It's going to be used on a PF website, not in products. 
![127695970-eb2e40fc-3e92-407f-8cbf-5f8ac112d3a5](https://user-images.githubusercontent.com/32618096/128871461-690311b9-168e-4fad-9bce-0a9455414149.png)

![127696016-014d540c-09c2-4452-a7e6-73fc7206c31d](https://user-images.githubusercontent.com/32618096/128871549-19d2c57b-59d7-4e7d-a0a9-16f6c8053c96.png)

**Comment by jhiadlov** [comment]
[back to top button.zip](https://github.com/patternfly/patternfly-design-kit/files/6994408/back.to.top.button.zip)
I made 4 "Back to top" buttons: default, hover, focus, and disabled. I hope it is alright. :)

**Comment by doruskova** [comment]
@jhiadlov Hey, it looks great in overall. Just a little nitpicks: 

- name the sketch file with the same name as the compressed file (I have many Patternfly.sketch) 
- the top arrow on the left side needs to be pinned to the top.
- Make always sure that the overrides make sense. In this case, it should be possible to change only the text. 

It's merged! YAY!
