### ISSUE TITLE
Add disabled tabs

### ISSUE THREAD

**Issue by doruskova** [patternfly/patternfly-design-kit#421]
@jhiadlov Add disabled tabs to a symbol library. Each group of tabs should have a disabled state. That means that the user can't click on it and use the functionality. It can be enabled when the user triggers some action in advance. But, the main point is that disabled state uses darker gray color. The mock with the spec is available here: 

![127548848-41e2b45a-7847-47e3-8ab4-f969fec7d815](https://user-images.githubusercontent.com/32618096/130797874-0729f286-9f35-40f1-a6f2-3069fb6bc262.png)

Add disabled state for: 

- [x] 1. Horizontal open tabs (white bg)  
- [x] 3. Horizontal box tabs (white bg)
- [x] 4. Horizontal box tabs (gray bg) 
- [x] 5. Horizontal secondary tabs
- [x] 6. Vertical open tabs
- [x] 7. Vertical box tabs

Fill for white bg should be always #f5f5f5 (black-150)
Fill for gray bg should be always #d2d2d2 (black-300)

Make sure that the overrides and responsive behavior are correct and make sense. 

https://github.com/patternfly/patternfly-design/issues/1066

**Comment by jhiadlov** [comment]
[disabled tabs.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/7149587/disabled.tabs.sketch.zip)
I removed the shadows from the backgrounds and used rectangles instead.

**Comment by jhiadlov** [comment]
Merged! 🎉

**Comment by jhiadlov** [comment]
[disabled tabs.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/7208961/disabled.tabs.sketch.zip)
I added a disabled state for tabs with icons. I put a red rectangle under new symbols, so you can find them easily 😄

**Comment by doruskova** [comment]
@jhiadlov Merged!
