### ISSUE TITLE
Add expandable toast and inline alert 

### ISSUE THREAD

**Issue by doruskova** [patternfly/patternfly-design-kit#426]
https://www.patternfly.org/v4/components/alert/html#expandable

**Comment by jhiadlov** [comment]
[expandable toast and inline alert.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/7149666/expandable.toast.and.inline.alert.sketch.zip)
So I made "Alerts / Toast / 2. Success / 5. Expandable / 1. Closed & 2. Expandable" and  "Alerts / Inline / 2. Success / 9. Expandable / 1. Closed & 2. Expandable"

**Comment by doruskova** [comment]
@jhiadlov There is only the success alert, other types are mising (warning, info, danger etc.)

**Comment by doruskova** [comment]
@jhiadlov I guess you merged this. Not labels.
