### ISSUE TITLE
Add Progress stepper

### ISSUE THREAD

**Issue by doruskova** [patternfly/patternfly-design-kit#427]
We have a new component called Progress stepper. We have an HTML version available at this moment. 
https://www.patternfly.org/v4/components/progress-stepper

Mocks available [here](https://marvelapp.com/prototype/gfa4i5b/screen/80215316)

We need to add **basic, with description, centered, vertical with description, compact**,  (see the link above)

Note: We need to add a new text style for the centered version because we don't support centered text layers.

I'd create these symbols:

- [x] Create default items (I mean First step etc) 
- [x] Create default items with description
- [x] Create selected default item (with bold title)
- [x] Create a selected item with a description

Note: For these 4 items above, we also need a centered version with a new text layer style. 

- [x] Create a trail that I can stretch horizontally. 
- [x] Create a trail for the vertical version  
- [x] Create an empty circle
- [x] Create a circle with an icon inside >> I can change the icon

When it comes to a compact version > it needs only circles with icons and trail.

**Comment by jhiadlov** [comment]
[progress stepper.zip](https://github.com/patternfly/patternfly-design-kit/files/7337618/progress.stepper.zip)
I made everything, except horizontal centered (I made just one), because it isn't working as it should be, I don't know where am I making mistake. Could you please check it and maybe explain it to me? Text style is already added.

**Comment by jhiadlov** [comment]
[progress stepper.zip](https://github.com/patternfly/patternfly-design-kit/files/7346270/progress.stepper.zip)
added error style
