### ISSUE TITLE
Add enhancements to a dual list - drag & drop

### ISSUE THREAD

**Issue by doruskova** [patternfly/patternfly-design-kit#428]
Add this drag&drop enhancement for a dual list to a template file. 
![68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3563653831363532346536633539346463316230646634642f35663839323762342d626163302d343761342d383433612d396331653665313961303438](https://user-images.githubusercontent.com/32618096/132007307-58a4af96-7927-4356-afb0-a6f731ac2a33.png)

**Comment by doruskova** [comment]
@jhiadlov Dual list already exists in a template file and library. Please, add a drag & drop example to a template file. Before you merge it > let me review it.

**Comment by doruskova** [comment]
@jhiadlov 
<img width="839" alt="Snímek obrazovky 2021-09-22 v 14 29 26" src="https://user-images.githubusercontent.com/32618096/134343752-e7ce8159-a572-48d1-9fb5-78f8262ffd23.png">

**Comment by jhiadlov** [comment]
[dual list drag and drop states.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/7210990/dual.list.drag.and.drop.states.sketch.zip)
Could you please check it?

**Comment by doruskova** [comment]
@jhiadlov Merged. But, I had to make bigger gap between icon and text.

**Comment by doruskova** [comment]
@jhiadlov any updates here?

**Comment by jhiadlov** [comment]
[single list drag and drop.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/7293488/single.list.drag.and.drop.sketch.zip)

**Comment by doruskova** [comment]
@jhiadlov Merged!
