### ISSUE TITLE
Fix tertiary nav in a template

### ISSUE THREAD

**Issue by doruskova** [patternfly/patternfly-design-kit#431]

**Comment by doruskova** [comment]
- [x] Fixed in application launcher

**Comment by doruskova** [comment]
- [x] Fixed Hint

**Comment by jhiadlov** [comment]
- [ ] Form
- [ ] Jump links

**Comment by jhiadlov** [comment]
[fixed ter nav - forms and jump links.zip](https://github.com/patternfly/patternfly-design-kit/files/7293609/fixed.ter.nav.-.forms.and.jump.links.zip)
I fixed ter nav on Forms and Jump links pages

**Comment by doruskova** [comment]
@jhiadlov Merged! 

- [x] Alerts fixed
- [x] Code block fixed
