### ISSUE TITLE
Add compact version of toggle groups 

### ISSUE THREAD

**Issue by doruskova** [patternfly/patternfly-design-kit#435]
Here's the implementation https://www.patternfly.org/v4/components/toggle-group/html#compact

- Font 12px
- 24px height for each toggle item
- 
- Add default, hover, selected, disabled state. Without icons!

**Comment by jhiadlov** [comment]
[toggle group compact.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/7211195/toggle.group.compact.sketch.zip)

**Comment by doruskova** [comment]
@jhiadlov Merged! Just one nitpick here: don't override original layer style! Toggle group has own pre-defined styles that you can find in 1.Theme / Widgets / Toggle group. 
<img width="275" alt="Snímek obrazovky 2021-09-29 v 11 55 59" src="https://user-images.githubusercontent.com/32618096/135247410-73bf15bc-0897-45a3-99eb-ec42ac14f6f5.png">
.
