### ISSUE TITLE
New style for selected states (tiles and cards)

### ISSUE THREAD

**Issue by doruskova** [patternfly/patternfly-design-kit#441]
New styling for cards (Default, hover, selected state)! Interaction is being described here: 
https://github.com/patternfly/patternfly-design/issues/1042
![129913108-02658530-e93e-4a02-a2aa-6ea0eae3df76](https://user-images.githubusercontent.com/32618096/135247898-51d9b16e-a220-466f-9cda-495005183625.png)

Create a new style for hover and selected card and apply the new style on cards. 
- State / Active / Selected card 
- State / Hover / Card hover

**Comment by doruskova** [comment]
@jhiadlov This issue is on hold because it's still TBD. Just FYI

**Comment by doruskova** [comment]
@jhiadlov Implementation available here https://www.patternfly.org/v4/components/card#selectable-and-selected

**Comment by jhiadlov** [comment]
[card new style.zip](https://github.com/patternfly/patternfly-design-kit/files/7659568/card.new.style.zip)
Hey, I made a new style, could you please check it? Thanksss :)

**Comment by doruskova** [comment]
@jhiadlov Hey, it's merged! I just created a layer style for it because it'll be easier to change the background then :) 
The style is available under State/Card/Hover or selected

**Comment by doruskova** [comment]
#483 just FYI

**Comment by doruskova** [comment]
@jhiadlov So tiles have been merged from the previous issue. Could you create a template file that reflects the example displayed above? It should be added to Cards page :)

**Comment by doruskova** [comment]
@jhiadlov https://github.com/patternfly/patternfly-design-kit/issues/491

**Comment by jhiadlov** [comment]
[template cards new style.zip](https://github.com/patternfly/patternfly-design-kit/files/7815556/template.cards.new.style.zip)
I added cards with a new style to the template.

**Comment by jhiadlov** [comment]
[card states template.zip](https://github.com/patternfly/patternfly-design-kit/files/7837968/card.states.template.zip)
So I added cards with a new style into the template, so it is simulating the webpage. I hope it is alright now.

**Comment by doruskova** [comment]
@jhiadlov Yes, it is. But, create just one row with one card that is hovered, the other selected and the last is disabled. Doesn't make sense to have 3 selected, 3 hovered and 3 disabled. The other cards doesn't need any style. Just do it as it is in a picture above.

**Comment by jhiadlov** [comment]
Fixed and merged! 🎉
