### ISSUE TITLE
Add keyboard shortcuts in the PF code editor

### ISSUE THREAD

**Issue by doruskova** [patternfly/patternfly-design-kit#457]
Add these shortcuts to a library and create an example in a context. 
https://marvelapp.com/prototype/15bb10j4/screen/81521392

**Comment by doruskova** [comment]
@jhiadlov As Matt mentioned, need to consider the visual for this 
issue https://github.com/patternfly/patternfly-design/issues/991

**Comment by doruskova** [comment]
@jhiadlov So, Monaco editor already has a way to configure any keyboard shortcuts and also comes with most of the standard keyboard shortcuts built-in. That means we don't have to use labels from PF. However, I'd like to wait for the implementation.

**Comment by doruskova** [comment]
@jhiadlov Here's the implementation of the shortcuts! 
https://patternfly-react-pr-6989.surge.sh/components/code-editor

<img width="435" alt="Snímek obrazovky 2022-03-11 v 13 53 47" src="https://user-images.githubusercontent.com/32618096/157870366-20c527d3-bddd-481f-b9c4-19c630e9ab1f.png">

**Comment by jhiadlov** [comment]
Working on it! Sorry for not letting you know.

**Comment by jhiadlov** [comment]
[shorcut.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/8322643/shorcut.sketch.zip)
I made a shortcut on a Code editor page.

**Comment by doruskova** [comment]
@jhiadlov You can merge it and then create a template with this new symbol :)

**Comment by jhiadlov** [comment]
[code editor shortcuts template.zip](https://github.com/patternfly/patternfly-design-kit/files/8324872/code.editor.shortcuts.template.zip)
