### ISSUE TITLE
Library Update: About Modal + Navigation update

### ISSUE THREAD

**Issue by mmenestr** [patternfly/patternfly-design-kit#46]
Added in the following pages:

**Dropdown:**
_Updated:_
Dropdowns / 4. Seperator / Default

**Icons:**
Create new icon called: Icons / Actions / times-circle / 42px
(Used a 18px times icon in the middle, because 10px looked way too small)

**About modal:**
_Added_
About modal / Desktop
About modal / Tablet
About modal / Mobile

****** Note: Asked Christie about this because I wasn't sure which dimensions to use for each format (there are multiple) and she told me to go from the width breaking point so that's what I did! (also put a note on the page)

[Patternfly 4 - About Modal.zip](https://github.com/patternfly/patternfly-design-kit/files/3340853/Patternfly.4.-.About.Modal.zip)

**Comment by gdoyle1** [comment]
Merged! About modal looks great. Not sure how else we would do it, thanks for the thought you put into this!!
