### ISSUE TITLE
Tiles - Text Style = Centered, Layers = Centered/No Pin to edges

### ISSUE THREAD

**Issue by neanda** [patternfly/patternfly-design-kit#469]
I believe that the Tiles are used as a big button, so layers should be centered. The Tiles are a bit of a mess tbh (I don't mean to be harsh, just had to be said), especially when resizing or when changing the text values.  Maybe in the '1. Basic tile / 2. Text with icon' use a Text with Icon symbol to make it easier to keep it centered.   Also, maybe remove the pin to edges for the text layers. Thanks.

**Comment by doruskova** [comment]
@jhiadlov any update here?

**Comment by jhiadlov** [comment]
@doruskova I tried to fix it, but I don't think it's possible to make it in Sketch the way we want it to work.

**Comment by doruskova** [comment]
@jhiadlov Thank you for the update!

**Comment by doruskova** [comment]
@jhiadlov Fixed!

**Comment by neanda** [comment]
thank you

**Comment by neanda** [comment]
you guys are very smart people, this world needs this
