### ISSUE TITLE
Add FileUpload component

### ISSUE THREAD

**Issue by doruskova** [patternfly/patternfly-design-kit#479]
https://github.com/patternfly/patternfly-design/issues/1064

https://marvelapp.com/prototype/69jc198/screen/82770742

**Comment by doruskova** [comment]
@jhiadlov Here is a link to the sketch file: https://sketch.com/s/55446f68-c5d0-4845-94dc-6d8385e3f523

**Comment by jhiadlov** [comment]
[file_upload.zip](https://github.com/patternfly/patternfly-design-kit/files/7744611/file_upload.zip)
Hi, I made a few examples for file upload, but I still have some questions about it. I will ask you in our call.

**Comment by doruskova** [comment]
@jhiadlov Horizontal multiple file upload has been merged! It was correct! The only thing that is missing in a template file is: 
https://www.patternfly.org/v4/components/file-upload---multiple#basic
https://www.patternfly.org/v4/components/file-upload---multiple#drag-over
https://www.patternfly.org/v4/components/file-upload---multiple#file-upload-status-expanded

It's basically the same thing > just the content is centered in a card.

**Comment by doruskova** [comment]
Need to add this icon to a library https://fontawesome.com/v5.15/icons/file?style=solid

**Comment by doruskova** [comment]
Any update here?

**Comment by jhiadlov** [comment]
[FileUpload component.zip](https://github.com/patternfly/patternfly-design-kit/files/7888162/FileUpload.component.zip)
Added file upload basic, drag over, and file upload status expanded. Also updated file icons.

**Comment by doruskova** [comment]
@jhiadlov It looks amazing! You can merge it to our template file :)

**Comment by jhiadlov** [comment]
Merged! :)
