### ISSUE TITLE
Add navigation enhancements

### ISSUE THREAD

**Issue by doruskova** [patternfly/patternfly-design-kit#480]
Flyout [flyout-nav.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/7589070/flyout-nav.sketch.zip) - **DONE**
Drill down - https://www.patternfly.org/v4/components/navigation/html#nav-with-drilldown-menu - **DONE**
Third level - expandable https://www.patternfly.org/v4/components/navigation#expandable-third-level - **TEMPLATE MISSING**

**Comment by mcarrano** [comment]
Google doc with specs and prototype links: https://docs.google.com/document/d/17jhcgkUgpw7f9Ixf9ew8RfcivSck9mdv_Yw6fIZhlAs/edit?ts=60cb76dd#heading=h.ea3lujnv46vp

**Comment by jhiadlov** [comment]
Hi, I compared the sketch file (symbols) with the implementation of Nav with Flyout. 

- I added  ~ / L1 / hover
- corrected background color in ~ / L1 / hover and ~ / L1 / selected
- added left line in ~ / L1 / in group / expandable / collapsed / hover
[flyout-nav.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/7659938/flyout-nav.sketch.zip)
- changed horizontal padding from 24px to 16px in L1

Where can I check ~ / bundle and ~ / group title?

**Comment by doruskova** [comment]
@jhiadlov Thank you! The padding was correct. I merged it and it's also available in a template file. 
Just want to note here some advice:

- Always name your components how you (as a user) expect them to be organized in a library. I was soo confused about the L1 and ~. I know it was used in the original Sketch. But, it's not something you should follow in detail.
I guess that everyone will understand more something like: Navigation / Flyout / Default (hover etc.) right? 

- Then always check the overrides. We don't want users to change text styles (at least for now). 
- When you use line, then you can't apply a shared style. It has to be a rectangle that has 1px width. 
- Use shared styles as much as possible. If it doesn't exist > no worries > just create a new one with appropriate name and inclusion. 


Let me know if you have any questions :)

**Comment by doruskova** [comment]
@jhiadlov Would you mind taking the third level - expandable menu? And please follow the implementation :) There is no sketch file for it. 

- Name it as clear as possible. For example: Navigation / Third level expandable / Default (hover,selected) 
- When you'll create a template for it, please follow this screen https://www.sketch.com/s/729c2eee-e8b6-4fcd-8a79-f6faa8c30f89/a/oYZjvbQ

**Comment by doruskova** [comment]
@jhiadlov Drill down is done

**Comment by jhiadlov** [comment]
[third level.zip](https://github.com/patternfly/patternfly-design-kit/files/7744934/third.level.zip)
I did third-level symbols. Could you please check them?

**Comment by doruskova** [comment]
@jhiadlov Merged! Could you create a template for that? 
I changed the naming a little bit because your structure created a lot of nested folders. Try to keep 3 nested folders max.

**Comment by jhiadlov** [comment]
[expandable 3rd lvl menu template.zip](https://github.com/patternfly/patternfly-design-kit/files/7838192/expandable.3rd.lvl.menu.template.zip)
I made a template for 3rd level

**Comment by doruskova** [comment]
@jhiadlov Looks great! Can you add it to our template file?

**Comment by jhiadlov** [comment]
Merged! :)
