### ISSUE TITLE
Tiles and selected state update

### ISSUE THREAD

**Issue by doruskova** [patternfly/patternfly-design-kit#483]
https://www.patternfly.org/v4/components/tile

**Comment by doruskova** [comment]
Any update? @jhiadlov

**Comment by jhiadlov** [comment]
not yet, working on another issue :)

**Comment by jhiadlov** [comment]
[tiles.zip](https://github.com/patternfly/patternfly-design-kit/files/7744627/tiles.zip)
Updated tiles with new styles

**Comment by doruskova** [comment]
@jhiadlov Merged! Thank you!
