### ISSUE TITLE
Add table striped rows 

### ISSUE THREAD

**Issue by doruskova** [patternfly/patternfly-design-kit#487]
https://marvelapp.com/prototype/2ccbf976/screen/83674640

1. Add a row background that reflects stripes to a library. Use the lightest grey black-100 for a stripe. 
2. Create an example in a context.

**Comment by doruskova** [comment]
@jhiadlov Here's the implementation https://www.patternfly.org/v4/components/table#composable-striped
https://www.patternfly.org/v4/components/table#composable-striped-expandable

**Comment by doruskova** [comment]
@jhiadlov I would do this issue after table reorganization

**Comment by doruskova** [comment]
@jhiadlov Symbols have been created, but they are not merged yet because of changes in the table component.

**Comment by jhiadlov** [comment]
Merged!
