### ISSUE TITLE
Add file icon to a library

### ISSUE THREAD

**Issue by doruskova** [patternfly/patternfly-design-kit#489]
https://fontawesome.com/v5.15/icons/file?style=solid

This icon is missing in a library and it's being used in Multiple File upload component. 

Add File icon to a library - all sizes

**Comment by doruskova** [comment]
[file-solid.svg.zip](https://github.com/patternfly/patternfly-design-kit/files/7854469/file-solid.svg.zip)
@jhiadlov

**Comment by doruskova** [comment]
@jhiadlov Any update?

**Comment by jhiadlov** [comment]
[file icon.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/7887628/file.icon.sketch.zip)
I added File icon to framework category. The shape of Task icon looked similar to File icon, that's why I used the same height. Is it okay?

**Comment by doruskova** [comment]
@jhiadlov Looks great! Can you merge it?

**Comment by jhiadlov** [comment]
Merged!
