### ISSUE TITLE
Library update: Forms input, buttons, dropdowns, icons

### ISSUE THREAD

**Issue by mmenestr** [patternfly/patternfly-design-kit#49]
**Form inputs:**
_Updated:_
Forms / 4. Text box / disabled 
Forms / 5. Text Box with Icon / Error
Forms / Vertical Aligned Labels / Default (merge allie's version of this one - Check comment on allie's issues for details)
Forms / Horizontal Input Field / Default (merge allie's version of this one - Check comment on allie's issues for details)

_Added:_
Forms /  Input group icon / dollar-sign
Forms /  Input group icon / at
Forms /  Input group icon / calendar-alt
Forms /  Input group icon / copy
Forms /  Input group icon / copy hover
Forms /  Input group icon / copy selected
Forms /  Input group icon / dropdown collapsed
Forms /  Input group icon / dropdown hover
Forms /  Input group icon / dropdown expanded

All future input group templates (5 items)

Forms / 7. Input group / Money field
Forms / 7. Input group / Username field
Forms / 7. Input group / Date field
Forms / 7. Input group / Search field
Forms / 7. Input group / Question field

Forms / 8. Copy to clipboard / No expansion / Editable
Forms / 8. Copy to clipboard / No expansion / Read-only
Forms / 8. Copy to clipboard / Expansion / Editable / Collapsed
Forms / 8. Copy to clipboard / Expansion /Editable / Expanded
Forms / 8. Copy to clipboard / Expansion / Read-only / Collapsed
Forms / 8. Copy to clipboard / Expansion / Read-only / Expanded
Forms / 8. Copy to clipboard / Expansion / Text input

Forms / Vertical Aligned Labels / help text
Forms / Vertical Aligned Labels / Invalid input

**Buttons:**
Button / 1. Primary / Default / Left rounded
Button / 1. Primary / Action group

Button / 2. Secondary / Default / Left rounded
Button / 2. Secondary / Default / Right rounded
Button / 2. Secondary / Default / Unrounded
Button / 2. Secondary / Hover / Left rounded
Button / 2. Secondary / Hover / Right rounded
Button / 2. Secondary / Hover / Unrounded
Button / 2. Secondary / Action group

Button / 3. Tertiary / Default / Right rounded
Button / 3. Tertiary / Hover / Right rounded
Button / 3. Tertiary / Search icon
Button / 3. Tertiary / Question icon

**Icons:**
Icons / Object / dollar-sign
Icons / Object / at
Icons / Object / calendar-alt
Icons / Social / Google
Icons / Social / Github
Icons / Social / Gitlab
Icons / Social / Facebook
Icons / Social / Dropbox

**Dropdowns:**
Dropdowns / 3. Menu Item / Default checked
Dropdowns / Context Selector / Default
Dropdowns / Select / Text input / Chip options

Also noticed issue and updated Dropdowns / 4. Seperator / Default

[Patternfly 4 - Form inputs, drop downs, icons, buttons.zip](https://github.com/patternfly/patternfly-design-kit/files/3347305/Patternfly.4.-.Form.inputs.drop.downs.icons.buttons.zip)

**Comment by gdoyle1** [comment]
Merged!
