### ISSUE TITLE
Add disabled style for cards and tiles

### ISSUE THREAD

**Issue by doruskova** [patternfly/patternfly-design-kit#491]
Add disabled style for cards and use it in Tiles and show it as example in a template file.

**Comment by jhiadlov** [comment]
[style disabled state.zip](https://github.com/patternfly/patternfly-design-kit/files/7815410/style.disabled.state.zip)

**Comment by jhiadlov** [comment]
[disabled state style.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/7815466/disabled.state.style.sketch.zip)

**Comment by doruskova** [comment]
Now you can update disabled tiles in a template file directly

**Comment by doruskova** [comment]
Tiles updates - disabled state
