### ISSUE TITLE
Bell icon is the wrong blue (for default alerts)

### ISSUE THREAD

**Issue by mmenestr** [patternfly/patternfly-design-kit#492]
Looks like the bell icon is a lighter blue than it should be in the symbol library, and there is an issue with the default color naming 

What is is:
![image](https://user-images.githubusercontent.com/51165119/148579476-2e2440ac-dfbb-4605-95a9-9acb6915bf13.png)

What it should be:
![image](https://user-images.githubusercontent.com/51165119/148579489-5aa633e1-e36a-41ac-a8d8-ade7a6689c2e.png)

I think it's a problem with the color naming - looks like there are 2 pf-global-default-color-100, but the second one should be 200 instead, and should be applied to the status icon of the bell!
![image](https://user-images.githubusercontent.com/51165119/148579574-3bcbad44-5762-4c3b-a832-03c1513d3dbd.png)

**Comment by doruskova** [comment]
@mmenestr Great catch! Thank you! It should be fixed now.
