### ISSUE TITLE
Update user menu symbol in Masthead

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design-kit#495]
Last year we updated our guidance on the user menu in the masthead to swap the order of the dropdown and avatar. Looks like the Sketch library never got updated. You can see what the new configuration looks like here: https://www.patternfly.org/v4/components/navigation/react-demos/default-nav/ The avatar should come before the dropdown.

**Comment by doruskova** [comment]
@mcarrano Great catch! It's fixed now :)
