### ISSUE TITLE
Library update: data list (desktop & mobile)

### ISSUE THREAD

**Issue by beccaglass** [patternfly/patternfly-design-kit#50]
**Data list:**
Data List / Desktop / 1. Simple / Header (update)
Data List / Desktop / 1. Simple / Row / Line (update)
Data List / Desktop / 1. Simple / Row / No line (update)
Data List / Desktop / 2. Actionable / Checkbox
Data List / Desktop / 2. Actionable / Kebab
Data List / Desktop / 3. Expandable / Collapsed
Data List / Desktop / 3. Expandable / Expanded / 1. Row content
Data List / Desktop / 3. Expandable / Expanded / 2. Expanded content / 1. Padding
Data List / Desktop / 3. Expandable / Expanded / 2. Expanded content / 2. No padding

Data List / Mobile / 1. Simple / Header
Data List / Mobile / 1. Simple / Row / Default
Data List / Mobile / 1. Simple / Row / Last
Data List / Mobile / 2. Actionable / Checkbox / Default
Data List / Mobile / 2. Actionable / Checkbox / Last row
Data List / Mobile / 2. Actionable / Kebab / Default
Data List / Mobile / 2. Actionable / Kebab / Last row
Data List / Mobile / 3. Expandable / Collapsed
Data List / Mobile / 3. Expandable / Expanded / 1. Row content
Data List / Mobile / 3. Expandable / Expanded / 2. Expanded content / Default / 1. Padding
Data List / Mobile / 3. Expandable / Expanded / 2. Expanded content / Default /2. No padding
Data List / Mobile / 3. Expandable / Expanded / 2. Expanded content / Last row / 1. Padding
Data List / Mobile / 3. Expandable / Expanded / 2. Expanded content / Last row / 2. No padding

**Layer styles:**
Styles / Borders / pf-c-data-list__item-item--BorderTopWidth
Styles / Borders / pf-c-data-list__item-item--sm--BorderTopWidth
Styles / Borders / pf-c-data-list__expandable-content--Border
Styles / Borders / pf-c-data-list--BorderBottomColor
Styles / Borders / pf-c-data-list__item-item--BorderTopWidth2
Styles / Borders / pf-c-data-list__item-item--BorderTopWidth3
Styles / Borders / pf-c-data-list__item-item--BorderTopWidth4
Styles / Borders / pf-c-data-list__expandable-content--Border2

[data-list.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/3351584/data-list.sketch.zip)

**Comment by gdoyle1** [comment]
Merged!
