### ISSUE TITLE
Reconsider labels hierarchy in a library

### ISSUE THREAD

**Issue by doruskova** [patternfly/patternfly-design-kit#503]
Related to #496

**Comment by doruskova** [comment]
@jhiadlov I've updated the labels and created a new hierarchy for it. It's merged. I hope it makes sense. Could you check it? 
<img width="341" alt="Snímek obrazovky 2022-03-15 v 15 42 33" src="https://user-images.githubusercontent.com/32618096/158403098-9c7427f1-a0e6-40ee-95b1-0df8204edade.png">

**Comment by jhiadlov** [comment]
Oh, nice! I think you managed it very well!
