### ISSUE TITLE
Add Avatar sizes

### ISSUE THREAD

**Issue by doruskova** [patternfly/patternfly-design-kit#509]
https://github.com/patternfly/patternfly-design/issues/1076

--sm 24px
--md 36px
--lg 72px
--xl 128px

With md being the default.

**Comment by jhiadlov** [comment]
[avatar masthead.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/8206331/avatar.masthead.sketch.zip)

**Comment by jhiadlov** [comment]
Merged! 🎉
