### ISSUE TITLE
Library Update: Data Tables

### ISSUE THREAD

**Issue by mmenestr** [patternfly/patternfly-design-kit#51]
**Data Table**
Everything is new 
Also delete what was there previously

**Colors**
Borders / pf-c-data-table__expandable-content--Border

**Icons**
Icons / Framework / arrow-alt-v

**Dropdowns**
Dropdowns / 1. Toggle / Select / Read only

[Patterfly 4 - Data table.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/3352440/Patterfly.4.-.Data.table.sketch.zip)

**Comment by gdoyle1** [comment]
Merged!
