### ISSUE TITLE
Add Datepicker range date

### ISSUE THREAD

**Issue by doruskova** [patternfly/patternfly-design-kit#515]
https://www.patternfly.org/v4/components/date-picker/react-demos#date-range-picker

**Comment by doruskova** [comment]
@jhiadlov Any update?

**Comment by jhiadlov** [comment]
I was back in Slovakia, I returned just yesterday evening. I didn't have my laptop with me. Gonna work on it this week :)

**Comment by doruskova** [comment]
@jhiadlov Great! Thanks for reply :)

**Comment by jhiadlov** [comment]
[datepicker.zip](https://github.com/patternfly/patternfly-design-kit/files/8253718/datepicker.zip)
Here is the template for the datepicker :) I am just not sure with the border around clock icon (referring to what we talked during our call)

**Comment by doruskova** [comment]
@jhiadlov It's great! The border is correct because it's in a demo as well https://www.patternfly.org/v4/components/date-picker/react-demos

Can you merge it to a template file?

**Comment by jhiadlov** [comment]
Merged! 💎
