### ISSUE TITLE
Dropdowns (Figma)

### ISSUE THREAD

**Issue by doruskova** [patternfly/patternfly-design-kit#516]
Redesign dropdown components from a Dropdown page. Here's the tutorial on [how to redesign components in Figma. ](https://docs.google.com/document/d/1j9NLVx_oGRwHJRtQtS4tK7_uzjpnx8XTCtjzdN0vU-o/edit?usp=sharing)
<img width="880" alt="Snímek obrazovky 2022-03-03 v 11 11 55" src="https://user-images.githubusercontent.com/32618096/156543715-b03ec38e-78bb-42e4-9031-a384412182dc.png">

**Comment by blfetche** [comment]
Thanks again Marie for putting together our first meeting!

**Comment by blfetche** [comment]
Marie I would like to revisit these since I have a better understanding of how to apply variants.

**Comment by doruskova** [comment]
@blfetche Ok! I'll assign it to you :)

**Comment by doruskova** [comment]
@blfetche Thank you again!

**Comment by doruskova** [comment]
@blfetche Ok!
