### ISSUE TITLE
 [SKETCH TRAINING] links outdated

### ISSUE THREAD

**Issue by MariaLeonova** [patternfly/patternfly-design-kit#519]
Several links throughout the training are broken, including a few in the very last section.
Some of them include:
- PatternFly SVG library (https://github.com/patternfly/patternfly-design-kit/tree/master/Symbol-SVGs), 
- Contribute to PatternFly design (new or variant patterns) (https://www.patternfly.org/v4/contribute/designers),
- Finished page link is broken here in Instructions, 3 (https://patternflyt-training.thinkific.com/courses/take/pf-sketch-e-training/texts/12855815-try-it-in-sketch-part-one)

**Comment by doruskova** [comment]
@maryshak1996 The correct links for the first two points are: 
SVGs - https://github.com/patternfly/patternfly-design-kit/tree/master/Symbols-SVGs
PF Design - https://www.patternfly.org/v4/contribute/design
