### ISSUE TITLE
Add editable label group 

### ISSUE THREAD

**Issue by doruskova** [patternfly/patternfly-design-kit#524]
https://github.com/patternfly/patternfly-design/issues/1108#issuecomment-1080670585

Marvel mocks https://marvelapp.com/prototype/2d90c04g/screen/85343000

Sketch Cloud https://www.sketch.com/s/4cbddfc7-30e3-4b5a-bcde-8ff87b6910d3

Both scenarios are valid

**Comment by doruskova** [comment]
@jhiadlov updated description. Including the original sketch file.

**Comment by jhiadlov** [comment]
I am working on this :)

**Comment by jhiadlov** [comment]
Merged!
