### ISSUE TITLE
Add critical risk icon

### ISSUE THREAD

**Issue by doruskova** [patternfly/patternfly-design-kit#525]
https://github.com/patternfly/patternfly/issues/4747

**Comment by jhiadlov** [comment]
[critical-risk icon.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/8440738/critical-risk.icon.sketch.zip)
Hey. I made a critical risk icon for all sizes. I add it to the Framework section, but I am not sure if it should be there. Could you please check it? :)

**Comment by doruskova** [comment]
@jhiadlov I think it should be in a Status. :) Could you change it and merge it? Thank you!

**Comment by doruskova** [comment]
@jhiadlov Did you merge it? Can I close this issue?

**Comment by jhiadlov** [comment]
Merged!
