### ISSUE TITLE
Add switch with checkmark and label

### ISSUE THREAD

**Issue by doruskova** [patternfly/patternfly-design-kit#526]
https://github.com/patternfly/patternfly-design/issues/1137

**Comment by jhiadlov** [comment]
[switch andchceckmark.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/8451321/switch.andchceckmark.sketch.zip)
Could you please check it? :)

**Comment by doruskova** [comment]
Looks great! Could you add it to a library?

**Comment by jhiadlov** [comment]
Merged!
