### ISSUE TITLE
Add "back to top" component to library

### ISSUE THREAD

**Issue by mmenestr** [patternfly/patternfly-design-kit#528]
Need to add the [back to top ](https://www.patternfly.org/v4/components/back-to-top)component to the symbol library.
Yifat was looking to use it!

**Comment by doruskova** [comment]
It's already in a library under Buttons :) 
https://www.sketch.com/s/2cf1063b-5283-4e0b-b8a6-cbb1ac07e29e/a/nRZRkdp
