### ISSUE TITLE
Review and fix labels component

### ISSUE THREAD

**Issue by doruskova** [patternfly/patternfly-design-kit#531]
**Is the text using the text style from the library?**

- [ ]  Is the text using a fill as a color style?
- [ ] Check the usability of the component

**Use the component from the Assets view (left panel, second tab)**

- [ ] Try to type some text in it and resize it
- [ ] See what's wrong, for example, the background is not resizing correctly or some part has completely changed its position.
- [ ] Fix these issues

**Check if anything is missing from Sketch**
Is there any component that is missing? If so, please describe what's missing here :) If it's a small issue 

**Add PF documentation link**
When you hover over the component in a library > you can get a short description and doc link. Please, add a short description of the Design Guidelines and a PF documentation link to the implementation.
<img width="993" alt="163385326-7a0bf06c-4e30-4166-bc55-488aef3ee9f2" src="https://user-images.githubusercontent.com/32618096/163951564-885fedbd-3d71-446f-b596-1f49900c20d6.png">

**Create variant with properties and values**

1. Does the component need variants? If so, please read this doc first https://help.figma.com/hc/en-us/articles/360056440594-Create-and-use-variants
3. Great working examples are Alerts and Buttons components in a library. 
4. Best practice: Create variants from components that have common values. It's better to group together components that have similar states and behavior. The goal is to choose a component from the library and then customize it via properties. We don't want to have thousands of components shown in a library. However, not every component is easy for more complex variants with a lot of properties. Then, it's fine to create variants that differentiate only the state (default, hover, etc.)  of one specific component. ![Snímek obrazovky 2022-04-06 v 17 02 03](https://user-images.githubusercontent.com/32618096/162005765-744bf541-2c9b-46e0-949c-9bb600fcb31a.png)

The disadvantage of simple variants = more components in a library.
A disadvantage of the complex variants is that only 1 component is visible in a list of components and other components are hidden as property values. 

In this case, I would like to see more complex variants because we can differentiate size (default, compact), state (default, hover), and type (editable, default) 
@blfetche

**Comment by blfetche** [comment]
This sounds great Marie thanks for sharing. I think there is pro and con to both, I generally try to look at things as state vs variant. A variant is a completely different version whereas a state is a child to a variant. Options within a variant.

**Comment by doruskova** [comment]
Yeah, I totally agree. I assigned this issue to you because you mentioned last time you want labels :) I hope I remember it correctly.

**Comment by doruskova** [comment]
Done!
