### ISSUE TITLE
Reconsider approach to scrolling horizontal tabs on mobile

### ISSUE THREAD

**Issue by doruskova** [patternfly/patternfly-design-kit#535]
https://github.com/patternfly/patternfly-design/issues/1034

Follow the implementation :)) 

https://patternfly-react-pr-7742.surge.sh/components/tabs/#horizontal-overflow

**Comment by jhiadlov** [comment]
I made new symbols and already used them in the template (page Tabs / horizontal overflow) and it is merged. Can you please check it? :) Thank you

**Comment by doruskova** [comment]
Yes! It looks good! :))
