### ISSUE TITLE
Library Update: Cards (In Progress) 

### ISSUE THREAD

**Issue by lboehling** [patternfly/patternfly-design-kit#54]
Compact & Standard Card symbols mostly finished. Still need to standardize layer names & test responsiveness. 
[patternfly-4-cards-inprogress.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/3356883/patternfly-4-cards-inprogress.sketch.zip)

**Comment by lboehling** [comment]
*Update* 

Compact and Standard Card symbols added to Cards page: 
[patternfly-4-cards.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/3369988/patternfly-4-cards.sketch.zip)

Card / Compact Card / 1. Background / Default
Card / Compact Card / 1. Background / Hover

Card / Compact Card / 2. Header / Title Only
Card / Compact Card / 2. Header / Actions / Checked
Card / Compact Card / 2. Header / Actions / Unchecked
Card / Compact Card / 2. Header / Actions / No Title
Card / Compact Card / 2. Header / With Image
Card / Compact Card / 2. Header / With Image / Actions / Checked
Card / Compact Card / 2. Header / With Image / Actions / Unchecked

Card / Compact Card / 3. Content / No Header
Card / Compact Card / 3. Content / No header or footer
Card / Compact Card / 3. Content / No footer
Card / Compact Card / 3. Content / Body

Card / Compact Card / 4. Footer
_____________

Card / Standard Card / 1. Background / Default
Card / Standard Card / 1. Background / Hover

Card / Standard Card / 2. Header / Title Only
Card / Standard Card / 2. Header / Actions / Checked
Card / Standard Card / 2. Header / Actions / Unchecked
Card / Standard Card / 2. Header / Actions / No Title
Card / Standard Card / 2. Header / With Image
Card / Standard Card / 2. Header / With Image / Actions / Checked
Card / Standard Card / 2. Header / With Image / Actions / Unchecked

Card / Standard Card / 3. Content / No Header
Card / Standard Card / 3. Content / No header or footer
Card / Standard Card / 3. Content / No footer
Card / Standard Card / 3. Content / Body

Card / Standard Card / 4. Footer


@gdoyle1

**Comment by gdoyle1** [comment]
Merged
