### ISSUE TITLE
Date picker - Fix icons used to toggle the month

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly-design-kit#547]
We noticed that the icons used in the calendar for date picker are incorrect. The [original design here](https://docs.google.com/document/d/1hlS0R1l7gnoe-YDu1SEHpUSrf6WMuZPejR5AwYr0a20/edit) uses the left and right caret icons and not the arrows. See https://github.com/patternfly/patternfly/pull/4862 for more discussion.

**Comment by doruskova** [comment]
@mcarrano I followed React implementation when I was creating datepicker component. I used arrows in the Sketch library. I guess it's correct. I didn't follow the HTML design. Let me know if it's ok :) 
<img width="354" alt="Snímek obrazovky 2022-05-25 v 14 36 20" src="https://user-images.githubusercontent.com/32618096/170263473-6aa1cced-4b86-4a84-9372-87a548442296.png">

**Comment by mcarrano** [comment]
@doruskova I understand. But somewhere along the way, the React implementation deviated from the original design and we want to go back to using the left/right carets as done in the core implementation. I've opened an issue to make these updates in the React repo also. Thanks.

**Comment by doruskova** [comment]
@mcarrano Oooh, got it. I'll update them :))

**Comment by doruskova** [comment]
@mcarrano Merged!
