### ISSUE TITLE
Create demo to show how alerts can be used in forms and modals

### ISSUE THREAD

**Issue by doruskova** [patternfly/patternfly-design-kit#549]
https://github.com/patternfly/patternfly-design/issues/1125

**Comment by doruskova** [comment]
@jhiadlov Any update?

**Comment by jhiadlov** [comment]
Work in progress. Hopefully tomorrow it will be done.

**Comment by jhiadlov** [comment]
[alerts in modal and form.zip](https://github.com/patternfly/patternfly-design-kit/files/9190004/alerts.in.modal.and.form.zip)
Is it okay like this? Or should I change anything :)

**Comment by doruskova** [comment]
@jhiadlov It's absolutely fine :))

**Comment by jhiadlov** [comment]
Merged!
