### ISSUE TITLE
Template Addition: Login

### ISSUE THREAD

**Issue by mmenestr** [patternfly/patternfly-design-kit#55]
**Added every login panel:**

Login / Desktop / Simple
Login / Tablet / Simple
Login / Mobile / Simple
Login / Desktop / Invalid
Login / Tablet / Invalid
Login / Mobile / Invalid

[PF4template - Log in.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/3363266/PF4template.-.Log.in.sketch.zip)

**Comment by gdoyle1** [comment]
Merged!
