### ISSUE TITLE
Create cards example

### ISSUE THREAD

**Issue by doruskova** [patternfly/patternfly-design-kit#551]
Recreate these two screens with cards to Figma. Show default, hover, and disabled state. You don't have to use the logos :)

https://www.sketch.com/s/729c2eee-e8b6-4fcd-8a79-f6faa8c30f89/a/v8ZLkp3
https://www.sketch.com/s/729c2eee-e8b6-4fcd-8a79-f6faa8c30f89/a/q3v1m2#Comment
<img width="1499" alt="Snímek obrazovky 2022-06-06 v 10 34 28" src="https://user-images.githubusercontent.com/32618096/172125882-ea18c847-4f38-4e98-9fc0-65968ef092dd.png">
<img width="1178" alt="Snímek obrazovky 2022-06-06 v 10 33 57" src="https://user-images.githubusercontent.com/32618096/172125899-d94d2e54-647e-4161-88b4-d281d2703954.png">

- Open Figma library(https://www.figma.com/file/NzoWmhVQEROziYQDCx3QFQ/PatternFly?node-id=0%3A1935)
- Create a new file in Figma
- Create a new frame with 1500x1024
- Copy the component you need (e.g. card) 
- Paste the component to your file
- Try to type some text to make sure that everything resizes correctly. If not, fix it please (usually with auto-layout) or ping me on Slack and I'll explain to you what to do. 
- Once you finish it > Send me the file here and I'll review it 
- Then we can merge it here [(to Sim's file) ](https://www.figma.com/file/DilMaDNOZeLpyjGtsjhmrx/PatternFly---Demos?node-id=0%3A1)

- Note: it's possible that text styles will not be imported because the library can't be published right now. So, just use the same styling for text. I do recommend to create the frame in a library because everything is available there. Then you can copy and paste it to your file.
- If you don't know the name of used components > let me know or take a look here https://www.patternfly.org/v4/components/

Useful links: 
[What is auto-layout? ](https://help.figma.com/hc/en-us/articles/360040451373-Explore-auto-layout-properties)

**Comment by smckinno** [comment]
https://www.figma.com/file/1znHadOtZkHEkhuwR9fFIT/Card-examples?node-id=0%3A1

**Comment by doruskova** [comment]
@smckinno I left some comments. But, it looks great!
