### ISSUE TITLE
Create dashboard in Figma

### ISSUE THREAD

**Issue by doruskova** [patternfly/patternfly-design-kit#552]

**Comment by doruskova** [comment]
@kuklas Any update?

**Comment by doruskova** [comment]
@kuklas Any updates?

**Comment by kuklas** [comment]
no updates yet, will update soon

**Comment by doruskova** [comment]
@kuklas Do you have any update?

**Comment by kuklas** [comment]
Finishing prototype in PatternFly - Demos file
[This is how the animation works](https://www.figma.com/proto/DilMaDNOZeLpyjGtsjhmrx/PatternFly---Demos?page-id=0%3A1&node-id=188%3A7708&viewport=1458%2C-927%2C0.21&scaling=min-zoom&starting-point-node-id=188%3A7708&show-proto-sidebar=1)
+ will add a few more tiles and see how it all works together

**Comment by kuklas** [comment]
Done! @doruskova
