### ISSUE TITLE
Library update: few fixed errors

### ISSUE THREAD

**Issue by mmenestr** [patternfly/patternfly-design-kit#56]
**Masthead**
_Fixed two pinning issues with the icon (size was not fixed)_
Masthead / Assets / Avatar
Masthead / User Info / Avatar

**Navigation**
Navigation / Tertiary Nav / Background

**Tables**
_Corrected minute errors in background styles_
Data Table / Desktop / Expandable / Row / Collapsed
Data Table / Desktop / Expandable / Compact / Row / Collapsed
Data Table / Desktop / Expandable / Row / Expanded
Data Table / Desktop / Expandable / Compact / Row / Expanded

[Patternfly 4 few updates.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/3374751/Patternfly.4.few.updates.sketch.zip)

**Comment by gdoyle1** [comment]
Merged!
