### ISSUE TITLE
Responsive behavior for vertical tabs

### ISSUE THREAD

**Issue by doruskova** [patternfly/patternfly-design-kit#561]
Responsive behavior for vertical tabs[#1165](https://github.com/patternfly/patternfly-design/issues/1165)

**Comment by doruskova** [comment]
@jhiadlov Any update?

**Comment by jhiadlov** [comment]
Work in progress. Hopefully tomorrow it will be done.

**Comment by doruskova** [comment]
@jhiadlov Yes. But, did you update the sketch library and template file?

**Comment by jhiadlov** [comment]
Updated! :)
