### ISSUE TITLE
Update vertical tabs - mobile behavior

### ISSUE THREAD

**Issue by doruskova** [patternfly/patternfly-design-kit#562]
@jhiadlov Take a look at this issue again https://github.com/patternfly/patternfly-design/issues/1165 
Your mocks are a little bit different from the implementation. There is no dropdown there.

**Comment by doruskova** [comment]
@jhiadlov Any update?

**Comment by jhiadlov** [comment]
I updated the mockup. Now it should look like the implementation. I just didn't change the background to a grey color. Is it okay like this?
https://marvelapp.com/prototype/dj6cag1/screen/87992357

**Comment by doruskova** [comment]
@jhiadlov Yes, it should be good to go. :))

**Comment by doruskova** [comment]
@jhiadlov Did you merge it?

**Comment by jhiadlov** [comment]
yes, it is merged
