### ISSUE TITLE
Add new toggle button

### ISSUE THREAD

**Issue by doruskova** [patternfly/patternfly-design-kit#567]
https://github.com/patternfly/patternfly-design/issues/1173

Add toggle button with badge

**Comment by jhiadlov** [comment]
<img width="408" alt="Screenshot 2022-08-17 at 10 19 36" src="https://user-images.githubusercontent.com/78600774/185070264-c10d7ead-16b3-4dc8-936a-90450fe5db64.png">
It is done and merged. Here is the screenshot how does it look like and how I named it. Is it okay? :)

**Comment by doruskova** [comment]
@jhiadlov yes, it is ok
