### ISSUE TITLE
Library addition: Data tables

### ISSUE THREAD

**Issue by mmenestr** [patternfly/patternfly-design-kit#57]
**Data table**
Just literally copy pasted the entire Data table page! :)

**Colors**
pf-c-data-table--responsive--BorderColor-top
pf-c-data-table__expandable-row--Border
pf-c-data-table__expandable-middlerow--Border

**Masthead**
Fixed two pinning issues with the icon (size was not fixed)
Masthead / Assets / Avatar
Masthead / User Info / Avatar

**Navigation**
Navigation / Tertiary Nav / Background

**Icon**
_Took an icon out of a folder so that the color could be editable_
Icons / Framework / arrows-alt-v

[Patternfly 4 Data table updates.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/3379394/Patternfly.4.Data.table.updates.sketch.zip)

**Comment by gdoyle1** [comment]
merged!
