### ISSUE TITLE
Template addition: Many pages

### ISSUE THREAD

**Issue by mmenestr** [patternfly/patternfly-design-kit#58]
**Input groups**
Updated Input group 4 and added update date

**Login**
Updated ALL login pages so just copy everything over

**Tables**
Copy whole page over

**Forms**
Copy whole page over

**Modal**
Copy whole page over

[Patternflt 4 Template updates (7:10:19).sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/3379413/Patternflt.4.Template.updates.7.10.19.sketch.zip)

**Comment by gdoyle1** [comment]
merged!
