### ISSUE TITLE
Library addition: More data table stuff

### ISSUE THREAD

**Issue by mmenestr** [patternfly/patternfly-design-kit#59]
**Data Table**
Fixed shadow issue problem and removed text I forgot to hide
Data Table / Desktop / Expandable / Row / Panel 128px padding
Data Table / Desktop / Expandable / Row / Panel 24px padding
Data Table / Desktop / Expandable / Row / Panel 0 padding

Data Table / Mobile /  Expandable / Content 24px padding
Data Table / Mobile /  Expandable / Content 0 padding
Data Table / Mobile /  Expandable / Row / Collapsed Icon

Data Table / Mobile /  Simple / Row / Bottom
Data Table / Mobile /  Simple / Row / Last

Data Table / Mobile / Compact / Row / Top
Data Table / Mobile / Compact / Row / Middle
Data Table / Mobile / Compact / Row / Bottom
Data Table / Mobile / Compact / Row / Last

***** Maybe just copy over the whole page bc that's probably way easier ****

**Colors**
pf-c-table_expandable-row--m-expanded--BoxShadow

[Patternfly 4 - More data table stuff.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/3383867/Patternfly.4.-.More.data.table.stuff.sketch.zip)

**Comment by gdoyle1** [comment]
Merged! I changed all data table symbols and layer styles to be called table as well
