### ISSUE TITLE
Update Sketch File - Add open-drawer-right icon to the library

### ISSUE THREAD

**Issue by lboehling** [patternfly/patternfly-design-kit#592]
Add open-drawer-right icon to the library [#1149](https://github.com/patternfly/patternfly-design/issues/1149)

Category: Actions

**Comment by jhiadlov** [comment]
Icon added to "Action" category :) It is merged.

**Comment by lboehling** [comment]
thank you @jhiadlov ! I renamed to "open-drawer-right" so that it matches the icon name on the site/repo!
