### ISSUE TITLE
Update Sketch Library - Fix resizing of chart symbols 

### ISSUE THREAD

**Issue by lboehling** [patternfly/patternfly-design-kit#594]
Our chart axis symbols do not resize properly. We need to update the following symbols to resize properly:

Charts/Axis/Full No Lines
Charts/Axis/Full with Horizontal Lines
Charts/Axis/Full with Vertical Lines
Charts/Axis/X-axis
Charts/Axis/Y-axis
Charts/Area/Full
Charts/Sparkline/Full

**Comment by jhiadlov** [comment]
All of those components should be fixed right now. I have only one problem: Between the first tick and second tick and also between the last and second last tick, there is always a bigger gap (both horizontal and vertical). I tried everything I could to fix it, but nothing worked for me. Can it be like this, or will you please look at it? Maybe, you will figure something out 😅

Thank you.

Here is an image, where I highlighted the bigger gaps.
<img width="716" alt="Screenshot 2022-11-07 at 11 24 38" src="https://user-images.githubusercontent.com/78600774/200274454-d4aa509f-56a9-459b-ab3d-15d63e2bea56.png">

**Comment by lboehling** [comment]
Thank you @jhiadlov! I'll take a look :)

**Comment by lboehling** [comment]
I think this is good for now, I can't get those to resize perfectly either. thank you for your work on this!!
