### ISSUE TITLE
Add timepicker component to symbol library

### ISSUE THREAD

**Issue by lboehling** [patternfly/patternfly-design-kit#596]
Timepicker symbol is missing from our library https://www.patternfly.org/v4/components/time-picker

**Comment by jhiadlov** [comment]
Done and merged :)

**Comment by lboehling** [comment]
Thank you @jhiadlov! Looks great! Should we add the error state (shown in the design guidelines https://www.patternfly.org/v4/components/time-picker/design-guidelines#error-messages) to the symbol?

**Comment by jhiadlov** [comment]
I add the Error and Focus states, and also fixed the Active state. But with the Error state, I also added the bottom part with Error text. Should I keep it like this?

**Comment by lboehling** [comment]
Yep, I think it looks good! Thank you! @jhiadlov
