### ISSUE TITLE
Fix text input with icon symbols

### ISSUE THREAD

**Issue by lboehling** [patternfly/patternfly-design-kit#598]
Seems like there are inconsistencies between the states for the forms/text box/with icon symbols. 
Looks like the default component may be showing an [input group](https://www.patternfly.org/v4/components/input-group) and not a [text box with icon](https://www.patternfly.org/v4/components/text-input#icon-variants). The other states appear to show a search input with the icon on the left.  

After review it looks like the forms/text box/with icon symbols should show the icon on the right (shown [here](https://www.patternfly.org/v4/components/text-input#icon-variants)) and allow for icon overrides. Default icon should be changed so it is not confused with search input symbol.

**Comment by jhiadlov** [comment]
Work in progress

**Comment by lboehling** [comment]
as part of this work, we should make sure that these symbols allow for text overrides

from pf design slack:

> hello! I just downloaded the latest sketch symbol library and found some minor issues with the text box with icon forms components. The issue is that they don't allow override for the text in the text box. The other types of text boxes do allow override though.

**Comment by jhiadlov** [comment]
It is fixed :)

**Comment by lboehling** [comment]
Thanks @jhiadlov! I also updated the icon to use the key icon as a more generic custom icon. I still need to check on proper error icon placement before closing this one out :)
