### ISSUE TITLE
Add compact label group and update label group border

### ISSUE THREAD

**Issue by lboehling** [patternfly/patternfly-design-kit#606]
- Add new compact variation for label group and update all label group borders. 

> See here for implementation issue/design specs: https://github.com/patternfly/patternfly/issues/5344

**Comment by jhiadlov** [comment]
Done and merged.

**Comment by lboehling** [comment]
reopening so this gets added and updated in the figma v5 kit

**Comment by cshinn** [comment]
Compact label group is created and border color has been updated for both components
