### ISSUE TITLE
Bug - Dropdown with number

### ISSUE THREAD

**Issue by JustinXHale** [patternfly/patternfly-design-kit#610]
**Describe the problem**
When using dropdown menu with numbers and a bulk change is made to use menu without numbers, the text is replaced with the number. The same for when the process is done in reverse.

**Expected behavior**

- If I remove numbers from a menu item, I expect to keep the menu name.
- If I add numbers, I expect the text to stay the same

**Screenshots**
Menu Item
<img width="1045" alt="image" src="https://user-images.githubusercontent.com/91554933/220396320-2d8c6c69-9688-4fa1-8026-3399b66522f7.png">

After changing to _with number_ the text becomes the number.
<img width="1030" alt="image" src="https://user-images.githubusercontent.com/91554933/220396383-c1693934-c361-4405-a96e-ec3bc6bcc8f6.png">

Starting with Numbers in place
<img width="1030" alt="image" src="https://user-images.githubusercontent.com/91554933/220396872-0d84f718-ccec-4012-b17d-08acd83810eb.png">

When changed to without numbers (default) numbers take place of text
<img width="1020" alt="image" src="https://user-images.githubusercontent.com/91554933/220397033-cd0d1306-71a6-4287-94fc-0139b70adfa4.png">

**Any other information?**

**Comment by jhiadlov** [comment]
I think it was some kind of a bug. I deleted the component and created it once again. Now it should be working. :) It is merged.

**Comment by lboehling** [comment]
thanks @jhiadlov! @JustinXHale let us know if this fixed the problem for you!
