### ISSUE TITLE
Energy changes alignment

### ISSUE THREAD

**Issue by JustinXHale** [patternfly/patternfly-design-kit#616]
When specifically using the checkbox with number component. Whenever the word "Energy" is in the  name field the alignment changes. 

![Energy bug](https://github.com/patternfly/patternfly-design-kit/assets/91554933/85017de7-7da2-4a1e-aaff-3ce2ca1db695)

**Comment by lboehling** [comment]
Hmm i think this must be a bug in sketch, not with the pf library. I would try resetting the symbol overrides and trying again, and then changing the text in the overrides panel and not directly on the canvas. I was able to get them all to resize correctly this way. Let me know if you keep having this problem! @JustinXHale

**Comment by JustinXHale** [comment]
@lboehling everything looks to be working fine now. I thought this was weird. Before I sent the bug I tried deleting the component, as well as, duplicating another component to see if it made a difference.
