### ISSUE TITLE
No option to select checkbox

### ISSUE THREAD

**Issue by JustinXHale** [patternfly/patternfly-design-kit#617]
There is no option to have selected checkbox when using checkbox with numbers

<img width="994" alt="image" src="https://github.com/patternfly/patternfly-design-kit/assets/91554933/8738cc9f-dce8-434d-a206-fee64a7f501e">

![No option to check with dropdowns with numbers](https://github.com/patternfly/patternfly-design-kit/assets/91554933/fd7d7e42-359a-49bb-b94c-8422417adacc)

**Comment by lboehling** [comment]
I'll take a look at this and make sure that override is enabled. thanks for catching this @JustinXHale

**Comment by lboehling** [comment]
Fixed! thanks for catching this @JustinXHale!
