### ISSUE TITLE
Update icon layer styles for nonactionable and actionable icon colors 

### ISSUE THREAD

**Issue by lboehling** [patternfly/patternfly-design-kit#621]
reference issue [https://github.com/patternfly/patternfly-design/issues/1195](https://www.google.com/url?q=https://github.com/patternfly/patternfly-design/issues/1195&sa=D&source=docs&ust=1689798664813018&usg=AOvVaw0le_nUW1xNkPZtKAphSTdv)

**Comment by cshinn** [comment]
Icon colors for relevant components have been updated per the comments on the attached issue
