### ISSUE TITLE
Accordion and expandable sections

### ISSUE THREAD

**Issue by andrew-ronaldson** [patternfly/patternfly-design-kit#639]
### Accordion
- [x] Does the background color work well for the component?
- [x] Does it scale correctly?
- [x] Are there any variant errors?
- [x] Do the properties behave correctly?
- [x] Have text properties been created?
- [x] Do the properties make sense?
- [x] Are the min/max height and width set when it makes sense?

### Expandable Sections
- [x] Does the background color work well for the component?
- [x] Does it scale correctly?
- [ ] Are there any variant errors?
- [ ] Do the properties behave correctly?
- [ ] Have text properties been created?
- [ ] Do the properties make sense?
- [ ] Are the min/max height and width set when it makes sense?

**Comment by cshinn** [comment]
Fixed a resizing issue for the caret on expanded sections and added min-height property to all variants

**Comment by cshinn** [comment]
The "call to action" on the large expanded version is acting weird, but I suspect that's an error with the button component. Will update here once I check those
