### ISSUE TITLE
Template Update: Accordion, Alert Groups, Chip Groups

### ISSUE THREAD

**Issue by lboehling** [patternfly/patternfly-design-kit#64]
Added Accordion Page (Collapsed, Expanded, Fixed Scroll, and Fluid)

[patternfly-4-template-Accordion.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/3402644/patternfly-4-template-Accordion.sketch.zip)

**Comment by lboehling** [comment]
also added in alert groups and chip groups, along with the accordion. all new pages in this file: 

[patternfly-4-template-accordion, alert group, chip group.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/3403534/patternfly-4-template-accordion.alert.group.chip.group.sketch.zip)

**Comment by gdoyle1** [comment]
merged these!
