### ISSUE TITLE
Cards (add tile variant)

### ISSUE THREAD

**Issue by andrew-ronaldson** [patternfly/patternfly-design-kit#641]
The tile component is being deprecated in v5 so the Card component needs to include a tile variant

- [x] Does the background color work well for the component?
- [x] Does it scale correctly?
- [x] Are there any variant errors?
- [x] Do the properties behave correctly?
- [x] Have text properties been created?
- [x] Do the properties make sense?
- [x] Are the min/max height and width set when it makes sense?

**Comment by JustinXHale** [comment]
I cant assign myself

**Comment by JustinXHale** [comment]
I've updated Cards and Tile not sure if they should be combined
