### ISSUE TITLE
Menu, menu toggle, dropdown, select, Application launcher, options menu

### ISSUE THREAD

**Issue by andrew-ronaldson** [patternfly/patternfly-design-kit#646]
- [x] Does the background color work well for the component?
- [x] Does it scale correctly?
- [x] Are there any variant errors?
- [x] Do the properties behave correctly?
- [x] Have text properties been created?
- [x] Do the properties make sense?
- [x] Are the min/max height and width set when it makes sense?

**Comment by JustinXHale** [comment]
Just a note to break this down and find components 

- Menu - https://www.patternfly.org/components/menus/menu
- Dropdown - https://www.patternfly.org/components/menus/dropdown
- Select - https://www.patternfly.org/components/menus/select
- Application launcher - https://www.patternfly.org/components/menus/application-launcher
- Options Menu - https://www.patternfly.org/components/menus/options-menu
