### ISSUE TITLE
Toolbar, action list

### ISSUE THREAD

**Issue by andrew-ronaldson** [patternfly/patternfly-design-kit#654]
- [x] Does the background color work well for the component?
- [x] Does it scale correctly?
- [x] Are there any variant errors?
- [x] Do the properties behave correctly?
- [x] Have text properties been created?
- [x] Do the properties make sense?
- [x] Are the min/max height and width set when it makes sense?

**Comment by JustinXHale** [comment]
what is action list?

**Comment by JustinXHale** [comment]
Within the toolbar component in figma, it shows pagination, however there is no pagination component page. Is pagination moving into toolbar?
