### ISSUE TITLE
Template update: data list

### ISSUE THREAD

**Issue by beccaglass** [patternfly/patternfly-design-kit#67]
Simple data list
Actionable data list
Expandable data list
Data list / Desktop / Simple demo
Data list / Desktop / Actionable demo
Data list / Desktop / Expandable demo
Data list / Mobile / Simple demo
Data list / Mobile / Actionable demo
Data list / Mobile / Expandable demo

[dataList.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/3417927/dataList.sketch.zip)

**Comment by beccaglass** [comment]
Updated file attached!

[dataList.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/3423163/dataList.sketch.zip)

**Comment by gdoyle1** [comment]
merged! thanks for your changes :)
