### ISSUE TITLE
Penta: Simple list, data list, description list

### ISSUE THREAD

**Issue by andrew-ronaldson** [patternfly/patternfly-design-kit#670]
- [ ] [Simple list](https://www.patternfly.org/components/simple-list)
- [x] [Data list](https://www.patternfly.org/components/data-list)
- [x] [Description list](https://www.patternfly.org/components/description-list)

**Comment by lboehling** [comment]
description list is done already

**Comment by smckinno** [comment]
@andrew-ronaldson  it seems like the description list is completed and Lucia told me not to worry about the data list so I guess that means I'm just responsible for the simple list? If so I just finished it and it needs review. Thanks!

**Comment by lboehling** [comment]
data list merged!
