### ISSUE TITLE
Penta: Avatar, brand, background image, backdrop, divider, truncate

### ISSUE THREAD

**Issue by andrew-ronaldson** [patternfly/patternfly-design-kit#672]
- [x] [Avatar](https://www.patternfly.org/components/avatar)
- [x] [Brand](https://www.patternfly.org/components/brand)
- [x] [Background image](https://www.patternfly.org/components/background-image)
- [x] [Backdrop](https://www.patternfly.org/components/backdrop)
- [x] [Divider](https://www.patternfly.org/components/divider)
- [ ] [Truncate](https://www.patternfly.org/components/truncate)

**Comment by lboehling** [comment]
created avatar/brand as part of masthead component work

**Comment by blfetche** [comment]
@lboehling in the Menu Toggle there is an avatar option can we link up to discuss? Thank.

**Comment by lboehling** [comment]
does truncate need a specific figma component? not sure how that would be presented. i could add with a string of text, but i don't think it would really be used in designs? we don't have it in the current sketch kit fwiw.
