### ISSUE TITLE
Symbol Library Update: Cards

### ISSUE THREAD

**Issue by lboehling** [patternfly/patternfly-design-kit#68]
Updated Card symbols (edited padding, and swapped icon for actual image).

[patternfly-Card Updates.sketch 2.zip](https://github.com/patternfly/patternfly-design-kit/files/3423432/patternfly-Card.Updates.sketch.2.zip)

**Comment by gdoyle1** [comment]
@lboehling Checking this out now - where is the semibold treatment coming from?
