### ISSUE TITLE
Symbol library update: New default alerts design

### ISSUE THREAD

**Issue by mmenestr** [patternfly/patternfly-design-kit#69]
**Alerts**
_Added new "default" alerts_
8 in total, default and inline default, dismissible, with description, and with action buttons

**Colors**
_Added_
1. Theme / Status / pf-global--default-color—100
1. Theme / Status / pf-global--default-color--200
1. Theme / Status / pf-global--default-color—300

**** those are automatically renumbering when I post this comment but they all start with 1. 

**Typography**
_Added_
Status / pf-global—default-color—100
Status / pf-global—default-color—200

**Icon**
_Edited_
Icons/ Object / bell

[Patternfly 4 Default Alerts.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/3424099/Patternfly.4.Default.Alerts.sketch.zip)

**Comment by gdoyle1** [comment]
merged!
