### ISSUE TITLE
Penta: Log viewer

### ISSUE THREAD

**Issue by andrew-ronaldson** [patternfly/patternfly-design-kit#699]

**Comment by kaylachumley** [comment]
Done -- the branch has been archived and moved to the main extensions file @andrew-ronaldson @lboehling

**Comment by andrew-ronaldson** [comment]
Closed design https://www.figma.com/file/MSr6kVEOuAxmPOkjg7x8PO/Penta-Patterns-%26-Extensions?type=design&node-id=1%3A7&mode=design&t=G1oTuLMs31fUkmNa-1
