### ISSUE TITLE
Template library update: 4 pages

### ISSUE THREAD

**Issue by mmenestr** [patternfly/patternfly-design-kit#70]
**Login:**
_Added_
Login / Mobile / Expanded Simple
Login / Mobile / Expanded Invalid

**Wizard:**
Edited or added all of them

**Tables**
Edited all of them (padding things)

**About modal**
Added everything

[patternfly-4-template.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/3433186/patternfly-4-template.sketch.zip)

**Comment by gdoyle1** [comment]
merged!
