### ISSUE TITLE
PF Chatbot extension

### ISSUE THREAD

**Issue by andrew-ronaldson** [patternfly/patternfly-design-kit#703]
Based on the original [designs](https://www.figma.com/design/YV8fXr4jjEjUqhvRzI0tT2/PatternFly%3A-Chatbot-Design-Framework?t=UvubcJeimzN9CrNP-0) done for lightspeed projects we need to add tokenize the chatbot interface and add it to the PF extension library.

**Comment by kaylachumley** [comment]
Closing this out! Branch has been merged into main extension file
