### ISSUE TITLE
v6 Onboarding documentation

### ISSUE THREAD

**Issue by andrew-ronaldson** [patternfly/patternfly-design-kit#706]
## Goal
Prepare an onboarding document to enable Designers can consume the Penta Figma kit.
Provide component examples and highlight how variables are used to switch between component types.
Guidance on how to file an issue with the library or a new feature.

**Follow up**
Post finished doc on the [Design getting started](https://www.patternfly.org/get-started/design) page.

**Comment by lboehling** [comment]
can probably also share the finished doc on the patternfly community page on figma!

**Comment by kaylachumley** [comment]
I put [this document](https://docs.google.com/document/d/1x30bBejQ0QtTjsMmtxYRkHKYTIwryaagUsk-ep7QTfQ/edit?usp=sharing) together to start generating ideas. Feel free to add anything and let me know your feedback. @lboehling @andrew-ronaldson

**Comment by andrew-ronaldson** [comment]
Marking as closed with Alpha docs available. Will create follow up issues for training modules
