### ISSUE TITLE
Penta: Create field groups

### ISSUE THREAD

**Issue by andrew-ronaldson** [patternfly/patternfly-design-kit#708]
## Goal
Add the [Field group](https://staging-v6.patternfly.org/components/forms/form#field-groups) component to the Form sections of the Figma kit.

### Field group requirements
- [ ] Expand/collapse field groups
- [ ] No expansion field groups
- [ ] Nested version (trash can)

![Screenshot 2024-02-05 at 4 25 33 PM](https://github.com/patternfly/patternfly-design-kit/assets/28658548/5ad98d4a-f14a-4029-ad12-42e7aeee3325)

**Comment by kaylachumley** [comment]
Done! Reviewed by Lucia
