### ISSUE TITLE
Template Update: Card View

### ISSUE THREAD

**Issue by lboehling** [patternfly/patternfly-design-kit#71]
Updated Card View desktop demo/added in mobile version. Also added in desktop and mobile versions of basic cards on a page. 

[patternfly-4-template-cardview-update 7:26.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/3437425/patternfly-4-template-cardview-update.7.26.sketch.zip)

**Comment by gdoyle1** [comment]
merged!
