### ISSUE TITLE
Accordion: Add left align variants

### ISSUE THREAD

**Issue by andrew-ronaldson** [patternfly/patternfly-design-kit#710]
Follow up to this [Core issue](https://github.com/patternfly/patternfly/issues/5426#issuecomment-1970042783).

Need to add a left aligned caret to our Accordions as an additional variant. This is required for both v5 and v6 kits

```[tasklist]
### To do list
- [x] V5 Figma kit Accordion change
- [ ] V6 Figma kit Accordion change
```

**Comment by andrew-ronaldson** [comment]
FYI @cshinn and @kaylachumley

**Comment by cshinn** [comment]
PF5 update made and published

**Comment by andrew-ronaldson** [comment]
Thanks, @cshinn!

**Comment by andrew-ronaldson** [comment]
Branch done in Penta kit.
