### ISSUE TITLE
Patterns: Filters

### ISSUE THREAD

**Issue by andrew-ronaldson** [patternfly/patternfly-design-kit#714]
https://www.patternfly.org/patterns/filters

**Comment by kaylachumley** [comment]
in design review with Lucia! @andrew-ronaldson

**Comment by kaylachumley** [comment]
https://www.figma.com/design/MSr6kVEOuAxmPOkjg7x8PO/branch/VMKcJaMd6a9nnEOeDdVfHJ/PatternFly-6%3A-Patterns-%26-Extensions?m=auto&node-id=2-13&t=JVB7Zfi5Ht8DYUt5-1
