### ISSUE TITLE
Component groups: Details page

### ISSUE THREAD

**Issue by andrew-ronaldson** [patternfly/patternfly-design-kit#722]
The [Details page](https://www.patternfly.org/extensions/component-groups/details-page) Component group is a template for a typical page header in product. We currently have some of this functionality in the [page](https://www.figma.com/file/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?type=design&node-id=15%3A2586&mode=design&t=wHzGk3sgY5KHoHI4-1) component in our Figma kit so we could build upon that component rather than a brand new section in the extensions library.

```[tasklist]
### Tasks
- [x] Add Details page to v6 kit
```

**Comment by kaylachumley** [comment]
ready for review! @andrew-ronaldson
