### ISSUE TITLE
Component groups: Skeleton table

### ISSUE THREAD

**Issue by andrew-ronaldson** [patternfly/patternfly-design-kit#728]
The [Skeleton table](https://www.patternfly.org/extensions/component-groups/skeleton-table) component will require gradient animations in Figma prototyping. This functionality will only be visible when sharing a prototype link so this is lower priority than other Component groups.

```[tasklist]
### Tasks
- [x] Add Skeleton table to v6 kit
```

**Comment by kaylachumley** [comment]
Ready for review - [Figma Prototype here](https://www.figma.com/proto/MSr6kVEOuAxmPOkjg7x8PO/branch/5tFyMQDh8vKih9Bv2nr0KJ/PatternFly-6%3A-Patterns-%26-Extensions?page-id=2%3A15&type=design&node-id=1834-29768&viewport=-716%2C242%2C0.5&t=qVS6L1G5Yck4oXxl-1&scaling=min-zoom&mode=design)

**Comment by kaylachumley** [comment]
Proposed Motion tokens: 
While the gradient is loading from left to right, use _Global--Motion--Timing-Function--Accelerate_ and _Global--Motion--Duration--Short_

**Comment by andrew-ronaldson** [comment]
Closed as completed in Extensions library
