### ISSUE TITLE
Patterns & Extensions: Remove UI Shell from figma variants

### ISSUE THREAD

**Issue by kaylachumley** [patternfly/patternfly-design-kit#738]
- [ ] Pt 1: remove UI shell from extensions and patterns with page content.

Components/Patterns/Extensions that need added:
- Dashboard
- Catalog View
- Card View
 
Pt 2 in a [separate design issue](https://github.com/patternfly/patternfly-design-kit/issues/739)

**Comment by kaylachumley** [comment]
done! This issue needs a pt 2. Lucia and I discussed adding variants or component swaps for the extensions within the page component so that would require another issue and a bit more thought on which approach is better long term. Currently we can at least detach the page body and drop the extension within the content area. @andrew-ronaldson

**Comment by andrew-ronaldson** [comment]
Closed with follow up issue https://github.com/patternfly/patternfly-design-kit/issues/739
