### ISSUE TITLE
Toolbar - V6 kit variant updates

### ISSUE THREAD

**Issue by kaylachumley** [patternfly/patternfly-design-kit#752]
The toolbar component needs updated in the figma library with new variant semantics and booleans to enhance user experience
```[tasklist]
### Tasks
- [ ] update semantic spacers
- [ ] https://docs.google.com/document/d/14P9-MP4sccQcNMso-ibxwWDAusLDf3C54QzoJNZTu2s/edit#heading=h.38p8npwi1eif
```

**Comment by kaylachumley** [comment]
[ready for review](https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/branch/2le839DaIdl5i0KOxfAGSG/PatternFly-6%3A-Components?m=auto&node-id=3-49&t=oTMSck6pPoVAgUPz-1)! @lboehling

**Comment by lboehling** [comment]
Reviewed and merged to main! I fixed a few spacing issues and renamed some properties for clarity. Just added the changes to the main component library! Thanks for your work on this @kaylachumley!
