### ISSUE TITLE
Update README file to include flow chart

### ISSUE THREAD

**Issue by andrew-ronaldson** [patternfly/patternfly-design-kit#757]
## Goal
With the new v6 Figma kit the team needs to update documentation to reflect the changes, indentify troubleshooting methods, and direct users to a feature enhancement / bug issue. @kaylachumley has a great diagram that we can utilize and promote within the team.

**Comment by kaylachumley** [comment]
![Component Contributing guide](https://github.com/user-attachments/assets/63bc8ea2-7510-40b1-a6de-4ec2dd3e2909)

**Comment by kaylachumley** [comment]
[figma branch ](https://www.figma.com/design/62h3rosGP9vkssXNo4lCQH/branch/Z0A6vkecrGeRyyNdE7tcXK/PatternFly-6%3A-Onboarding-Resources?m=auto&node-id=2002-19&t=JOrD9JPkQdOCHyaH-1)w/ WIP contribution guide

**Comment by kaylachumley** [comment]
@andrew-ronaldson Ready for one final look through! https://www.figma.com/design/62h3rosGP9vkssXNo4lCQH/branch/Z0A6vkecrGeRyyNdE7tcXK/PatternFly-6%3A-Onboarding-Resources?m=auto&node-id=2002-63&t=pt3RBRE2ikFoSGi4-1

**Comment by andrew-ronaldson** [comment]
Closed by https://github.com/patternfly/patternfly-design-kit/issues/770
