### ISSUE TITLE
V6 Release -- Update Libraries and Post to Community Page

### ISSUE THREAD

**Issue by lboehling** [patternfly/patternfly-design-kit#759]
Once we've completed the last handful of design kit fixes and the PF6 final release is live, we should republish all of our libraries and update them on our community page. 

- [x] Update cover pages on all 3 libraries with latest release and date info 
- [x] Publish Design Tokens library FIRST (to Red Hat employees) 
- [x] Make sure updated Design tokens library is updated in Components library
- [x] Publish Components Library SECOND (to Red Hat employees) 
- [x] Make sure updated components library is pulled into Patterns & Extensions Library
- [x] Publish Patterns & Extensions Library THIRD (to Red Hat employees) 
- [x] Finally, go into each library and reupload them to our community page!

**Comment by kaylachumley** [comment]
Done!
