### ISSUE TITLE
Library: Compact Data Table Bug

### ISSUE THREAD

**Issue by lboehling** [patternfly/patternfly-design-kit#80]
@dongniwang mentioned that there are no overrides allowed for the kebab icon in data table rows. Can we allow overrides so users can select "none" when kebab icon is not needed? 

![Screen Shot 2019-08-02 at 1 28 56 PM](https://user-images.githubusercontent.com/46571616/62487836-d8ae8380-b790-11e9-9515-522abe0f846a.png)
![Screen Shot 2019-08-02 at 1 28 24 PM](https://user-images.githubusercontent.com/46571616/62487837-d8ae8380-b790-11e9-9341-8800773c3f08.png)

**Comment by gdoyle1** [comment]
Merged this fix
