### ISSUE TITLE
Chip group has extra padding in the middle

### ISSUE THREAD

**Issue by ajacobs21e** [patternfly/patternfly-design-kit#84]
Could be that the padding isn't pinned accurately or else it needs to be deleted. I can investigate further and fix as needed.

**Comment by ajacobs21e** [comment]
[chip group.zip](https://github.com/patternfly/patternfly-design-kit/files/3506741/chip.group.zip)
fixed this and also added in the close icon

**Comment by gdoyle1** [comment]
merged!
