### ISSUE TITLE
Data List / Desktop / 2. Expandable row / Collapsed / With line

### ISSUE THREAD

**Issue by bdellasc** [patternfly/patternfly-design-kit#88]
There doesn't appear to be divider lines in this type of data list row, even though it is labeled as having lines.

![DataTableRowLineMissing](https://user-images.githubusercontent.com/17882357/63461738-4c09f380-c427-11e9-9e39-47339f8c8404.png)

**Comment by gdoyle1** [comment]
@bdellasc have you updated your symbols? We had to consolidate a lot of items from data list and table and therefore that one got deleted. We only offer one now that is called Data List / Desktop / 2. Expandable row / Collapsed and it always has lines. Let me know if you can see that in your PF4 library

**Comment by bdellasc** [comment]
@gdoyle1 - that did it, thanks. Sorry for the extra noise on the repo. I need to make a habit of checking those notifications in Sketch
