### ISSUE TITLE
Switch

### ISSUE THREAD

**Issue by ajacobs21e** [patternfly/patternfly-design-kit#9]

**Comment by ajacobs21e** [comment]
I don't know how to label this or assign it to myself.

**Comment by ajacobs21e** [comment]
[Switch.zip](https://github.com/patternfly/patternfly-design-kit/files/1815842/Switch.zip)

**Comment by mcarrano** [comment]
@ajacobs21e Your Switch component has been merged into the master library on GitHub. Thanks for doing this. Will close out the issue.
