### ISSUE TITLE
Added twitter and facebook-alt social icons

### ISSUE THREAD

**Issue by ajacobs21e** [patternfly/patternfly-design-kit#90]
Portal uses the facebook icon that's just an f so I added that variant. Plus Twitter.
[TwitterFacebook.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/3556512/TwitterFacebook.sketch.zip)

@gdoyle1 I know you're working on the file so I didn't want to upload any changes and screw you up!

**Comment by gdoyle1** [comment]
Merged (also from your other issue)
