### ISSUE TITLE
Added missing expandable component

### ISSUE THREAD

**Issue by ajacobs21e** [patternfly/patternfly-design-kit#91]
https://pf4.patternfly.org/components/Expandable/examples/
This component is missing from the library.

I added this to the same file I used for the social icon addition so you can pull both from this file.

**Comment by ajacobs21e** [comment]
I also noticed that two of the accordion toggle states had an extra label within the padding so I fixed those too.
[Expandable+TwitterFacebook.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/3557356/Expandable%2BTwitterFacebook.sketch.zip)

**Comment by gdoyle1** [comment]
Merged!
