### ISSUE TITLE
Added alert variant - description dismissable

### ISSUE THREAD

**Issue by ajacobs21e** [patternfly/patternfly-design-kit#92]
I removed the close icon from the Description variant and created a fourth variant for the Description + close icon.

This will have an impact on anyone that's using this component currently but it stays consistent with our naming conventions. Do we need to release a blog post with this info?

[Alerts 2.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/3570575/Alerts.2.sketch.zip)

**Comment by gdoyle1** [comment]
Yes to blog post! I'll work on a draft now. Also just merged this
