### ISSUE TITLE
Add symbols for Dark Navigation System 

### ISSUE THREAD

**Issue by doruskova** [patternfly/patternfly-design-kit#94]
I'm adding a sketch file with the symbols for a Dark Navigation System. 
Sketch file: [DarkNav.zip](https://github.com/patternfly/patternfly-design-kit/files/3600130/DarkNav.zip)

Hope it'll be helpful to add these symbols (components) into the library under the Dark Theme section. @gdoyle1 

![single-level](https://user-images.githubusercontent.com/32618096/64688497-c230d180-d48c-11e9-9759-68f5a768754c.png)

**Comment by gdoyle1** [comment]
Merged! Thank you @doruskova
