### ISSUE TITLE
Add symbols for Empty State options

### ISSUE THREAD

**Issue by tiffanynolan** [patternfly/patternfly-design-kit#95]

**Comment by gdoyle1** [comment]
@tiffanynolan I added a template version of this as we already had symbols for the necessary elements. You'll find it in the template file here: https://sketch.cloud/s/R9k28

**Comment by katierik** [comment]
Can I open this and request specifically an empty state-sized icon? There is no way to use a symbol to create the 52px icon specified in the documentation. 
https://www.patternfly.org/v4/documentation/react/components/emptystate/
