### ISSUE TITLE
Template file update: Login & Toolbar

### ISSUE THREAD

**Issue by bdiring** [patternfly/patternfly-design-kit#98]
Added **Login** and **Toolbar** components to the "patternfly-template" Sketch file using PatternFly symbols (with the new RH font).

[patternfly-template.sketch.zip](https://github.com/patternfly/patternfly-design-kit/files/3647406/patternfly-template.sketch.zip)

Artboards added:

**Login** page:
Login spec
Login / Desktop / Simple
Login / Tablet / Simple
Login / Mobile / Simple
Login / Mobile / Simple - expanded
Login / Desktop / Invalid
Login / Tablet / Invalid
Login / Mobile / Invalid
Login / Mobile / Invalid - expanded

**Toolbar** page:
Toolbar spec
Top toolbar with bulk selector - desktop
Top toolbar with sort - desktop
Top toolbar with filter - desktop
Top toolbar with expanded filter - desktop
Top toolbar with bulk selector - mobile xs
Top toolbar with sort - mobile xs
Top toolbar with filter - mobile xs

**Comment by gdoyle1** [comment]
Merged!
