### ISSUE TITLE
Patternfly library - design kit - Disabled state form still uses Overpass instead of Red Hat Text

### ISSUE THREAD

**Issue by jknilans** [patternfly/patternfly-design-kit#99]
It looks like the disabled state form field's content still uses Overpass font instead of Red Hat Text. For reference:
![disabled state content](https://user-images.githubusercontent.com/25486044/65797211-a4c25f80-e13c-11e9-97d0-de396870c0a8.png)

Let me know if you have any questions. Thanks!

**Comment by gdoyle1** [comment]
@jknilans I'm actually not seeing this happen with this symbol. Did you maybe change the state of the input field to disabled using the Patternfly 4 symbol library or existing document symbols? When I change the input field to disabled with PatternFly, it works as expected.

Here is the symbol I believe we are both talking about 
<img width="259" alt="Screen Shot 2019-09-28 at 5 08 01 AM" src="https://user-images.githubusercontent.com/30870144/65814336-1d153900-e1ae-11e9-888c-792c14277ee4.png">

**Comment by jknilans** [comment]
@gdoyle1 I tried it again and I think you are probably right. I must have selected the disabled state from a document symbol. Thanks for checking!
